/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@shashes.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@shashes.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NIMCALL(NI, murmurHash__pureZhashes_192)(NU8* x, NI xLen_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NU32, rotl32__pureZhashes_180)(NU32 x, NI r);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError)(void);
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NIM_BOOL nimInErrorMode__system_4240;
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
static N_INLINE(NU32, rotl32__pureZhashes_180)(NU32 x, NI r) {
	NU32 result;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_5;
	nimfr_("rotl32", "/usr/lib/nim/pure/hashes.nim");
{	result = (NU32)0;
	nimln_(300, "/usr/lib/nim/pure/hashes.nim");
	if (nimSubInt(((NI) 32), r, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_5)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NU32)((NU32)((NU32)(x) << (NU32)(r)) | (NU32)((NU32)(x) >> (NU32)((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_5))));
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, murmurHash__pureZhashes_192)(NU8* x, NI xLen_0) {
	NI result;
	NI size;
	NI stepSize;
	NI n;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_2;
	NU32 h1;
	NI i;
	NU32 k1_2;
	NI rem;
	NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_6;
NIM_BOOL* nimErr_;
	nimfr_("murmurHash", "/usr/lib/nim/pure/hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(311, "/usr/lib/nim/pure/hashes.nim");
	size = xLen_0;
	nimln_(312, "/usr/lib/nim/pure/hashes.nim");
	stepSize = ((NI) 4);
	nimln_(313, "/usr/lib/nim/pure/hashes.nim");
	if (stepSize == 0){ raiseDivByZero(); goto BeforeRet_;
}
	if (nimDivInt(size, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_2)) { raiseOverflow(); goto BeforeRet_;
};
	n = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_2);
	h1 = (NU32)0;
	nimln_(316, "/usr/lib/nim/pure/hashes.nim");
	i = ((NI) 0);
	{
		nimln_(319, "/usr/lib/nim/pure/hashes.nim");
		while (1) {
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_3;
			NU32 k1;
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_4;
			if (nimMulInt(n, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_3)) { raiseOverflow(); goto BeforeRet_;
};
			if (!(i < (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_3))) goto LA2;
			k1 = (NU32)0;
			nimln_(327, "/usr/lib/nim/pure/hashes.nim");
			if (i < 0 || i >= xLen_0){ raiseIndexError2(i,xLen_0-1); goto BeforeRet_;
}
			k1 = (*((NU32*) ((&x[i]))));
			nimln_(328, "/usr/lib/nim/pure/hashes.nim");
			if (nimAddInt(i, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_4)) { raiseOverflow(); goto BeforeRet_;
};
			i = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_4);
			nimln_(330, "/usr/lib/nim/pure/hashes.nim");
			k1 = (NU32)((NU32)(k1) * (NU32)(((NU32) IL64(3432918353))));
			nimln_(331, "/usr/lib/nim/pure/hashes.nim");
			k1 = rotl32__pureZhashes_180(k1, ((NI) 15));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(332, "/usr/lib/nim/pure/hashes.nim");
			k1 = (NU32)((NU32)(k1) * (NU32)(((NU32) 461845907)));
			nimln_(334, "/usr/lib/nim/pure/hashes.nim");
			h1 = (NU32)(h1 ^ k1);
			nimln_(335, "/usr/lib/nim/pure/hashes.nim");
			h1 = rotl32__pureZhashes_180(h1, ((NI) 13));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(336, "/usr/lib/nim/pure/hashes.nim");
			h1 = (NU32)((NU32)((NU32)((NU32)(h1) * (NU32)(((NU32) 5)))) + (NU32)(((NU32) IL64(3864292196))));
		} LA2: ;
	}
	k1_2 = (NU32)0;
	nimln_(340, "/usr/lib/nim/pure/hashes.nim");
	if (stepSize == 0){ raiseDivByZero(); goto BeforeRet_;
}
	if (nimModInt(size, stepSize, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_6)) { raiseOverflow(); goto BeforeRet_;
};
	rem = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_6);
	{
		nimln_(341, "/usr/lib/nim/pure/hashes.nim");
		while (1) {
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_7;
			NI TM__7tkD9cFJSchVDwHuwaY9bP9bA_8;
			if (!(((NI) 0) < rem)) goto LA4;
			nimln_(342, "/usr/lib/nim/pure/hashes.nim");
			if (nimSubInt(rem, ((NI) 1), &TM__7tkD9cFJSchVDwHuwaY9bP9bA_7)) { raiseOverflow(); goto BeforeRet_;
};
			rem = (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_7);
			nimln_(343, "/usr/lib/nim/pure/hashes.nim");
			if (nimAddInt(i, rem, &TM__7tkD9cFJSchVDwHuwaY9bP9bA_8)) { raiseOverflow(); goto BeforeRet_;
};
			if ((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8) < 0 || (NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8) >= xLen_0){ raiseIndexError2((NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8),xLen_0-1); goto BeforeRet_;
}
			k1_2 = (NU32)((NU32)((NU32)(k1_2) << (NU32)(((NI) 8))) | ((NU32) (x[(NI)(TM__7tkD9cFJSchVDwHuwaY9bP9bA_8)])));
		} LA4: ;
	}
	nimln_(344, "/usr/lib/nim/pure/hashes.nim");
	k1_2 = (NU32)((NU32)(k1_2) * (NU32)(((NU32) IL64(3432918353))));
	nimln_(345, "/usr/lib/nim/pure/hashes.nim");
	k1_2 = rotl32__pureZhashes_180(k1_2, ((NI) 15));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(346, "/usr/lib/nim/pure/hashes.nim");
	k1_2 = (NU32)((NU32)(k1_2) * (NU32)(((NU32) 461845907)));
	nimln_(347, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)(h1 ^ k1_2);
	nimln_(350, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)(h1 ^ ((NU32) (size)));
	nimln_(351, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU32)(((NI) 16))));
	nimln_(352, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)((NU32)(h1) * (NU32)(((NU32) IL64(2246822507))));
	nimln_(353, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU32)(((NI) 13))));
	nimln_(354, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)((NU32)(h1) * (NU32)(((NU32) IL64(3266489909))));
	nimln_(355, "/usr/lib/nim/pure/hashes.nim");
	h1 = (NU32)(h1 ^ (NU32)((NU32)(h1) >> (NU32)(((NI) 16))));
	nimln_(356, "/usr/lib/nim/pure/hashes.nim");
	result = ((NI) (h1));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_279)(NimStringV2 x) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("hash", "/usr/lib/nim/pure/hashes.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(388, "/usr/lib/nim/pure/hashes.nim");
	if ((x.len-1)-((NI) 0) != -1 && (((NI) 0) < 0 || ((NI) 0) >= x.len || (x.len-1) < 0 || (x.len-1) >= x.len)){ raiseIndexError(); goto BeforeRet_;
}
	result = murmurHash__pureZhashes_192((((x).p) ? ((NU8*)x.p->data+(((NI) 0))) : NIM_NIL), ((x.len-1))-(((NI) 0))+1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
