/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sparsecfg.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sparsecfg.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA;
typedef struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw tySequence__dl1tcid0VwP1mpWNDzitYw;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw_Content tySequence__dl1tcid0VwP1mpWNDzitYw_Content;
typedef struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q;
typedef struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct RootObj RootObj;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw;
typedef struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg;
typedef struct tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg;
typedef struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg;
typedef struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ tyTuple__FVrpX6NSm2kCOe3mqHLSLQ;
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct tySequence__dl1tcid0VwP1mpWNDzitYw {
  NI len; tySequence__dl1tcid0VwP1mpWNDzitYw_Content* p;
};
struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q {
tySequence__dl1tcid0VwP1mpWNDzitYw data;
NI counter;
NI first;
NI last;
};
struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q {
  NI len; tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content* p;
};
struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA {
tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q data;
NI counter;
NI first;
NI last;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg;
struct RootObj {
TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringV2* buffer, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringV2* line);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ {
  tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ Sup;
FILE* f;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg {
  RootObj Sup;
NI bufpos;
NimStringV2 buf;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg;
struct tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw {
tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg kind;
NimStringV2 literal;
};
struct tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw {
  tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg Sup;
tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw tok;
NimStringV2 filename;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ {
NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ {
NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {
tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ traceStack;
tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
typedef NU8 tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug;
struct tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg {
  RootObj Sup;
tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind;
union{
struct {NimStringV2 section;
} _kind_2;
struct {NimStringV2 key;
NimStringV2 value;
} _kind_3;
struct {NimStringV2 msg;
} _kind_4;
};
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg {
NI Field0;
NI Field1;
NimStringV2 Field2;
NimStringV2 Field3;
};


#ifndef tySequence__dl1tcid0VwP1mpWNDzitYw_Content_PP
#define tySequence__dl1tcid0VwP1mpWNDzitYw_Content_PP
struct tySequence__dl1tcid0VwP1mpWNDzitYw_Content { NI cap; tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ {
NI Field0;
NI Field1;
NimStringV2 Field2;
tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* Field3;
};


#ifndef tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content_PP
#define tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content_PP
struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q_Content { NI cap; tyTuple__FVrpX6NSm2kCOe3mqHLSLQ data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_753)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_530)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_539)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_762)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* dest, void* env);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__systemZio_495)(NimStringV2 filename, tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ*, newFileStream__pureZstreams_987)(FILE* f);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_2502)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* stream, NimStringV2 filename);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_57)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3263)(NimStringV2* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3164)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_66)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* dest, void* env);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__system_2723)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1725)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, newOrderedTable__pureZparsecfg_381)(NI initialSize);
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringV2 filename, NI lineOffset);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_136)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NI bufLen, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3269)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_45)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_229)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_183)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_87)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_100)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_217)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(NIM_CHAR*, X5BX5D___system_7055)(NimStringV2* s, NI i);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_187)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_118)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x);
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_101)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI* xi);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_321)(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* dest);
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result);
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_291)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3266)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldError2)(NimStringV2 f, NI discVal);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZparsecfg_327)(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* dest, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, npcerrorStr)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr, NimStringV2* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_155)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*, newOrderedTable__pureZparsecfg_2520)(NI initialSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_4290)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZparsecfg_1878)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** dest, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* src, NIM_BOOL cyclic);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**, X5BX5D___pureZparsecfg_4463)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringV2 key);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_2644)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, NimStringV2 key, NimStringV2 val);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_843)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringV2 key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val);
static N_INLINE(void, nimMarkCyclic)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_1875)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** dest);
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_14)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_740)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA** dest);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_57)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_920)(tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ** dest);
N_LIB_PRIVATE TNimTypeV2 NTIv2__UVxsO8EtsgVrmdBJlfhbxA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19 = { 2 | NIM_STRLIT_FLAG, "--" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20 = {2, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19};
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25 = {
0x00, 0x00, 0x00, 0x00, 0x01, 0xe0, 0xff, 0x03,
0xfe, 0xff, 0xff, 0x97, 0xfe, 0xff, 0xff, 0x07,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}
;
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_29 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_30 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_29};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_39 = { 1 | NIM_STRLIT_FLAG, "\012" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_40 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_39};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_47 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_39};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_73 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_74 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_73};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_76 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_77 = {1, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_76};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_78 = { 5 | NIM_STRLIT_FLAG, "[EOF]" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_79 = {5, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_78};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9blb2N9brhIlBVapT72kwOHg_;
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_80 = {0, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7};
static const struct {
  NI cap; NIM_CHAR data[66+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81 = { 66 | NIM_STRLIT_FLAG, "field \'value\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_82 = {66, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_83 = { 20 | NIM_STRLIT_FLAG, "$1($2, $3) Error: $4" };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_84 = {20, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_83};
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_85 = { 28 | NIM_STRLIT_FLAG, "symbol expected, but found: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_86 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_85};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_87 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_85};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_88 = {28, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_85};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_89 = { 25 | NIM_STRLIT_FLAG, "\']\' expected, but found: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_90 = {25, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_89};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_91 = { 15 | NIM_STRLIT_FLAG, "invalid token: " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_92 = {15, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_91};
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_93 = { 68 | NIM_STRLIT_FLAG, "field \'section\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_94 = {68, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_93};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_95 = {68, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_93};
static const struct {
  NI cap; NIM_CHAR data[64+1];
} TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_96 = { 64 | NIM_STRLIT_FLAG, "field \'key\' is not accessible for type \'CfgEvent\' using \'kind = " };
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_97 = {64, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_96};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_98 = {64, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_96};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_99 = {66, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_100 = {66, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_101 = {2, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_102 = {64, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_96};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_103 = {66, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81};
static const NimStringV2 TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_104 = {66, (NimStrPayload*)&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_81};
extern NIM_BOOL nimInErrorMode__system_4240;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/usr/lib/nim/system/arithmetics.nim");
	nimln_(418, "/usr/lib/nim/system/arithmetics.nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/usr/lib/nim/system/orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(475, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		nimln_(476, "/usr/lib/nim/system/orc.nim");
		nimln_(63, "/usr/lib/nim/system/arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		nimln_(477, "/usr/lib/nim/system/orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;
			nimln_(478, "/usr/lib/nim/system/orc.nim");
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2;
			nimln_(481, "/usr/lib/nim/system/orc.nim");
			if (nimSubInt((*cell).rc, ((NI) 16), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2);
		}
		LA6_: ;
		nimln_(483, "/usr/lib/nim/system/orc.nim");
		rememberCycle__system_3164(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_57)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* dest) {
	eqdestroy___system_3263((&(*dest).Sup.buf));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest).Sup.input);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.input);
	}
	LA4_: ;
	eqdestroy___system_3263((&(*dest).tok.literal));
	eqdestroy___system_3263((&(*dest).filename));
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, add__system_2723)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6;
	nimfr_("add", "/usr/lib/nim/system/cellseqs_v2.nim");
{	nimln_(20, "/usr/lib/nim/system/cellseqs_v2.nim");
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3;
		tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4;
		void* T5_;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5;
		if (!((*s).cap <= (*s).len)) goto LA3_;
		nimln_(21, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).cap, ((NI) 3), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3)) { raiseOverflow(); goto BeforeRet_;
};
		(*s).cap = (NI)((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3) / ((NI) 2));
		nimln_(25, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).cap, ((NI) 8), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4)) < ((NI) 0) || ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T5_ = (void*)0;
		T5_ = allocImpl__system_1725(((NI) ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4))));
		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
		nimln_(26, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).len, ((NI) 8), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5)) < ((NI) 0) || ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5))));
		nimln_(30, "/usr/lib/nim/system/cellseqs_v2.nim");
		dealloc(((void*) ((*s).d)));
		nimln_(31, "/usr/lib/nim/system/cellseqs_v2.nim");
		(*s).d = d;
	}
	LA3_: ;
	nimln_(33, "/usr/lib/nim/system/cellseqs_v2.nim");
	colontmp_ = c;
	colontmp__2 = t;
	(*s).d[(*s).len].Field0 = colontmp_;
	(*s).d[(*s).len].Field1 = colontmp__2;
	nimln_(34, "/usr/lib/nim/system/cellseqs_v2.nim");
	if (nimAddInt((*s).len, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6)) { raiseOverflow(); goto BeforeRet_;
};
	(*s).len = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {
	void** p;
	nimfr_("nimTraceRefDyn", "/usr/lib/nim/system/orc.nim");
	nimln_(130, "/usr/lib/nim/system/orc.nim");
	p = ((void**) (q));
	nimln_(131, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		nimln_(132, "/usr/lib/nim/system/orc.nim");
		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
		nimln_(133, "/usr/lib/nim/system/orc.nim");
		add__system_2723((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZparsecfg_66)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* dest, void* env) {
	nimTraceRefDyn(&(*dest).Sup.input, env);
}
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_183)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI pos) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("handleCRLF", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(307, "/usr/lib/nim/pure/parsecfg.nim");
	if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
	switch (((NU8)((*c).Sup.buf.p->data[pos]))) {
	case 13:
	{
		nimln_(308, "/usr/lib/nim/pure/parsecfg.nim");
		result = handleCR__pureZlexbase_87(&c->Sup, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case 10:
	{
		nimln_(309, "/usr/lib/nim/pure/parsecfg.nim");
		result = handleLF__pureZlexbase_100(&c->Sup, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		nimln_(310, "/usr/lib/nim/pure/parsecfg.nim");
		result = pos;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_229)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI pos;
NIM_BOOL* nimErr_;
	nimfr_("skip", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(369, "/usr/lib/nim/pure/parsecfg.nim");
	pos = (*c).Sup.bufpos;
	{
		nimln_(370, "/usr/lib/nim/pure/parsecfg.nim");
		while (1) {
			nimln_(371, "/usr/lib/nim/pure/parsecfg.nim");
			if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			switch (((NU8)((*c).Sup.buf.p->data[pos]))) {
			case 32:
			case 9:
			{
				NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12;
				nimln_(373, "/usr/lib/nim/pure/parsecfg.nim");
				if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12)) { raiseOverflow(); goto BeforeRet_;
};
				pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12);
			}
			break;
			case 35:
			case 59:
			{
				{
					nimln_(375, "/usr/lib/nim/pure/parsecfg.nim");
					while (1) {
						NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13;
						if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
						if (!!((((NU8)((*c).Sup.buf.p->data[pos])) == ((NU8)(13)) || ((NU8)((*c).Sup.buf.p->data[pos])) == ((NU8)(10)) || ((NU8)((*c).Sup.buf.p->data[pos])) == ((NU8)(0))))) goto LA6;
						if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13)) { raiseOverflow(); goto BeforeRet_;
};
						pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13);
					} LA6: ;
				}
			}
			break;
			case 13:
			case 10:
			{
				nimln_(377, "/usr/lib/nim/pure/parsecfg.nim");
				pos = handleCRLF__pureZparsecfg_183(c, pos);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			break;
			default:
			{
				nimln_(379, "/usr/lib/nim/pure/parsecfg.nim");
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	nimln_(380, "/usr/lib/nim/pure/parsecfg.nim");
	(*c).Sup.bufpos = pos;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22;
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23;
{	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	if (nimAddInt((*s).len, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22)) { raiseOverflow(); goto BeforeRet_;
};
	(*(*s).p).data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22)] = 0;
	if (nimAddInt((*s).len, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23)) { raiseOverflow(); goto BeforeRet_;
};
	(*s).len = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23);
	}BeforeRet_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_2330(s);
	}
	LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_7055)(NimStringV2* s, NI i) {
	NIM_CHAR* result;
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26;
	nimfr_("[]", "/usr/lib/nim/system.nim");
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s)));
	nimln_(2652, "/usr/lib/nim/system.nim");
	if (nimSubInt((*s).len, i, &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26)) { raiseOverflow(); goto BeforeRet_;
};
	if ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26) < 0 || (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26) >= (*s).len){ raiseIndexError2((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26),(*s).len-1); goto BeforeRet_;
}
	result = (&(*s).p->data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_217)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
	NI pos;
	nimfr_("getSymbol", "/usr/lib/nim/pure/parsecfg.nim");
{	nimln_(356, "/usr/lib/nim/pure/parsecfg.nim");
	pos = (*c).Sup.bufpos;
	{
		nimln_(357, "/usr/lib/nim/pure/parsecfg.nim");
		while (1) {
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24;
			nimln_(358, "/usr/lib/nim/pure/parsecfg.nim");
			if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			nimAddCharV1((&(*tok).literal), (*c).Sup.buf.p->data[pos]);
			nimln_(359, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24)) { raiseOverflow(); goto BeforeRet_;
};
			pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24);
			nimln_(360, "/usr/lib/nim/pure/parsecfg.nim");
			{
				if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
				if (!!(((TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25[(NU)(((NU8)((*c).Sup.buf.p->data[pos])))>>3] &(1U<<((NU)(((NU8)((*c).Sup.buf.p->data[pos])))&7U)))!=0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
		}
	} LA1: ;
	{
		nimln_(362, "/usr/lib/nim/pure/parsecfg.nim");
		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < (*tok).literal.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_7055((&(*tok).literal), ((NI) 1));
			T9_ = ((NU8)((*T11_)) == (NU8)(32));
			LA10_: ;
			if (!T9_) goto LA8;
			nimln_(363, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimSubInt((*tok).literal.len, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27)) < ((NI) 0) || ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			setLengthStrV2((&(*tok).literal), ((NI) ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27))));
		} LA8: ;
	}
	nimln_(365, "/usr/lib/nim/pure/parsecfg.nim");
	(*c).Sup.bufpos = pos;
	nimln_(366, "/usr/lib/nim/pure/parsecfg.nim");
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_42;
		if (!(((NI) 0) < src.len)) goto LA3_;
		if (nimAddInt(src.len, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41)) < ((NI) 0) || ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_41))));
		if (nimAddInt((*dest).len, src.len, &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_42)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_42);
	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x) {
	NIM_BOOL result;
	nimfr_("handleHexChar", "/usr/lib/nim/std/private/decode_helpers.nim");
{	result = (NIM_BOOL)0;
	nimln_(16, "/usr/lib/nim/std/private/decode_helpers.nim");
	result = NIM_TRUE;
	nimln_(17, "/usr/lib/nim/std/private/decode_helpers.nim");
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_60;
		nimln_(18, "/usr/lib/nim/std/private/decode_helpers.nim");
		if (nimSubInt(((NU8)(c)), ((NI) 48), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_60)) { raiseOverflow(); goto BeforeRet_;
};
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_60));
	}
	break;
	case 97 ... 102:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_61;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_62;
		nimln_(19, "/usr/lib/nim/std/private/decode_helpers.nim");
		if (nimSubInt(((NU8)(c)), ((NI) 97), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_61)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_61), ((NI) 10), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_62)) { raiseOverflow(); goto BeforeRet_;
};
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_62));
	}
	break;
	case 65 ... 70:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_63;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_64;
		nimln_(20, "/usr/lib/nim/std/private/decode_helpers.nim");
		if (nimSubInt(((NU8)(c)), ((NI) 65), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_63)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_63), ((NI) 10), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_64)) { raiseOverflow(); goto BeforeRet_;
};
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_64));
	}
	break;
	default:
	{
		nimln_(22, "/usr/lib/nim/std/private/decode_helpers.nim");
		result = NIM_FALSE;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_101)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI* xi) {
	nimfr_("handleDecChars", "/usr/lib/nim/pure/parsecfg.nim");
{	{
		nimln_(251, "/usr/lib/nim/pure/parsecfg.nim");
		while (1) {
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_67;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_68;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_69;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_70;
			if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			if (!(((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos])) >= ((NU8)(48)) && ((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos])) <= ((NU8)(57)))) goto LA2;
			nimln_(252, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimMulInt((*xi), ((NI) 10), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_67)) { raiseOverflow(); goto BeforeRet_;
};
			if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			if (nimSubInt(((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos])), ((NI) 48), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_68)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_67), (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_68), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_69)) { raiseOverflow(); goto BeforeRet_;
};
			(*xi) = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_69);
			nimln_(253, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_70)) { raiseOverflow(); goto BeforeRet_;
};
			(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_70);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_118)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_46;
NIM_BOOL* nimErr_;
	nimfr_("getEscapedChar", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(256, "/usr/lib/nim/pure/parsecfg.nim");
	if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_46)) { raiseOverflow(); goto BeforeRet_;
};
	(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_46);
	nimln_(257, "/usr/lib/nim/pure/parsecfg.nim");
	if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
	switch (((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos]))) {
	case 110:
	case 78:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_48;
		nimln_(259, "/usr/lib/nim/pure/parsecfg.nim");
		prepareAdd((&(*tok).literal), 1);
appendString((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_47);
		nimln_(260, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_48)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_48);
	}
	break;
	case 114:
	case 82:
	case 99:
	case 67:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_49;
		nimln_(262, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 13);
		nimln_(263, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_49)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_49);
	}
	break;
	case 108:
	case 76:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_50;
		nimln_(265, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 10);
		nimln_(266, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_50)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_50);
	}
	break;
	case 102:
	case 70:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_51;
		nimln_(268, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 12);
		nimln_(269, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_51)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_51);
	}
	break;
	case 101:
	case 69:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_52;
		nimln_(271, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 27);
		nimln_(272, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_52)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_52);
	}
	break;
	case 97:
	case 65:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_53;
		nimln_(274, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 7);
		nimln_(275, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_53)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_53);
	}
	break;
	case 98:
	case 66:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_54;
		nimln_(277, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 8);
		nimln_(278, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_54)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_54);
	}
	break;
	case 118:
	case 86:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_55;
		nimln_(280, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 11);
		nimln_(281, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_55)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_55);
	}
	break;
	case 116:
	case 84:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_56;
		nimln_(283, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 9);
		nimln_(284, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_56)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_56);
	}
	break;
	case 39:
	case 34:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_57;
		nimln_(286, "/usr/lib/nim/pure/parsecfg.nim");
		if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
		nimAddCharV1((&(*tok).literal), (*c).Sup.buf.p->data[(*c).Sup.bufpos]);
		nimln_(287, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_57)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_57);
	}
	break;
	case 92:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_58;
		nimln_(289, "/usr/lib/nim/pure/parsecfg.nim");
		nimAddCharV1((&(*tok).literal), 92);
		nimln_(290, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_58)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_58);
	}
	break;
	case 120:
	case 88:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_59;
		NI xi;
		nimln_(292, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_59)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_59);
		nimln_(293, "/usr/lib/nim/pure/parsecfg.nim");
		xi = ((NI) 0);
		nimln_(294, "/usr/lib/nim/pure/parsecfg.nim");
		{
			NIM_BOOL T15_;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_65;
			if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			T15_ = (NIM_BOOL)0;
			T15_ = handleHexChar__stdZprivateZdecode95helpers_1((*c).Sup.buf.p->data[(*c).Sup.bufpos], (&xi));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T15_) goto LA16_;
			nimln_(295, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_65)) { raiseOverflow(); goto BeforeRet_;
};
			(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_65);
			nimln_(296, "/usr/lib/nim/pure/parsecfg.nim");
			{
				NIM_BOOL T20_;
				NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_66;
				if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
				T20_ = (NIM_BOOL)0;
				T20_ = handleHexChar__stdZprivateZdecode95helpers_1((*c).Sup.buf.p->data[(*c).Sup.bufpos], (&xi));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!T20_) goto LA21_;
				nimln_(297, "/usr/lib/nim/pure/parsecfg.nim");
				if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_66)) { raiseOverflow(); goto BeforeRet_;
};
				(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_66);
			}
			LA21_: ;
		}
		LA16_: ;
		nimln_(298, "/usr/lib/nim/pure/parsecfg.nim");
		if ((xi) < ((NI) 0) || (xi) > ((NI) 255)){ raiseRangeErrorI(xi, ((NI) 0), ((NI) 255)); goto BeforeRet_;
}
		nimAddCharV1((&(*tok).literal), ((NIM_CHAR) (((NI) (xi)))));
	}
	break;
	case 48 ... 57:
	{
		NI xi_2;
		nimln_(300, "/usr/lib/nim/pure/parsecfg.nim");
		xi_2 = ((NI) 0);
		nimln_(301, "/usr/lib/nim/pure/parsecfg.nim");
		handleDecChars__pureZparsecfg_101(c, (&xi_2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(302, "/usr/lib/nim/pure/parsecfg.nim");
		{
			if (!(xi_2 <= ((NI) 255))) goto LA26_;
			if ((xi_2) < ((NI) 0) || (xi_2) > ((NI) 255)){ raiseRangeErrorI(xi_2, ((NI) 0), ((NI) 255)); goto BeforeRet_;
}
			nimAddCharV1((&(*tok).literal), ((NIM_CHAR) (((NI) (xi_2)))));
		}
		goto LA24_;
		LA26_: ;
		{
			nimln_(303, "/usr/lib/nim/pure/parsecfg.nim");
			(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
		}
		LA24_: ;
	}
	break;
	default:
	{
		nimln_(304, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_187)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode) {
	NI pos;
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_33;
NIM_BOOL* nimErr_;
	nimfr_("getString", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(313, "/usr/lib/nim/pure/parsecfg.nim");
	if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_33)) { raiseOverflow(); goto BeforeRet_;
};
	pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_33);
	nimln_(314, "/usr/lib/nim/pure/parsecfg.nim");
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2);
	nimln_(315, "/usr/lib/nim/pure/parsecfg.nim");
	{
		NIM_BOOL T3_;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_35;
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_44;
		T3_ = (NIM_BOOL)0;
		if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
		T3_ = ((NU8)((*c).Sup.buf.p->data[pos]) == (NU8)(34));
		if (!(T3_)) goto LA4_;
		if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34)) { raiseOverflow(); goto BeforeRet_;
};
		if ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34) < 0 || (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34) >= (*c).Sup.buf.len){ raiseIndexError2((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34),(*c).Sup.buf.len-1); goto BeforeRet_;
}
		T3_ = ((NU8)((*c).Sup.buf.p->data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_34)]) == (NU8)(34));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(317, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt(pos, ((NI) 2), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_35)) { raiseOverflow(); goto BeforeRet_;
};
		pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_35);
		nimln_(319, "/usr/lib/nim/pure/parsecfg.nim");
		pos = handleCRLF__pureZparsecfg_183(c, pos);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			nimln_(320, "/usr/lib/nim/pure/parsecfg.nim");
			while (1) {
				nimln_(321, "/usr/lib/nim/pure/parsecfg.nim");
				if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
				switch (((NU8)((*c).Sup.buf.p->data[pos]))) {
				case 34:
				{
					NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_38;
					nimln_(323, "/usr/lib/nim/pure/parsecfg.nim");
					{
						NIM_BOOL T12_;
						NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36;
						NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37;
						T12_ = (NIM_BOOL)0;
						if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36)) { raiseOverflow(); goto BeforeRet_;
};
						if ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36) < 0 || (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36) >= (*c).Sup.buf.len){ raiseIndexError2((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36),(*c).Sup.buf.len-1); goto BeforeRet_;
}
						T12_ = ((NU8)((*c).Sup.buf.p->data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_36)]) == (NU8)(34));
						if (!(T12_)) goto LA13_;
						if (nimAddInt(pos, ((NI) 2), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37)) { raiseOverflow(); goto BeforeRet_;
};
						if ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37) < 0 || (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37) >= (*c).Sup.buf.len){ raiseIndexError2((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37),(*c).Sup.buf.len-1); goto BeforeRet_;
}
						T12_ = ((NU8)((*c).Sup.buf.p->data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_37)]) == (NU8)(34));
						LA13_: ;
						if (!T12_) goto LA14_;
						goto LA7;
					}
					LA14_: ;
					nimln_(324, "/usr/lib/nim/pure/parsecfg.nim");
					nimAddCharV1((&(*tok).literal), 34);
					nimln_(325, "/usr/lib/nim/pure/parsecfg.nim");
					if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_38)) { raiseOverflow(); goto BeforeRet_;
};
					pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_38);
				}
				break;
				case 13:
				case 10:
				{
					nimln_(327, "/usr/lib/nim/pure/parsecfg.nim");
					pos = handleCRLF__pureZparsecfg_183(c, pos);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(328, "/usr/lib/nim/pure/parsecfg.nim");
					prepareAdd((&(*tok).literal), 1);
appendString((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_40);
				}
				break;
				case 0:
				{
					nimln_(330, "/usr/lib/nim/pure/parsecfg.nim");
					(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					nimln_(331, "/usr/lib/nim/pure/parsecfg.nim");
					goto LA7;
				}
				break;
				default:
				{
					NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_43;
					nimln_(333, "/usr/lib/nim/pure/parsecfg.nim");
					if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
					nimAddCharV1((&(*tok).literal), (*c).Sup.buf.p->data[pos]);
					nimln_(334, "/usr/lib/nim/pure/parsecfg.nim");
					if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_43)) { raiseOverflow(); goto BeforeRet_;
};
					pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_43);
				}
				break;
				}
			}
		} LA7: ;
		nimln_(335, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt(pos, ((NI) 3), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_44)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_44);
	}
	goto LA1_;
	LA5_: ;
	{
		{
			nimln_(338, "/usr/lib/nim/pure/parsecfg.nim");
			while (1) {
				NIM_CHAR ch;
				nimln_(339, "/usr/lib/nim/pure/parsecfg.nim");
				if (pos < 0 || pos >= (*c).Sup.buf.len){ raiseIndexError2(pos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
				ch = (*c).Sup.buf.p->data[pos];
				nimln_(340, "/usr/lib/nim/pure/parsecfg.nim");
				{
					NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_45;
					if (!((NU8)(ch) == (NU8)(34))) goto LA24_;
					nimln_(341, "/usr/lib/nim/pure/parsecfg.nim");
					if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_45)) { raiseOverflow(); goto BeforeRet_;
};
					pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_45);
					nimln_(342, "/usr/lib/nim/pure/parsecfg.nim");
					goto LA20;
				}
				LA24_: ;
				nimln_(343, "/usr/lib/nim/pure/parsecfg.nim");
				{
					if (!(((NU8)(ch)) == ((NU8)(13)) || ((NU8)(ch)) == ((NU8)(10)) || ((NU8)(ch)) == ((NU8)(0)))) goto LA28_;
					nimln_(344, "/usr/lib/nim/pure/parsecfg.nim");
					(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					nimln_(345, "/usr/lib/nim/pure/parsecfg.nim");
					goto LA20;
				}
				LA28_: ;
				nimln_(346, "/usr/lib/nim/pure/parsecfg.nim");
				{
					NIM_BOOL T32_;
					T32_ = (NIM_BOOL)0;
					T32_ = ((NU8)(ch) == (NU8)(92));
					if (!(T32_)) goto LA33_;
					T32_ = !(rawMode);
					LA33_: ;
					if (!T32_) goto LA34_;
					nimln_(347, "/usr/lib/nim/pure/parsecfg.nim");
					(*c).Sup.bufpos = pos;
					nimln_(348, "/usr/lib/nim/pure/parsecfg.nim");
					getEscapedChar__pureZparsecfg_118(c, tok);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(349, "/usr/lib/nim/pure/parsecfg.nim");
					pos = (*c).Sup.bufpos;
				}
				goto LA30_;
				LA34_: ;
				{
					NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_71;
					nimln_(351, "/usr/lib/nim/pure/parsecfg.nim");
					nimAddCharV1((&(*tok).literal), ch);
					nimln_(352, "/usr/lib/nim/pure/parsecfg.nim");
					if (nimAddInt(pos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_71)) { raiseOverflow(); goto BeforeRet_;
};
					pos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_71);
				}
				LA30_: ;
			}
		} LA20: ;
		nimln_(353, "/usr/lib/nim/pure/parsecfg.nim");
		(*c).Sup.bufpos = pos;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_45)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
NIM_BOOL* nimErr_;
	nimfr_("rawGetTok", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(383, "/usr/lib/nim/pure/parsecfg.nim");
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	nimln_(384, "/usr/lib/nim/pure/parsecfg.nim");
	setLengthStrV2((&(*tok).literal), ((NI) 0));
	nimln_(385, "/usr/lib/nim/pure/parsecfg.nim");
	skip__pureZparsecfg_229(c);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(386, "/usr/lib/nim/pure/parsecfg.nim");
	if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
	switch (((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos]))) {
	case 61:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14;
		nimln_(388, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 3);
		nimln_(389, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16);
	}
	break;
	case 45:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17;
		nimln_(392, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17);
		nimln_(393, "/usr/lib/nim/pure/parsecfg.nim");
		{
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18;
			if ((*c).Sup.bufpos < 0 || (*c).Sup.bufpos >= (*c).Sup.buf.len){ raiseIndexError2((*c).Sup.bufpos,(*c).Sup.buf.len-1); goto BeforeRet_;
}
			if (!((NU8)((*c).Sup.buf.p->data[(*c).Sup.bufpos]) == (NU8)(45))) goto LA5_;
			nimln_(394, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18)) { raiseOverflow(); goto BeforeRet_;
};
			(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18);
			nimln_(395, "/usr/lib/nim/pure/parsecfg.nim");
			(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 7);
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20);
		}
		goto LA3_;
		LA5_: ;
		{
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21;
			nimln_(398, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimSubInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21)) { raiseOverflow(); goto BeforeRet_;
};
			(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21);
			nimln_(399, "/usr/lib/nim/pure/parsecfg.nim");
			getSymbol__pureZparsecfg_217(c, tok);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA3_: ;
	}
	break;
	case 58:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28;
		nimln_(401, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 4);
		nimln_(402, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_30);
	}
	break;
	case 114:
	case 82:
	{
		nimln_(405, "/usr/lib/nim/pure/parsecfg.nim");
		{
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31;
			NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_32;
			if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31)) { raiseOverflow(); goto BeforeRet_;
};
			if ((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31) < 0 || (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31) >= (*c).Sup.buf.len){ raiseIndexError2((NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31),(*c).Sup.buf.len-1); goto BeforeRet_;
}
			if (!((NU8)((*c).Sup.buf.p->data[(NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_31)]) == (NU8)(34))) goto LA12_;
			nimln_(406, "/usr/lib/nim/pure/parsecfg.nim");
			if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_32)) { raiseOverflow(); goto BeforeRet_;
};
			(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_32);
			nimln_(407, "/usr/lib/nim/pure/parsecfg.nim");
			getString__pureZparsecfg_187(c, tok, NIM_TRUE);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA10_;
		LA12_: ;
		{
			nimln_(409, "/usr/lib/nim/pure/parsecfg.nim");
			getSymbol__pureZparsecfg_217(c, tok);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA10_: ;
	}
	break;
	case 91:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_72;
		nimln_(411, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 5);
		nimln_(412, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_72)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_72);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_74);
	}
	break;
	case 93:
	{
		NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_75;
		nimln_(415, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6);
		nimln_(416, "/usr/lib/nim/pure/parsecfg.nim");
		if (nimAddInt((*c).Sup.bufpos, ((NI) 1), &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_75)) { raiseOverflow(); goto BeforeRet_;
};
		(*c).Sup.bufpos = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_75);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_77);
	}
	break;
	case 34:
	{
		nimln_(419, "/usr/lib/nim/pure/parsecfg.nim");
		getString__pureZparsecfg_187(c, tok, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case 0:
	{
		nimln_(421, "/usr/lib/nim/pure/parsecfg.nim");
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 1);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*tok).literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_79);
	}
	break;
	default:
	{
		nimln_(423, "/usr/lib/nim/pure/parsecfg.nim");
		getSymbol__pureZparsecfg_217(c, tok);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringV2 filename, NI lineOffset) {
	NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11;
	tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T2_;
NIM_BOOL* nimErr_;
	nimfr_("open", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(227, "/usr/lib/nim/pure/parsecfg.nim");
	open__pureZlexbase_136(&c->Sup, input, ((NI) 8192), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	eqsink___system_3269((&(*c).filename), filename);
	nimln_(228, "/usr/lib/nim/pure/parsecfg.nim");
	filename.len = 0; filename.p = NIM_NIL;
	nimln_(229, "/usr/lib/nim/pure/parsecfg.nim");
	(*c).tok.kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	eqsink___system_3269((&(*c).tok.literal), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10);
	nimln_(231, "/usr/lib/nim/pure/parsecfg.nim");
	if (nimAddInt((*c).Sup.lineNumber, lineOffset, &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11)) { raiseOverflow(); goto LA1_;
};
	(*c).Sup.lineNumber = (NI)(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11);
	nimln_(232, "/usr/lib/nim/pure/parsecfg.nim");
	T2_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
	T2_ = c;
	rawGetTok__pureZparsecfg_45(T2_, (&(*c).tok));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&filename));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_321)(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* dest) {
	switch ((*dest).kind) {
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
	{
		eqdestroy___system_3263((&(*dest)._kind_2.section));
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
	{
		eqdestroy___system_3263((&(*dest)._kind_3.key));
		eqdestroy___system_3263((&(*dest)._kind_3.value));
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
	{
		eqdestroy___system_3263((&(*dest)._kind_4.msg));
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZparsecfg_327)(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* dest, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* src) {
	switch ((*dest).kind) {
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
	{
		eqdestroy___system_3263((&(*dest)._kind_2.section));
		(*dest)._kind_2.section.len = 0; (*dest)._kind_2.section.p = NIM_NIL;
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
	{
		eqdestroy___system_3263((&(*dest)._kind_3.key));
		(*dest)._kind_3.key.len = 0; (*dest)._kind_3.key.p = NIM_NIL;
		eqdestroy___system_3263((&(*dest)._kind_3.value));
		(*dest)._kind_3.value.len = 0; (*dest)._kind_3.value.p = NIM_NIL;
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
	{
		eqdestroy___system_3263((&(*dest)._kind_4.msg));
		(*dest)._kind_4.msg.len = 0; (*dest)._kind_4.msg.p = NIM_NIL;
	}
	break;
	}
	(*dest).kind = 0;
	(*dest).kind = (*src).kind;
	switch ((*dest).kind) {
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
	{
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
	{
		(*dest)._kind_2.section = (*src)._kind_2.section;
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
	{
		(*dest)._kind_3.key = (*src)._kind_3.key;
		(*dest)._kind_3.value = (*src)._kind_3.value;
	}
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
	{
		(*dest)._kind_4.msg = (*src)._kind_4.msg;
	}
	break;
	}
	(*dest).Sup.m_type = (*src).Sup.m_type;
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI result;
	nimfr_("getLine", "/usr/lib/nim/pure/parsecfg.nim");
	result = (NI)0;
	nimln_(244, "/usr/lib/nim/pure/parsecfg.nim");
	result = (*c).Sup.lineNumber;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("getColumn", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(240, "/usr/lib/nim/pure/parsecfg.nim");
	result = getColNumber__pureZlexbase_155((&(*c).Sup), (*c).Sup.bufpos);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, npcerrorStr)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NimStringV2 msg) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T2_;
	NI T3_;
	NI T4_;
NIM_BOOL* nimErr_;
	nimfr_("errorStr", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	nimln_(428, "/usr/lib/nim/pure/parsecfg.nim");
	T2_[0] = (*c).filename;
	nimln_(429, "/usr/lib/nim/pure/parsecfg.nim");
	T3_ = (NI)0;
	T3_ = npcgetLine(c);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD_ = dollar___systemZdollars_3(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[1] = colontmpD_;
	T4_ = (NI)0;
	T4_ = npcgetColumn(c);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__2 = dollar___systemZdollars_3(T4_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[2] = colontmpD__2;
	T2_[3] = msg;
	nimln_(428, "/usr/lib/nim/pure/parsecfg.nim");
	result = nsuFormatOpenArray(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_84, T2_, 4);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&msg));
		eqdestroy___system_3263((&colontmpD__2));
		eqdestroy___system_3263((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_291)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result) {
NIM_BOOL* nimErr_;
	nimfr_("getKeyValPair", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
	(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
	nimln_(449, "/usr/lib/nim/pure/parsecfg.nim");
	{
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T7_;
		if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA3_;
		nimln_(450, "/usr/lib/nim/pure/parsecfg.nim");
		switch (kind) {
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
		{
			tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug colontmpD_;
			NimStringV2 colontmpD__2;
			colontmpD_ = (tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug)0;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
			nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			colontmpD_ = kind;
			(*Result).kind = colontmpD_;
			colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqcopy___system_3266((&colontmpD__2), (*c).tok.literal);
			(*Result)._kind_3.key = colontmpD__2;
			(*Result)._kind_3.value = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_80;
		}
		break;
		default:
		{
		}
		break;
		}
		nimln_(454, "/usr/lib/nim/pure/parsecfg.nim");
		T7_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T7_ = c;
		rawGetTok__pureZparsecfg_45(T7_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(455, "/usr/lib/nim/pure/parsecfg.nim");
		{
			tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T12_;
			tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T20_;
			if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 3) || (*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 4))) goto LA10_;
			nimln_(456, "/usr/lib/nim/pure/parsecfg.nim");
			T12_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
			T12_ = c;
			rawGetTok__pureZparsecfg_45(T12_, (&(*c).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(457, "/usr/lib/nim/pure/parsecfg.nim");
			{
				if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA15_;
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				if (!(((12 &((NU8)1<<((NU)((*Result).kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_82, (NI)(*Result).kind); goto BeforeRet_;
} 
				eqcopy___system_3266((&(*Result)._kind_3.value), (*c).tok.literal);
			}
			goto LA13_;
			LA15_: ;
			{
				tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg T18_;
				NimStringV2 T19_;
				nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
				T18_.Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
				nimZeroMem((void*)(&T18_), sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
				T18_.Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
				T18_.kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
				nimln_(461, "/usr/lib/nim/pure/parsecfg.nim");
				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = rawNewString((*c).tok.literal.len + 28);
appendString((&T19_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_86);
appendString((&T19_), (*c).tok.literal);
				T18_._kind_4.msg = npcerrorStr((&(*c)), T19_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
				eqsink___pureZparsecfg_327(Result, (&T18_));
			}
			LA13_: ;
			nimln_(462, "/usr/lib/nim/pure/parsecfg.nim");
			T20_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
			T20_ = c;
			rawGetTok__pureZparsecfg_45(T20_, (&(*c).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA10_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringV2 T22_;
		NimStringV2 T23_;
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T24_;
		nimln_(464, "/usr/lib/nim/pure/parsecfg.nim");
		nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
		(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
		nimln_(465, "/usr/lib/nim/pure/parsecfg.nim");
		T22_.len = 0; T22_.p = NIM_NIL;
		T22_ = rawNewString((*c).tok.literal.len + 28);
appendString((&T22_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_87);
appendString((&T22_), (*c).tok.literal);
		T23_.len = 0; T23_.p = NIM_NIL;
		T23_ = npcerrorStr((&(*c)), T22_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*Result)._kind_4.msg = T23_;
		nimln_(466, "/usr/lib/nim/pure/parsecfg.nim");
		T24_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T24_ = c;
		rawGetTok__pureZparsecfg_45(T24_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result) {
NIM_BOOL* nimErr_;
	nimfr_("next", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(470, "/usr/lib/nim/pure/parsecfg.nim");
	switch ((*c).tok.kind) {
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 1):
	{
		nimln_(472, "/usr/lib/nim/pure/parsecfg.nim");
		nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
		(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0);
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 7):
	{
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T3_;
		nimln_(474, "/usr/lib/nim/pure/parsecfg.nim");
		T3_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T3_ = c;
		rawGetTok__pureZparsecfg_45(T3_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(475, "/usr/lib/nim/pure/parsecfg.nim");
		getKeyValPair__pureZparsecfg_291(c, ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3), Result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2):
	{
		nimln_(477, "/usr/lib/nim/pure/parsecfg.nim");
		getKeyValPair__pureZparsecfg_291(c, ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2), Result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 5):
	{
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T6_;
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T14_;
		nimln_(479, "/usr/lib/nim/pure/parsecfg.nim");
		T6_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T6_ = c;
		rawGetTok__pureZparsecfg_45(T6_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(480, "/usr/lib/nim/pure/parsecfg.nim");
		{
			NimStringV2 colontmpD_;
			if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA9_;
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			nimln_(481, "/usr/lib/nim/pure/parsecfg.nim");
			nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1);
			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqcopy___system_3266((&colontmpD_), (*c).tok.literal);
			(*Result)._kind_2.section = colontmpD_;
		}
		goto LA7_;
		LA9_: ;
		{
			NimStringV2 T12_;
			NimStringV2 T13_;
			nimln_(483, "/usr/lib/nim/pure/parsecfg.nim");
			nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
			nimln_(484, "/usr/lib/nim/pure/parsecfg.nim");
			T12_.len = 0; T12_.p = NIM_NIL;
			T12_ = rawNewString((*c).tok.literal.len + 28);
appendString((&T12_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_88);
appendString((&T12_), (*c).tok.literal);
			T13_.len = 0; T13_.p = NIM_NIL;
			T13_ = npcerrorStr((&(*c)), T12_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*Result)._kind_4.msg = T13_;
		}
		LA7_: ;
		nimln_(485, "/usr/lib/nim/pure/parsecfg.nim");
		T14_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T14_ = c;
		rawGetTok__pureZparsecfg_45(T14_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(486, "/usr/lib/nim/pure/parsecfg.nim");
		{
			tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T19_;
			if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6))) goto LA17_;
			nimln_(487, "/usr/lib/nim/pure/parsecfg.nim");
			T19_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
			T19_ = c;
			rawGetTok__pureZparsecfg_45(T19_, (&(*c).tok));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA15_;
		LA17_: ;
		{
			tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg T21_;
			NimStringV2 T22_;
			nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
			T21_.Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			nimZeroMem((void*)(&T21_), sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			T21_.Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			T21_.kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
			nimln_(490, "/usr/lib/nim/pure/parsecfg.nim");
			T22_.len = 0; T22_.p = NIM_NIL;
			T22_ = rawNewString((*c).tok.literal.len + 25);
appendString((&T22_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_90);
appendString((&T22_), (*c).tok.literal);
			T21_._kind_4.msg = npcerrorStr((&(*c)), T22_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
			eqsink___pureZparsecfg_327(Result, (&T21_));
		}
		LA15_: ;
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 3):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 4):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6):
	{
		NimStringV2 T24_;
		NimStringV2 T25_;
		tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* T26_;
		nimln_(492, "/usr/lib/nim/pure/parsecfg.nim");
		nimZeroMem((void*)Result, sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
		(*Result).Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
		nimln_(493, "/usr/lib/nim/pure/parsecfg.nim");
		T24_.len = 0; T24_.p = NIM_NIL;
		T24_ = rawNewString((*c).tok.literal.len + 15);
appendString((&T24_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_92);
appendString((&T24_), (*c).tok.literal);
		T25_.len = 0; T25_.p = NIM_NIL;
		T25_ = npcerrorStr((&(*c)), T24_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*Result)._kind_4.msg = T25_;
		nimln_(494, "/usr/lib/nim/pure/parsecfg.nim");
		T26_ = (tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw*)0;
		T26_ = c;
		rawGetTok__pureZparsecfg_45(T26_, (&(*c).tok));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimMarkCyclic)(void* p) {
	nimfr_("nimMarkCyclic", "/usr/lib/nim/system/orc.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
NIM_BOOL* nimErr_;
	nimfr_("close", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	nimln_(236, "/usr/lib/nim/pure/parsecfg.nim");
	close__pureZlexbase_14(&c->Sup);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_2502)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* stream, NimStringV2 filename) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* dict;
	NimStringV2 curSection;
	tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw p;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
	nimfr_("loadConfig", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	dict = NIM_NIL;
	curSection.len = 0; curSection.p = NIM_NIL;
	nimZeroMem((void*)(&p), sizeof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw));
	p.Sup.Sup.m_type = (&NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_);
	nimln_(508, "/usr/lib/nim/pure/parsecfg.nim");
	dict = newOrderedTable__pureZparsecfg_381(((NI) 32));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(509, "/usr/lib/nim/pure/parsecfg.nim");
	curSection = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8;
	nimln_(513, "/usr/lib/nim/pure/parsecfg.nim");
	blitTmp = filename;
	filename.len = 0; filename.p = NIM_NIL;
	npcopen((&p), stream, blitTmp, ((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		nimln_(514, "/usr/lib/nim/pure/parsecfg.nim");
		while (1) {
			tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg e;
			nimZeroMem((void*)(&e), sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			e.Sup.m_type = (&NTIv2__9blb2N9brhIlBVapT72kwOHg_);
			nimln_(515, "/usr/lib/nim/pure/parsecfg.nim");
			npcnext((&p), (&e));
			if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			nimln_(516, "/usr/lib/nim/pure/parsecfg.nim");
			switch (e.kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			{
				nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
				eqdestroy___pureZparsecfg_321((&e));
				nimln_(518, "/usr/lib/nim/pure/parsecfg.nim");
				goto LA2;
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			{
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				if (!(((2 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_94, (NI)e.kind); goto LA4_;
} 
				eqsink___system_3269((&curSection), e._kind_2.section);
				nimln_(520, "/usr/lib/nim/pure/parsecfg.nim");
				if (!(((2 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_95, (NI)e.kind); goto LA4_;
} 
				e._kind_2.section.len = 0; e._kind_2.section.p = NIM_NIL;
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			{
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t;
				NimStringV2 colontmpD_;
				NimStringV2 blitTmp_2;
				NimStringV2 T15_;
				NimStringV2 blitTmp_3;
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* blitTmp_4;
				t = NIM_NIL;
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimln_(522, "/usr/lib/nim/pure/parsecfg.nim");
				t = newOrderedTable__pureZparsecfg_2520(((NI) 32));
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				nimln_(523, "/usr/lib/nim/pure/parsecfg.nim");
				{
					NIM_BOOL T11_;
					tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** T14_;
					T11_ = (NIM_BOOL)0;
					T11_ = hasKey__pureZparsecfg_4290(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					if (!T11_) goto LA12_;
					nimln_(287, "/usr/lib/nim/system.nim");
					nimln_(524, "/usr/lib/nim/pure/parsecfg.nim");
					T14_ = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
					T14_ = X5BX5D___pureZparsecfg_4463(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
					nimln_(287, "/usr/lib/nim/system.nim");
					eqcopy___pureZparsecfg_1878(&t, (*T14_), NIM_FALSE);
				}
				LA12_: ;
				nimln_(525, "/usr/lib/nim/pure/parsecfg.nim");
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_97, (NI)e.kind); goto LA8_;
} 
				blitTmp_2 = e._kind_3.key;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_98, (NI)e.kind); goto LA8_;
} 
				e._kind_3.key.len = 0; e._kind_3.key.p = NIM_NIL;
				T15_.len = 0; T15_.p = NIM_NIL;
				T15_ = blitTmp_2;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_99, (NI)e.kind); goto LA8_;
} 
				blitTmp_3 = e._kind_3.value;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_100, (NI)e.kind); goto LA8_;
} 
				e._kind_3.value.len = 0; e._kind_3.value.p = NIM_NIL;
				X5BX5Deq___pureZparsecfg_2644(t, T15_, blitTmp_3);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				nimln_(526, "/usr/lib/nim/pure/parsecfg.nim");
				colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				eqcopy___system_3266((&colontmpD_), curSection);
				nimln_(526, "/usr/lib/nim/pure/parsecfg.nim");
				blitTmp_4 = t;
				nimMarkCyclic(t);
				t = 0;
				X5BX5Deq___pureZparsecfg_843(dict, colontmpD_, blitTmp_4);
				if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
				{
					LA8_:;
				}
				{
					nimln_(287, "/usr/lib/nim/system.nim");
					eqdestroy___pureZparsecfg_1875(&t);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			{
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* c;
				NimStringV2 colontmpD__2;
				NimStringV2 T26_;
				NimStringV2 T27_;
				NimStringV2 blitTmp_5;
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* blitTmp_6;
				c = NIM_NIL;
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				nimln_(528, "/usr/lib/nim/pure/parsecfg.nim");
				c = newOrderedTable__pureZparsecfg_2520(((NI) 32));
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				nimln_(529, "/usr/lib/nim/pure/parsecfg.nim");
				{
					NIM_BOOL T22_;
					tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** T25_;
					T22_ = (NIM_BOOL)0;
					T22_ = hasKey__pureZparsecfg_4290(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
					if (!T22_) goto LA23_;
					nimln_(287, "/usr/lib/nim/system.nim");
					nimln_(530, "/usr/lib/nim/pure/parsecfg.nim");
					T25_ = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
					T25_ = X5BX5D___pureZparsecfg_4463(dict, curSection);
					if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
					nimln_(287, "/usr/lib/nim/system.nim");
					eqcopy___pureZparsecfg_1878(&c, (*T25_), NIM_FALSE);
				}
				LA23_: ;
				nimln_(531, "/usr/lib/nim/pure/parsecfg.nim");
				T26_.len = 0; T26_.p = NIM_NIL;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_102, (NI)e.kind); goto LA19_;
} 
				T26_ = rawNewString(e._kind_3.key.len + 2);
appendString((&T26_), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_101);
appendString((&T26_), e._kind_3.key);
				T27_.len = 0; T27_.p = NIM_NIL;
				T27_ = T26_;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_103, (NI)e.kind); goto LA19_;
} 
				blitTmp_5 = e._kind_3.value;
				if (!(((12 &((NU8)1<<((NU)(e.kind)&7U)))!=0))) 				{ raiseFieldError2(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_104, (NI)e.kind); goto LA19_;
} 
				e._kind_3.value.len = 0; e._kind_3.value.p = NIM_NIL;
				X5BX5Deq___pureZparsecfg_2644(c, T27_, blitTmp_5);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				nimln_(532, "/usr/lib/nim/pure/parsecfg.nim");
				colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				eqcopy___system_3266((&colontmpD__2), curSection);
				nimln_(532, "/usr/lib/nim/pure/parsecfg.nim");
				blitTmp_6 = c;
				nimMarkCyclic(c);
				c = 0;
				X5BX5Deq___pureZparsecfg_843(dict, colontmpD__2, blitTmp_6);
				if (NIM_UNLIKELY(*nimErr_)) goto LA19_;
				{
					LA19_:;
				}
				{
					nimln_(287, "/usr/lib/nim/system.nim");
					eqdestroy___pureZparsecfg_1875(&c);
				}
				if (NIM_UNLIKELY(*nimErr_)) goto LA4_;
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			{
				nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
				eqdestroy___pureZparsecfg_321((&e));
				nimln_(534, "/usr/lib/nim/pure/parsecfg.nim");
				goto LA2;
			}
			break;
			}
			{
				LA4_:;
			}
			{
				nimln_(452, "/usr/lib/nim/pure/parsecfg.nim");
				eqdestroy___pureZparsecfg_321((&e));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
	} LA2: ;
	nimln_(535, "/usr/lib/nim/pure/parsecfg.nim");
	npcclose((&p));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(536, "/usr/lib/nim/pure/parsecfg.nim");
	result = dict;
	dict = 0;
	{
		LA1_:;
	}
	{
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&filename));
		nimln_(227, "/usr/lib/nim/pure/parsecfg.nim");
		eqdestroy___pureZparsecfg_57((&p));
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&curSection));
		nimln_(1824, "/usr/lib/nim/pure/collections/tables.nim");
		eqdestroy___pureZparsecfg_740(&dict);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_5167)(NimStringV2 filename) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ* fileStream;
	FILE* file;
	NimStringV2 blitTmp;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
	nimfr_("loadConfig", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	fileStream = NIM_NIL;
	nimln_(540, "/usr/lib/nim/pure/parsecfg.nim");
	file = open__systemZio_495(filename, ((tyEnum_FileMode__ZJfK20XeZ9bv2j1pZjw9aswg) 0), ((NI) -1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(541, "/usr/lib/nim/pure/parsecfg.nim");
	fileStream = newFileStream__pureZstreams_987(file);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(543, "/usr/lib/nim/pure/parsecfg.nim");
	blitTmp = filename;
	filename.len = 0; filename.p = NIM_NIL;
	result = loadConfig__pureZparsecfg_2502(&fileStream->Sup, blitTmp);
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	{
		LA2_:;
	}
	{
		oldNimErrFin2_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimln_(542, "/usr/lib/nim/pure/parsecfg.nim");
		close__pureZstreams_57(&fileStream->Sup);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin2_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&filename));
		nimln_(1312, "/usr/lib/nim/pure/streams.nim");
		eqdestroy___pureZstreams_920(&fileStream);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, newConfig__pureZparsecfg_377)(void) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
NIM_BOOL* nimErr_;
	nimfr_("newConfig", "/usr/lib/nim/pure/parsecfg.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(503, "/usr/lib/nim/pure/parsecfg.nim");
	result = newOrderedTable__pureZparsecfg_381(((NI) 32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsparsecfgdotnim_DatInit000)(void) {
NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.destructor = (void*)eqdestroy___pureZparsecfg_530; NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.size = sizeof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q); NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.align = NIM_ALIGNOF(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q); NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.name = "|__aBRulY0v9b6F4b7NLhEoU1Q|";
; NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.traceImpl = (void*)eqtrace___pureZparsecfg_539; NTIv2__aBRulY0v9b6F4b7NLhEoU1Q_.flags = 0;NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.destructor = (void*)eqdestroy___pureZparsecfg_753; NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.size = sizeof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA); NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.align = NIM_ALIGNOF(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA); NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.name = "|__UVxsO8EtsgVrmdBJlfhbxA|";
; NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.traceImpl = (void*)eqtrace___pureZparsecfg_762; NTIv2__UVxsO8EtsgVrmdBJlfhbxA_.flags = 0;NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.destructor = (void*)eqdestroy___pureZparsecfg_57; NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.size = sizeof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw); NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.align = NIM_ALIGNOF(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw); NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.name = "|stdlib.parsecfg.CfgParser|stdlib.lexbase.BaseLexer|RootObj|";
; NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.traceImpl = (void*)eqtrace___pureZparsecfg_66; NTIv2__r3Jw8HBNj9b667nxe8vVd9bw_.flags = 0;NTIv2__9blb2N9brhIlBVapT72kwOHg_.destructor = (void*)eqdestroy___pureZparsecfg_321; NTIv2__9blb2N9brhIlBVapT72kwOHg_.size = sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg); NTIv2__9blb2N9brhIlBVapT72kwOHg_.align = NIM_ALIGNOF(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg); NTIv2__9blb2N9brhIlBVapT72kwOHg_.name = "|stdlib.parsecfg.CfgEvent|RootObj|";
; NTIv2__9blb2N9brhIlBVapT72kwOHg_.traceImpl = (void*)NIM_NIL; NTIv2__9blb2N9brhIlBVapT72kwOHg_.flags = 0;}

