/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sstrutils.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sstrutils.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_720)(NU64 x, NI len, NIM_BOOL handleNegative);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2* s);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s, NimStringV2 formatstr, NimStringV2* a, NI aLen_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_2266)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_2254)(NimStringV2 x, NimStringV2* inArray, NI inArrayLen_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_1)(NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7460)(NimStringV2 s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3263)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_3)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3269)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_3 = { 16 | NIM_STRLIT_FLAG, "0123456789ABCDEF" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_4 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_3};
extern TNimTypeV2 NTIv2__yoNlBGx0D2tRizIdhQuENw_;
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_9 = { 21 | NIM_STRLIT_FLAG, "invalid format string" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_10 = {21, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_9};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_58 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_59 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_58};
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NIM_BOOL nimInErrorMode__system_4240;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_2330(s);
	}
	LA5_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_720)(NU64 x, NI len, NIM_BOOL handleNegative) {
	NimStringV2 result;
	NU64 n;
	nimfr_("toHexImpl", "/usr/lib/nim/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(904, "/usr/lib/nim/pure/strutils.nim");
	n = x;
	nimln_(905, "/usr/lib/nim/pure/strutils.nim");
	result = mnewString(((NI) (len)));
	{
		NI j;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_2;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		nimln_(906, "/usr/lib/nim/pure/strutils.nim");
		if (nimSubInt(((NI) (len)), ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_2)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_2);
		nimln_(33, "/usr/lib/nim/system/iterators_1.nim");
		res = colontmp_;
		{
			nimln_(34, "/usr/lib/nim/system/iterators_1.nim");
			while (1) {
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_5;
				if (!(((NI) 0) <= res)) goto LA3;
				nimln_(906, "/usr/lib/nim/pure/strutils.nim");
				j = res;
				if (j < 0 || j >= result.len){ raiseIndexError2(j,result.len-1); goto BeforeRet_;
}
				nimPrepareStrMutationV2((&result));
				nimln_(907, "/usr/lib/nim/pure/strutils.nim");
				if ((NU64)(n & 15ULL) < 0 || (NU64)(n & 15ULL) >= TM__JGc9b9bh2D3nTdUR7TGyq8aA_4.len){ raiseIndexError2((NU64)(n & 15ULL),TM__JGc9b9bh2D3nTdUR7TGyq8aA_4.len-1); goto BeforeRet_;
}
				result.p->data[j] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_4.p->data[(NU64)(n & 15ULL)];
				nimln_(908, "/usr/lib/nim/pure/strutils.nim");
				n = (NU64)((NU64)(n) >> (NU64)(((NI) 4)));
				nimln_(906, "/usr/lib/nim/pure/strutils.nim");
				{
					NIM_BOOL T6_;
					nimln_(910, "/usr/lib/nim/pure/strutils.nim");
					T6_ = (NIM_BOOL)0;
					T6_ = (n == 0ULL);
					if (!(T6_)) goto LA7_;
					T6_ = handleNegative;
					LA7_: ;
					if (!T6_) goto LA8_;
					n = 18446744073709551615ULL;
				}
				LA8_: ;
				nimln_(36, "/usr/lib/nim/system/iterators_1.nim");
				if (nimSubInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_5)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6471)(NU16 x) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("toHex", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(933, "/usr/lib/nim/pure/strutils.nim");
	result = toHexImpl__pureZstrutils_720(((NU64) (x)), ((NI) 4), ((NU16)(x) < (NU16)(((NU16) 0))));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_2266)(void) {
	tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw* T1_;
	nimfr_("invalidFormatString", "/usr/lib/nim/pure/strutils.nim");
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw*) nimNewObj(sizeof(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw), NIM_ALIGNOF(tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__yoNlBGx0D2tRizIdhQuENw_);
	(*T1_).Sup.Sup.name = "ValueError";
	(*T1_).Sup.Sup.message = TM__JGc9b9bh2D3nTdUR7TGyq8aA_10;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	nimln_(2649, "/usr/lib/nim/pure/strutils.nim");
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "/usr/lib/nim/pure/strutils.nim", 2649);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_11;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_12;
		if (!(((NI) 0) < src.len)) goto LA3_;
		if (nimAddInt(src.len, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_11))));
		if (nimAddInt((*dest).len, src.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_12)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_12);
	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_15;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_16;
{	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	if (nimAddInt((*s).len, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) { raiseOverflow(); goto BeforeRet_;
};
	(*(*s).p).data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)] = 0;
	if (nimAddInt((*s).len, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_16)) { raiseOverflow(); goto BeforeRet_;
};
	(*s).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_16);
	}BeforeRet_: ;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_1)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "/usr/lib/nim/std/private/strimpl.nim");
{	result = (NIM_CHAR)0;
	nimln_(2, "/usr/lib/nim/std/private/strimpl.nim");
	{
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_34;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;
		nimln_(3, "/usr/lib/nim/std/private/strimpl.nim");
		if (nimAddInt(((NU8)(c)), ((NI) 32), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)) > ((NI) 255)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34), ((NI) 0), ((NI) 255)); goto BeforeRet_;
}
		result = ((NIM_CHAR) (((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_34)))));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(5, "/usr/lib/nim/std/private/strimpl.nim");
		result = c;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a, NimStringV2 b) {
	NI result;
	NI aLenX60gensym25_;
	NI bLenX60gensym25_;
	NI iX60gensym25_;
	NI jX60gensym25_;
NIM_BOOL* nimErr_;
	nimfr_("cmpIgnoreStyle", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym25_ = a.len;
	bLenX60gensym25_ = b.len;
	iX60gensym25_ = ((NI) 0);
	jX60gensym25_ = ((NI) 0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym25_;
			NIM_CHAR bbX60gensym25_;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym25_ < aLenX60gensym25_);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a.p->data[iX60gensym25_]) == (NU8)(95));
					LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym25_ += ((NI) 1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym25_ < bLenX60gensym25_);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b.p->data[jX60gensym25_]) == (NU8)(95));
					LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym25_ += ((NI) 1);
				} LA8: ;
			}
			{
				if (!(iX60gensym25_ < aLenX60gensym25_)) goto LA13_;
				colontmpD_ = toLowerAscii__stdZprivateZstrimpl_1(a.p->data[iX60gensym25_]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym25_ = colontmpD_;
			}
			goto LA11_;
			LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym25_ = colontmpD__2;
			}
			LA11_: ;
			{
				if (!(jX60gensym25_ < bLenX60gensym25_)) goto LA18_;
				colontmpD__3 = toLowerAscii__stdZprivateZstrimpl_1(b.p->data[jX60gensym25_]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym25_ = colontmpD__3;
			}
			goto LA16_;
			LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym25_ = colontmpD__4;
			}
			LA16_: ;
			result = (NI)(((NU8)(aaX60gensym25_)) - ((NU8)(bbX60gensym25_)));
			{
				if (!!((result == ((NI) 0)))) goto LA23_;
				goto BeforeRet_;
			}
			LA23_: ;
			{
				if (!(aLenX60gensym25_ <= iX60gensym25_)) goto LA27_;
				{
					if (!(bLenX60gensym25_ <= jX60gensym25_)) goto LA31_;
					result = ((NI) 0);
					goto BeforeRet_;
				}
				LA31_: ;
				result = ((NI) -1);
				goto BeforeRet_;
			}
			goto LA25_;
			LA27_: ;
			{
				if (!(bLenX60gensym25_ <= jX60gensym25_)) goto LA34_;
				result = ((NI) 1);
				goto BeforeRet_;
			}
			goto LA25_;
			LA34_: ;
			LA25_: ;
			iX60gensym25_ += ((NI) 1);
			jX60gensym25_ += ((NI) 1);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_2254)(NimStringV2 x, NimStringV2* inArray, NI inArrayLen_0) {
	NI result;
	NI i;
NIM_BOOL* nimErr_;
	nimfr_("findNormalized", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(2641, "/usr/lib/nim/pure/strutils.nim");
	i = ((NI) 0);
	{
		nimln_(2642, "/usr/lib/nim/pure/strutils.nim");
		while (1) {
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_35;
			if (!(i < (inArrayLen_0-1))) goto LA2;
			nimln_(2643, "/usr/lib/nim/pure/strutils.nim");
			{
				NI T5_;
				if (i < 0 || i >= inArrayLen_0){ raiseIndexError2(i,inArrayLen_0-1); goto BeforeRet_;
}
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x, inArray[i]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI) 0))) goto LA6_;
				result = i;
				goto BeforeRet_;
			}
			LA6_: ;
			nimln_(2644, "/usr/lib/nim/pure/strutils.nim");
			if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) { raiseOverflow(); goto BeforeRet_;
};
			i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_35);
		} LA2: ;
	}
	nimln_(2646, "/usr/lib/nim/pure/strutils.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s, NimStringV2 formatstr, NimStringV2* a, NI aLen_0) {
	NI i;
	NI num;
NIM_BOOL* nimErr_;
	nimfr_("addf", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2655, "/usr/lib/nim/pure/strutils.nim");
	i = ((NI) 0);
	nimln_(2656, "/usr/lib/nim/pure/strutils.nim");
	num = ((NI) 0);
	{
		nimln_(2657, "/usr/lib/nim/pure/strutils.nim");
		while (1) {
			if (!(i < formatstr.len)) goto LA2;
			nimln_(2658, "/usr/lib/nim/pure/strutils.nim");
			{
				NIM_BOOL T5_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_7;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_8;
				T5_ = (NIM_BOOL)0;
				if (i < 0 || i >= formatstr.len){ raiseIndexError2(i,formatstr.len-1); goto BeforeRet_;
}
				T5_ = ((NU8)(formatstr.p->data[i]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_7)) { raiseOverflow(); goto BeforeRet_;
};
				T5_ = ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_7) < formatstr.len);
				LA6_: ;
				if (!T5_) goto LA7_;
				nimln_(2659, "/usr/lib/nim/pure/strutils.nim");
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)) { raiseOverflow(); goto BeforeRet_;
};
				if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8) >= formatstr.len){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8),formatstr.len-1); goto BeforeRet_;
}
				switch (((NU8)(formatstr.p->data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_8)]))) {
				case 35:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_13;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_14;
					nimln_(2661, "/usr/lib/nim/pure/strutils.nim");
					{
						if (!((aLen_0-1) < num)) goto LA12_;
						invalidFormatString__pureZstrutils_2266();
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					LA12_: ;
					nimln_(2662, "/usr/lib/nim/pure/strutils.nim");
					if (num < 0 || num >= aLen_0){ raiseIndexError2(num,aLen_0-1); goto BeforeRet_;
}
					prepareAdd((&(*s)), a[num].len + 0);
appendString((&(*s)), a[num]);
					nimln_(2663, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) { raiseOverflow(); goto BeforeRet_;
};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_13);
					nimln_(2664, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(num, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_14)) { raiseOverflow(); goto BeforeRet_;
};
					num = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_14);
				}
				break;
				case 36:
				{
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_17;
					nimln_(2666, "/usr/lib/nim/pure/strutils.nim");
					nimAddCharV1((&(*s)), 36);
					nimln_(2667, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) { raiseOverflow(); goto BeforeRet_;
};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_17);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_18;
					NIM_BOOL negative;
					NI idx;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					nimln_(2669, "/usr/lib/nim/pure/strutils.nim");
					j = ((NI) 0);
					nimln_(2670, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_18)) { raiseOverflow(); goto BeforeRet_;
};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_18);
					nimln_(2671, "/usr/lib/nim/pure/strutils.nim");
					if (i < 0 || i >= formatstr.len){ raiseIndexError2(i,formatstr.len-1); goto BeforeRet_;
}
					negative = ((NU8)(formatstr.p->data[i]) == (NU8)(45));
					nimln_(2672, "/usr/lib/nim/pure/strutils.nim");
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_19;
						if (!negative) goto LA18_;
						if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) { raiseOverflow(); goto BeforeRet_;
};
						i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_19);
					}
					LA18_: ;
					{
						nimln_(2673, "/usr/lib/nim/pure/strutils.nim");
						while (1) {
							NIM_BOOL T22_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_20;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_21;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_22;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_23;
							T22_ = (NIM_BOOL)0;
							T22_ = (i < formatstr.len);
							if (!(T22_)) goto LA23_;
							if (i < 0 || i >= formatstr.len){ raiseIndexError2(i,formatstr.len-1); goto BeforeRet_;
}
							T22_ = (((NU8)(formatstr.p->data[i])) >= ((NU8)(48)) && ((NU8)(formatstr.p->data[i])) <= ((NU8)(57)));
							LA23_: ;
							if (!T22_) goto LA21;
							nimln_(2674, "/usr/lib/nim/pure/strutils.nim");
							if (nimMulInt(j, ((NI) 10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_20)) { raiseOverflow(); goto BeforeRet_;
};
							if (i < 0 || i >= formatstr.len){ raiseIndexError2(i,formatstr.len-1); goto BeforeRet_;
}
							if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_20), ((NU8)(formatstr.p->data[i])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) { raiseOverflow(); goto BeforeRet_;
};
							if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_21), ((NI) 48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_22)) { raiseOverflow(); goto BeforeRet_;
};
							j = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_22);
							nimln_(2675, "/usr/lib/nim/pure/strutils.nim");
							if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) { raiseOverflow(); goto BeforeRet_;
};
							i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_23);
						} LA21: ;
					}
					nimln_(2676, "/usr/lib/nim/pure/strutils.nim");
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_24;
						if (!!(negative)) goto LA26_;
						if (nimSubInt(j, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_24)) { raiseOverflow(); goto BeforeRet_;
};
						colontmpD_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_24);
						idx = colontmpD_;
					}
					goto LA24_;
					LA26_: ;
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_25;
						if (nimSubInt(aLen_0, j, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) { raiseOverflow(); goto BeforeRet_;
};
						colontmpD__2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_25);
						idx = colontmpD__2;
					}
					LA24_: ;
					nimln_(2677, "/usr/lib/nim/pure/strutils.nim");
					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx < ((NI) 0));
						if (T31_) goto LA32_;
						T31_ = ((aLen_0-1) < idx);
						LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_2266();
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					LA33_: ;
					nimln_(2678, "/usr/lib/nim/pure/strutils.nim");
					if (idx < 0 || idx >= aLen_0){ raiseIndexError2(idx,aLen_0-1); goto BeforeRet_;
}
					prepareAdd((&(*s)), a[idx].len + 0);
appendString((&(*s)), a[idx]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_26;
					NI k;
					NIM_BOOL negative_2;
					NI isNumber;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_39;
					nimln_(2680, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_26)) { raiseOverflow(); goto BeforeRet_;
};
					j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_26);
					nimln_(2681, "/usr/lib/nim/pure/strutils.nim");
					k = ((NI) 0);
					nimln_(2682, "/usr/lib/nim/pure/strutils.nim");
					if (j_2 < 0 || j_2 >= formatstr.len){ raiseIndexError2(j_2,formatstr.len-1); goto BeforeRet_;
}
					negative_2 = ((NU8)(formatstr.p->data[j_2]) == (NU8)(45));
					nimln_(2683, "/usr/lib/nim/pure/strutils.nim");
					{
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_27;
						if (!negative_2) goto LA38_;
						if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) { raiseOverflow(); goto BeforeRet_;
};
						j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_27);
					}
					LA38_: ;
					nimln_(2684, "/usr/lib/nim/pure/strutils.nim");
					isNumber = ((NI) 0);
					{
						nimln_(2685, "/usr/lib/nim/pure/strutils.nim");
						while (1) {
							NIM_BOOL T42_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_31;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr.len);
							if (!(T42_)) goto LA43_;
							if (j_2 < 0 || j_2 >= formatstr.len){ raiseIndexError2(j_2,formatstr.len-1); goto BeforeRet_;
}
							T42_ = !((((NU8)(formatstr.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr.p->data[j_2])) == ((NU8)(125))));
							LA43_: ;
							if (!T42_) goto LA41;
							nimln_(2686, "/usr/lib/nim/pure/strutils.nim");
							{
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_28;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_29;
								NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_30;
								if (j_2 < 0 || j_2 >= formatstr.len){ raiseIndexError2(j_2,formatstr.len-1); goto BeforeRet_;
}
								if (!(((NU8)(formatstr.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								nimln_(2687, "/usr/lib/nim/pure/strutils.nim");
								if (nimMulInt(k, ((NI) 10), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_28)) { raiseOverflow(); goto BeforeRet_;
};
								if (j_2 < 0 || j_2 >= formatstr.len){ raiseIndexError2(j_2,formatstr.len-1); goto BeforeRet_;
}
								if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_28), ((NU8)(formatstr.p->data[j_2])), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) { raiseOverflow(); goto BeforeRet_;
};
								if (nimSubInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_29), ((NI) 48), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_30)) { raiseOverflow(); goto BeforeRet_;
};
								k = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_30);
								nimln_(2688, "/usr/lib/nim/pure/strutils.nim");
								{
									if (!(isNumber == ((NI) 0))) goto LA50_;
									isNumber = ((NI) 1);
								}
								LA50_: ;
							}
							goto LA44_;
							LA46_: ;
							{
								nimln_(2690, "/usr/lib/nim/pure/strutils.nim");
								isNumber = ((NI) -1);
							}
							LA44_: ;
							nimln_(2691, "/usr/lib/nim/pure/strutils.nim");
							if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) { raiseOverflow(); goto BeforeRet_;
};
							j_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_31);
						} LA41: ;
					}
					nimln_(2692, "/usr/lib/nim/pure/strutils.nim");
					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber == ((NI) 1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						nimln_(2693, "/usr/lib/nim/pure/strutils.nim");
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_32;
							if (!!(negative_2)) goto LA59_;
							if (nimSubInt(k, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_32)) { raiseOverflow(); goto BeforeRet_;
};
							colontmpD__3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_32);
							idx_2 = colontmpD__3;
						}
						goto LA57_;
						LA59_: ;
						{
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_33;
							if (nimSubInt(aLen_0, k, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) { raiseOverflow(); goto BeforeRet_;
};
							colontmpD__4 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_33);
							idx_2 = colontmpD__4;
						}
						LA57_: ;
						nimln_(2694, "/usr/lib/nim/pure/strutils.nim");
						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI) 0));
							if (T64_) goto LA65_;
							T64_ = ((aLen_0-1) < idx_2);
							LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_2266();
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
						LA66_: ;
						nimln_(2695, "/usr/lib/nim/pure/strutils.nim");
						if (idx_2 < 0 || idx_2 >= aLen_0){ raiseIndexError2(idx_2,aLen_0-1); goto BeforeRet_;
}
						prepareAdd((&(*s)), a[idx_2].len + 0);
appendString((&(*s)), a[idx_2]);
					}
					goto LA53_;
					LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_36;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_37;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						nimln_(2697, "/usr/lib/nim/pure/strutils.nim");
						if (nimAddInt(i, ((NI) 2), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_36)) { raiseOverflow(); goto LA69_;
};
						if (nimSubInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) { raiseOverflow(); goto LA69_;
};
						colontmpD__5 = substr__system_7460(formatstr, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_36), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_37));
						x = findNormalized__pureZstrutils_2254(colontmpD__5, a, aLen_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						nimln_(2698, "/usr/lib/nim/pure/strutils.nim");
						{
							NIM_BOOL T72_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_38;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI) 0) <= x);
							if (!(T72_)) goto LA73_;
							T72_ = (x < (aLen_0-1));
							LA73_: ;
							if (!T72_) goto LA74_;
							if (nimAddInt(x, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)) { raiseOverflow(); goto LA69_;
};
							if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38) >= aLen_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38),aLen_0-1); goto LA69_;
}
							prepareAdd((&(*s)), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)].len + 0);
appendString((&(*s)), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_38)]);
						}
						goto LA70_;
						LA74_: ;
						{
							nimln_(2699, "/usr/lib/nim/pure/strutils.nim");
							invalidFormatString__pureZstrutils_2266();
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
						LA70_: ;
						{
							LA69_:;
						}
						{
							nimln_(54, "/usr/lib/nim/system/fatal.nim");
							eqdestroy___system_3263((&colontmpD__5));
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					LA53_: ;
					nimln_(2700, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(j_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) { raiseOverflow(); goto BeforeRet_;
};
					i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_39);
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_40;
					NI x_2;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_42;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_43;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					nimln_(2702, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_40)) { raiseOverflow(); goto LA80_;
};
					j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_40);
					{
						nimln_(2703, "/usr/lib/nim/pure/strutils.nim");
						while (1) {
							NIM_BOOL T83_;
							NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_41;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr.len);
							if (!(T83_)) goto LA84_;
							if (j_3 < 0 || j_3 >= formatstr.len){ raiseIndexError2(j_3,formatstr.len-1); goto LA80_;
}
							T83_ = (((NU8)(formatstr.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr.p->data[j_3])) == ((NU8)(95)));
							LA84_: ;
							if (!T83_) goto LA82;
							if (nimAddInt(j_3, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) { raiseOverflow(); goto LA80_;
};
							j_3 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_41);
						} LA82: ;
					}
					nimln_(2704, "/usr/lib/nim/pure/strutils.nim");
					if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_42)) { raiseOverflow(); goto LA80_;
};
					if (nimSubInt(j_3, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) { raiseOverflow(); goto LA80_;
};
					colontmpD__6 = substr__system_7460(formatstr, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_42), (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_43));
					x_2 = findNormalized__pureZstrutils_2254(colontmpD__6, a, aLen_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					nimln_(2705, "/usr/lib/nim/pure/strutils.nim");
					{
						NIM_BOOL T87_;
						NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_44;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI) 0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (aLen_0-1));
						LA88_: ;
						if (!T87_) goto LA89_;
						if (nimAddInt(x_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)) { raiseOverflow(); goto LA80_;
};
						if ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44) < 0 || (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44) >= aLen_0){ raiseIndexError2((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44),aLen_0-1); goto LA80_;
}
						prepareAdd((&(*s)), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)].len + 0);
appendString((&(*s)), a[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_44)]);
					}
					goto LA85_;
					LA89_: ;
					{
						nimln_(2706, "/usr/lib/nim/pure/strutils.nim");
						invalidFormatString__pureZstrutils_2266();
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
					LA85_: ;
					nimln_(2707, "/usr/lib/nim/pure/strutils.nim");
					i = j_3;
					{
						LA80_:;
					}
					{
						nimln_(54, "/usr/lib/nim/system/fatal.nim");
						eqdestroy___system_3263((&colontmpD__6));
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					nimln_(2709, "/usr/lib/nim/pure/strutils.nim");
					invalidFormatString__pureZstrutils_2266();
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
			LA7_: ;
			{
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_45;
				nimln_(2711, "/usr/lib/nim/pure/strutils.nim");
				if (i < 0 || i >= formatstr.len){ raiseIndexError2(i,formatstr.len-1); goto BeforeRet_;
}
				nimAddCharV1((&(*s)), formatstr.p->data[i]);
				nimln_(2712, "/usr/lib/nim/pure/strutils.nim");
				if (nimAddInt(i, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) { raiseOverflow(); goto BeforeRet_;
};
				i = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_45);
			}
			LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr, NimStringV2* a, NI aLen_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_6;
NIM_BOOL* nimErr_;
	nimfr_("%", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2759, "/usr/lib/nim/pure/strutils.nim");
	if (nimAddInt(formatstr.len, (NI)((NU32)(aLen_0) << (NU32)(((NI) 4))), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	result = rawNewString(((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_6))));
	nimln_(2760, "/usr/lib/nim/pure/strutils.nim");
	nsuAddf((&result), formatstr, a, aLen_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatVarargs)(NimStringV2 formatstr, NimStringV2* a, NI aLen_0) {
	NimStringV2 result;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_46;
NIM_BOOL* nimErr_;
	nimfr_("format", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(2777, "/usr/lib/nim/pure/strutils.nim");
	if (nimAddInt(formatstr.len, aLen_0, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	result = rawNewString(((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_46))));
	nimln_(2778, "/usr/lib/nim/pure/strutils.nim");
	nsuAddf((&result), formatstr, a, aLen_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c) {
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_48;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_49;
{	(*(*dest).p).data[(*dest).len] = c;
	if (nimAddInt((*dest).len, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)) { raiseOverflow(); goto BeforeRet_;
};
	(*(*dest).p).data[(NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_48)] = 0;
	if (nimAddInt((*dest).len, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_49)) { raiseOverflow(); goto BeforeRet_;
};
	(*dest).len = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_49);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuIntToStr)(NI x, NI minchars) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("intToStr", "/usr/lib/nim/pure/strutils.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(1057, "/usr/lib/nim/pure/strutils.nim");
	if (x == (-2147483647 -1)){ raiseOverflow(); goto BeforeRet_;
}
	result = dollar___systemZdollars_3((x > 0? (x) : -(x)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i;
		NI colontmp_;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_47;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(1058, "/usr/lib/nim/pure/strutils.nim");
		if (nimSubInt(((NI) (minchars)), result.len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_47)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
		nimln_(90, "/usr/lib/nim/system/iterators_1.nim");
		res = ((NI) 1);
		{
			nimln_(91, "/usr/lib/nim/system/iterators_1.nim");
			while (1) {
				NimStringV2 T4_;
				NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_50;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(1058, "/usr/lib/nim/pure/strutils.nim");
				i = res;
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				nimln_(1058, "/usr/lib/nim/pure/strutils.nim");
				T4_.len = 0; T4_.p = NIM_NIL;
				T4_ = rawNewString(result.len + 1);
appendChar((&T4_), 48);
appendString((&T4_), result);
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				eqsink___system_3269((&result), T4_);
				nimln_(93, "/usr/lib/nim/system/iterators_1.nim");
				if (nimAddInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_50)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_50);
			} LA3: ;
		}
	}
	nimln_(1060, "/usr/lib/nim/pure/strutils.nim");
	{
		NimStringV2 T9_;
		if (!(x < ((NI) 0))) goto LA7_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		nimln_(1061, "/usr/lib/nim/pure/strutils.nim");
		T9_.len = 0; T9_.p = NIM_NIL;
		T9_ = rawNewString(result.len + 1);
appendChar((&T9_), 45);
appendString((&T9_), result);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&result), T9_);
	}
	LA7_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/usr/lib/nim/system/arithmetics.nim");
	nimln_(418, "/usr/lib/nim/system/arithmetics.nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s, NIM_CHAR sub, NI start, NI last) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI L;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_51;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_52;
	nimfr_("find", "/usr/lib/nim/pure/strutils.nim");
{	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(1870, "/usr/lib/nim/pure/strutils.nim");
	{
		if (!(last == ((NI) 0))) goto LA3_;
		colontmpD_ = (s.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = last;
		last_2 = colontmpD__2;
	}
	LA1_: ;
	nimln_(1876, "/usr/lib/nim/pure/strutils.nim");
	if (nimSubInt(last_2, ((NI) (start)), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_51)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimAddInt((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_51), ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_52)) { raiseOverflow(); goto BeforeRet_;
};
	L = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_52);
	nimln_(1877, "/usr/lib/nim/pure/strutils.nim");
	{
		void* found;
		if (!(((NI) 0) < L)) goto LA8_;
		nimln_(1878, "/usr/lib/nim/pure/strutils.nim");
		if (start < 0 || start >= s.len){ raiseIndexError2(start,s.len-1); goto BeforeRet_;
}
		found = memchr(((void*) ((&s.p->data[start]))), sub, ((size_t) (L)));
		nimln_(1879, "/usr/lib/nim/pure/strutils.nim");
		{
			if (!!((found == 0))) goto LA12_;
			nimln_(1880, "/usr/lib/nim/pure/strutils.nim");
			result = minuspercent___system_716(((NI) (ptrdiff_t) (found)), ((NI) (nimToCStringConv(s))));
			goto BeforeRet_;
		}
		LA12_: ;
	}
	LA8_: ;
	nimln_(1884, "/usr/lib/nim/pure/strutils.nim");
	result = ((NI) -1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a, NI aLen_0, NimStringV2 sep) {
	NimStringV2 result;
	nimfr_("join", "/usr/lib/nim/pure/strutils.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(1778, "/usr/lib/nim/pure/strutils.nim");
	{
		NI L;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_53;
		NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_54;
		if (!(((NI) 0) < aLen_0)) goto LA3_;
		nimln_(1779, "/usr/lib/nim/pure/strutils.nim");
		if (nimSubInt(aLen_0, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_53)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimMulInt(sep.len, (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_53), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_54)) { raiseOverflow(); goto BeforeRet_;
};
		L = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_54);
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			nimln_(1780, "/usr/lib/nim/pure/strutils.nim");
			colontmp_ = (aLen_0-1);
			nimln_(90, "/usr/lib/nim/system/iterators_1.nim");
			res = ((NI) 0);
			{
				nimln_(91, "/usr/lib/nim/system/iterators_1.nim");
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_55;
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_56;
					if (!(res <= colontmp_)) goto LA7;
					nimln_(1780, "/usr/lib/nim/pure/strutils.nim");
					i = res;
					if (i < 0 || i >= aLen_0){ raiseIndexError2(i,aLen_0-1); goto BeforeRet_;
}
					if (nimAddInt(L, a[i].len, &TM__JGc9b9bh2D3nTdUR7TGyq8aA_55)) { raiseOverflow(); goto BeforeRet_;
};
					L = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_55);
					nimln_(93, "/usr/lib/nim/system/iterators_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_56)) { raiseOverflow(); goto BeforeRet_;
};
					res = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_56);
				} LA7: ;
			}
		}
		nimln_(1781, "/usr/lib/nim/pure/strutils.nim");
		if ((L) < ((NI) 0) || (L) > ((NI) 2147483647)){ raiseRangeErrorI(L, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		result = rawNewString(((NI) (L)));
		nimln_(1782, "/usr/lib/nim/pure/strutils.nim");
		if (((NI) 0) < 0 || ((NI) 0) >= aLen_0){ raiseIndexError2(((NI) 0),aLen_0-1); goto BeforeRet_;
}
		prepareAdd((&result), a[((NI) 0)].len + 0);
appendString((&result), a[((NI) 0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimln_(1783, "/usr/lib/nim/pure/strutils.nim");
			colontmp__2 = (aLen_0-1);
			nimln_(90, "/usr/lib/nim/system/iterators_1.nim");
			res_2 = ((NI) 1);
			{
				nimln_(91, "/usr/lib/nim/system/iterators_1.nim");
				while (1) {
					NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_57;
					if (!(res_2 <= colontmp__2)) goto LA10;
					nimln_(1783, "/usr/lib/nim/pure/strutils.nim");
					i_2 = res_2;
					prepareAdd((&result), sep.len + 0);
appendString((&result), sep);
					if (i_2 < 0 || i_2 >= aLen_0){ raiseIndexError2(i_2,aLen_0-1); goto BeforeRet_;
}
					prepareAdd((&result), a[i_2].len + 0);
appendString((&result), a[i_2]);
					nimln_(93, "/usr/lib/nim/system/iterators_1.nim");
					if (nimAddInt(res_2, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_57)) { raiseOverflow(); goto BeforeRet_;
};
					res_2 = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_57);
				} LA10: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(1787, "/usr/lib/nim/pure/strutils.nim");
		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_59;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuRemoveSuffixCharSet)(NimStringV2* s, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars) {
	NI last;
	NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_61;
	nimfr_("removeSuffix", "/usr/lib/nim/pure/strutils.nim");
{	nimln_(1677, "/usr/lib/nim/pure/strutils.nim");
	{
		if (!((*s).len == ((NI) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(1678, "/usr/lib/nim/pure/strutils.nim");
	last = ((*s).len-1);
	{
		nimln_(1679, "/usr/lib/nim/pure/strutils.nim");
		while (1) {
			NIM_BOOL T7_;
			NI TM__JGc9b9bh2D3nTdUR7TGyq8aA_60;
			T7_ = (NIM_BOOL)0;
			T7_ = (((NI) -1) < last);
			if (!(T7_)) goto LA8_;
			if (last < 0 || last >= (*s).len){ raiseIndexError2(last,(*s).len-1); goto BeforeRet_;
}
			T7_ = ((chars[(NU)(((NU8)((*s).p->data[last])))>>3] &(1U<<((NU)(((NU8)((*s).p->data[last])))&7U)))!=0);
			LA8_: ;
			if (!T7_) goto LA6;
			if (nimSubInt(last, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_60)) { raiseOverflow(); goto BeforeRet_;
};
			last = (NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_60);
		} LA6: ;
	}
	nimln_(1680, "/usr/lib/nim/pure/strutils.nim");
	if (nimAddInt(last, ((NI) 1), &TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) < ((NI) 0) || ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	setLengthStrV2((&(*s)), ((NI) ((NI)(TM__JGc9b9bh2D3nTdUR7TGyq8aA_61))));
	}BeforeRet_: ;
	popFrame();
}
