/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sos.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sos.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
#include <string.h>
#include <time.h>
#include <stdlib.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
NI32 errorCode;
};
struct tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringV2 Field0;
NimStringV2 Field1;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__pureZos_97)(NimStringV2* result, NI* state, NimStringV2 tail);
static N_INLINE(NIM_CHAR, X5BX5D___system_7016)(NimStringV2 s, NI i);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_CHAR*, X5BX5D___system_7055)(NimStringV2* s, NI i);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__pureZos_66)(NimStringV2* path, NIM_BOOL trailingSep);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3269)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, addNormalizePath__pureZpathnorm_74)(NimStringV2 x, NimStringV2* result, NI* state, NIM_CHAR dirSep);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsOrCreateDir)(NimStringV2 dir);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir__pureZos_1716)(NimStringV2 dir);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__pureZos_450)(NI32 errorCode, NimStringV2 additionalInfo);
N_LIB_PRIVATE N_NOINLINE(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*, newOSError__pureZos_405)(NI32 errorCode, NimStringV2 additionalInfo);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_413)(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA** dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3164)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, osErrorMsg__pureZos_378)(NI32 errorCode);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__pureZos_453)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7460)(NimStringV2 s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3263)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3266)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(NIM_BOOL, contains__pureZos_810)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
static N_INLINE(NI, find__pureZos_815)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosaddFileExt)(NimStringV2 filename, NimStringV2 ext);
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__pureZos_286)(NimStringV2 path);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normExt__pureZos_283)(NimStringV2 ext);
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__pureZos_463)(NimStringV2 key, NimStringV2 default_0);
static N_INLINE(NIM_BOOL, eqeq___system_7440)(NCSTRING x, NCSTRING y);
static N_INLINE(NimStringV2, slash___pureZos_136)(NimStringV2 head, NimStringV2 tail);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head, NimStringV2 tail);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandTilde__pureZos_732)(NimStringV2 path);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7472)(NimStringV2 s, NI first);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link);
N_NIMCALL(NimStringV2, mnewString)(NI len);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normalizePath__pureZpathnorm_130)(NimStringV2 path, NIM_CHAR dirSep);
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__pureZos_210)(NimStringV2 path);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b);
static N_INLINE(NIM_BOOL, equalMem__system_1717)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_12 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_13 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_12};
extern TNimTypeV2 NTIv2__BeJgrOdDsczOwEWOZbRfKA_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_16 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_17 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_18 = { 17 | NIM_STRLIT_FLAG, "Additional info: " };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_19 = {17, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_18};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_22 = { 16 | NIM_STRLIT_FLAG, "unknown OS error" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_23 = {16, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_22};
extern TNimTypeV2 NTIv2__iLZrPn9anoh9ad1MmO0RczFw_;
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_24 = { 18 | NIM_STRLIT_FLAG, "Failed to create \'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_25 = {18, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_24};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_26 = { 1 | NIM_STRLIT_FLAG, "\'" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_27 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_26};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_37 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_38 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_37};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_39 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_42 = { 4 | NIM_STRLIT_FLAG, "HOME" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_43 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_42};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_44 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_45 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_12};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_50 = { 2 | NIM_STRLIT_FLAG, ".." };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_51 = {2, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_50};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_52 = { 1 | NIM_STRLIT_FLAG, "." };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_53 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_52};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_54 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_55 = {1, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_52};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_59 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16};
N_LIB_PRIVATE NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA ExeExts__pureZos_802 = {{0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_16}}
;
extern NCSTRING* environ;
extern int cmdCount;
extern NCSTRING* cmdLine;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NIM_BOOL nimInErrorMode__system_4240;
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
static N_INLINE(NIM_CHAR, X5BX5D___system_7016)(NimStringV2 s, NI i) {
	NIM_CHAR result;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_3;
	nimfr_("[]", "/usr/lib/nim/system.nim");
{	result = (NIM_CHAR)0;
	nimln_(2646, "/usr/lib/nim/system.nim");
	if (nimSubInt(s.len, i, &TM__yu6cxgKBBXbNsTkT9cyMd4g_3)) { raiseOverflow(); goto BeforeRet_;
};
	if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_3) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_3) >= s.len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_3),s.len-1); goto BeforeRet_;
}
	result = s.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_3)];
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_2330(s);
	}
	LA5_: ;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_7055)(NimStringV2* s, NI i) {
	NIM_CHAR* result;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_4;
	nimfr_("[]", "/usr/lib/nim/system.nim");
{	result = (NIM_CHAR*)0;
	nimPrepareStrMutationV2((&(*s)));
	nimln_(2652, "/usr/lib/nim/system.nim");
	if (nimSubInt((*s).len, i, &TM__yu6cxgKBBXbNsTkT9cyMd4g_4)) { raiseOverflow(); goto BeforeRet_;
};
	if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4) >= (*s).len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4),(*s).len-1); goto BeforeRet_;
}
	result = (&(*s).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_4)]);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s, NIM_CHAR c) {
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_10;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_11;
{	prepareAdd(s, ((NI) 1));
	(*(*s).p).data[(*s).len] = c;
	if (nimAddInt((*s).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_10)) { raiseOverflow(); goto BeforeRet_;
};
	(*(*s).p).data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_10)] = 0;
	if (nimAddInt((*s).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_11)) { raiseOverflow(); goto BeforeRet_;
};
	(*s).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_11);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__pureZos_66)(NimStringV2* path, NIM_BOOL trailingSep) {
	NI i;
	nimfr_("normalizePathEnd", "/usr/lib/nim/pure/os.nim");
{	nimln_(104, "/usr/lib/nim/pure/os.nim");
	{
		if (!((*path).len == ((NI) 0))) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(105, "/usr/lib/nim/pure/os.nim");
	i = (*path).len;
	{
		nimln_(106, "/usr/lib/nim/pure/os.nim");
		while (1) {
			if (!(((NI) 1) <= i)) goto LA6;
			nimln_(107, "/usr/lib/nim/pure/os.nim");
			{
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_5;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_6;
				if (nimSubInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_5)) { raiseOverflow(); goto BeforeRet_;
};
				if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5) >= (*path).len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5),(*path).len-1); goto BeforeRet_;
}
				if (!(((NU8)((*path).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5)])) == ((NU8)(47)) || ((NU8)((*path).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5)])) == ((NU8)(47)))) goto LA9_;
				if (nimSubInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_6)) { raiseOverflow(); goto BeforeRet_;
};
				i = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_6);
			}
			goto LA7_;
			LA9_: ;
			{
				NIM_BOOL T12_;
				NIM_BOOL T13_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_7;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_8;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_9;
				nimln_(108, "/usr/lib/nim/pure/os.nim");
				T12_ = (NIM_BOOL)0;
				T13_ = (NIM_BOOL)0;
				if (nimSubInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_7)) { raiseOverflow(); goto BeforeRet_;
};
				if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_7) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_7) >= (*path).len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_7),(*path).len-1); goto BeforeRet_;
}
				T13_ = ((NU8)((*path).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_7)]) == (NU8)(46));
				if (!(T13_)) goto LA14_;
				T13_ = (((NI) 2) <= i);
				LA14_: ;
				T12_ = T13_;
				if (!(T12_)) goto LA15_;
				if (nimSubInt(i, ((NI) 2), &TM__yu6cxgKBBXbNsTkT9cyMd4g_8)) { raiseOverflow(); goto BeforeRet_;
};
				if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8) >= (*path).len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8),(*path).len-1); goto BeforeRet_;
}
				T12_ = (((NU8)((*path).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8)])) == ((NU8)(47)) || ((NU8)((*path).p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8)])) == ((NU8)(47)));
				LA15_: ;
				if (!T12_) goto LA16_;
				if (nimSubInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_9)) { raiseOverflow(); goto BeforeRet_;
};
				i = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_9);
			}
			goto LA7_;
			LA16_: ;
			{
				nimln_(109, "/usr/lib/nim/pure/os.nim");
				goto LA5;
			}
			LA7_: ;
		} LA6: ;
	} LA5: ;
	nimln_(110, "/usr/lib/nim/pure/os.nim");
	{
		if (!trailingSep) goto LA21_;
		nimln_(112, "/usr/lib/nim/pure/os.nim");
		if ((i) < ((NI) 0) || (i) > ((NI) 2147483647)){ raiseRangeErrorI(i, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		setLengthStrV2((&(*path)), ((NI) (i)));
		nimln_(114, "/usr/lib/nim/pure/os.nim");
		nimAddCharV1((&(*path)), 47);
	}
	goto LA19_;
	LA21_: ;
	{
		nimln_(115, "/usr/lib/nim/pure/os.nim");
		if (!(((NI) 0) < i)) goto LA24_;
		nimln_(117, "/usr/lib/nim/pure/os.nim");
		if ((i) < ((NI) 0) || (i) > ((NI) 2147483647)){ raiseRangeErrorI(i, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		setLengthStrV2((&(*path)), ((NI) (i)));
	}
	goto LA19_;
	LA24_: ;
	{
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*path)), TM__yu6cxgKBBXbNsTkT9cyMd4g_13);
	}
	LA19_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, joinPathImpl__pureZos_97)(NimStringV2* result, NI* state, NimStringV2 tail) {
	NIM_BOOL trailingSep;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_CHAR T4_;
	NIM_BOOL T6_;
	NIM_BOOL T8_;
	NIM_CHAR* T10_;
NIM_BOOL* nimErr_;
	nimfr_("joinPathImpl", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	nimln_(141, "/usr/lib/nim/pure/os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (NIM_BOOL)0;
	nimln_(138, "/usr/lib/nim/pure/os.nim");
	T2_ = (((NI) 0) < tail.len);
	if (!(T2_)) goto LA3_;
	T4_ = (NIM_CHAR)0;
	T4_ = X5BX5D___system_7016(tail, ((NI) 1));
	T2_ = (((NU8)(T4_)) == ((NU8)(47)) || ((NU8)(T4_)) == ((NU8)(47)));
	LA3_: ;
	T1_ = T2_;
	if (T1_) goto LA5_;
	nimln_(141, "/usr/lib/nim/pure/os.nim");
	T6_ = (NIM_BOOL)0;
	T6_ = (tail.len == ((NI) 0));
	if (!(T6_)) goto LA7_;
	T8_ = (NIM_BOOL)0;
	nimln_(138, "/usr/lib/nim/pure/os.nim");
	T8_ = (((NI) 0) < (*result).len);
	if (!(T8_)) goto LA9_;
	T10_ = (NIM_CHAR*)0;
	T10_ = X5BX5D___system_7055(result, ((NI) 1));
	T8_ = (((NU8)((*T10_))) == ((NU8)(47)) || ((NU8)((*T10_))) == ((NU8)(47)));
	LA9_: ;
	T6_ = T8_;
	LA7_: ;
	T1_ = T6_;
	LA5_: ;
	trailingSep = T1_;
	nimln_(142, "/usr/lib/nim/pure/os.nim");
	normalizePathEnd__pureZos_66(result, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(143, "/usr/lib/nim/pure/os.nim");
	addNormalizePath__pureZpathnorm_74(tail, result, state, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(144, "/usr/lib/nim/pure/os.nim");
	normalizePathEnd__pureZos_66(result, trailingSep);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head, NimStringV2 tail) {
	NimStringV2 result;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_2;
	NI state;
NIM_BOOL* nimErr_;
	nimfr_("joinPath", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(172, "/usr/lib/nim/pure/os.nim");
	if (nimAddInt(head.len, tail.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) < ((NI) 0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	result = rawNewString(((NI) ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_2))));
	nimln_(173, "/usr/lib/nim/pure/os.nim");
	state = ((NI) 0);
	nimln_(174, "/usr/lib/nim/pure/os.nim");
	joinPathImpl__pureZos_97((&result), (&state), head);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(175, "/usr/lib/nim/pure/os.nim");
	joinPathImpl__pureZos_97((&result), (&state), tail);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/usr/lib/nim/system/arithmetics.nim");
	nimln_(418, "/usr/lib/nim/system/arithmetics.nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/usr/lib/nim/system/orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(475, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		nimln_(476, "/usr/lib/nim/system/orc.nim");
		nimln_(63, "/usr/lib/nim/system/arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		nimln_(477, "/usr/lib/nim/system/orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;
			nimln_(478, "/usr/lib/nim/system/orc.nim");
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__yu6cxgKBBXbNsTkT9cyMd4g_15;
			nimln_(481, "/usr/lib/nim/system/orc.nim");
			if (nimSubInt((*cell).rc, ((NI) 16), &TM__yu6cxgKBBXbNsTkT9cyMd4g_15)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_15);
		}
		LA6_: ;
		nimln_(483, "/usr/lib/nim/system/orc.nim");
		rememberCycle__system_3164(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_413)(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA** dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, osErrorMsg__pureZos_378)(NI32 errorCode) {
	NimStringV2 result;
	nimfr_("osErrorMsg", "/usr/lib/nim/pure/includes/oserr.nim");
	result.len = 0; result.p = NIM_NIL;
	nimln_(39, "/usr/lib/nim/pure/includes/oserr.nim");
	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_17;
	nimln_(57, "/usr/lib/nim/pure/includes/oserr.nim");
	{
		NCSTRING T5_;
		NimStringV2 T6_;
		if (!!((errorCode == ((NI32) 0)))) goto LA3_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		nimln_(58, "/usr/lib/nim/pure/includes/oserr.nim");
		T5_ = (NCSTRING)0;
		T5_ = strerror(errorCode);
		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = cstrToNimstr(T5_);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&result), T6_);
	}
	LA3_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_20;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_21;
		if (!(((NI) 0) < src.len)) goto LA3_;
		if (nimAddInt(src.len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_20)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_20)) < ((NI) 0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_20)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_20), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_20))));
		if (nimAddInt((*dest).len, src.len, &TM__yu6cxgKBBXbNsTkT9cyMd4g_21)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_21);
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*, newOSError__pureZos_405)(NI32 errorCode, NimStringV2 additionalInfo) {
	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* result;
	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* e;
	NimStringV2 T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("newOSError", "/usr/lib/nim/pure/includes/oserr.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	e = NIM_NIL;
	nimln_(78, "/usr/lib/nim/pure/includes/oserr.nim");
	eqdestroy___pureZos_413(&e);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	e = (tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA*) nimNewObj(sizeof(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA), NIM_ALIGNOF(tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA));
	(*e).Sup.Sup.Sup.m_type = (&NTIv2__BeJgrOdDsczOwEWOZbRfKA_);
	(*e).Sup.Sup.name = "OSError";
	nimln_(79, "/usr/lib/nim/pure/includes/oserr.nim");
	(*e).errorCode = errorCode;
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	nimln_(80, "/usr/lib/nim/pure/includes/oserr.nim");
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = osErrorMsg__pureZos_378(errorCode);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	eqsink___system_3269((&(*e).Sup.Sup.message), T2_);
	nimln_(81, "/usr/lib/nim/pure/includes/oserr.nim");
	{
		if (!(((NI) 0) < additionalInfo.len)) goto LA5_;
		nimln_(82, "/usr/lib/nim/pure/includes/oserr.nim");
		{
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < (*e).Sup.Sup.message.len);
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_7055((&(*e).Sup.Sup.message), ((NI) 1));
			T9_ = !(((NU8)((*T11_)) == (NU8)(10)));
			LA10_: ;
			if (!T9_) goto LA12_;
			nimAddCharV1((&(*e).Sup.Sup.message), 10);
		}
		LA12_: ;
		nimln_(83, "/usr/lib/nim/pure/includes/oserr.nim");
		prepareAdd((&(*e).Sup.Sup.message), 17);
appendString((&(*e).Sup.Sup.message), TM__yu6cxgKBBXbNsTkT9cyMd4g_19);
		nimln_(84, "/usr/lib/nim/pure/includes/oserr.nim");
		prepareAdd((&(*e).Sup.Sup.message), additionalInfo.len + 0);
appendString((&(*e).Sup.Sup.message), additionalInfo);
	}
	LA5_: ;
	nimln_(86, "/usr/lib/nim/pure/includes/oserr.nim");
	{
		if (!((*e).Sup.Sup.message.len == 0)) goto LA16_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&(*e).Sup.Sup.message), TM__yu6cxgKBBXbNsTkT9cyMd4g_23);
	}
	LA16_: ;
	nimln_(88, "/usr/lib/nim/pure/includes/oserr.nim");
	result = e;
	e = 0;
	nimln_(78, "/usr/lib/nim/pure/includes/oserr.nim");
	eqdestroy___pureZos_413(&e);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___pureZos_413(&e);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__pureZos_450)(NI32 errorCode, NimStringV2 additionalInfo) {
	tyObject_OSError__BeJgrOdDsczOwEWOZbRfKA* T1_;
NIM_BOOL* nimErr_;
	nimfr_("raiseOSError", "/usr/lib/nim/pure/includes/oserr.nim");
{nimErr_ = nimErrorFlag();
	nimln_(95, "/usr/lib/nim/pure/includes/oserr.nim");
	T1_ = NIM_NIL;
	T1_ = newOSError__pureZos_405(errorCode, additionalInfo);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	raiseExceptionEx((Exception*)T1_, "OSError", "raiseOSError", "/usr/lib/nim/pure/includes/oserr.nim", 95);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__pureZos_453)(void) {
	NI32 result;
	result = (NI32)0;
	result = errno;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, rawCreateDir__pureZos_1716)(NimStringV2 dir) {
	NIM_BOOL result;
	int res;
NIM_BOOL* nimErr_;
	nimfr_("rawCreateDir", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(2488, "/usr/lib/nim/pure/os.nim");
	res = mkdir(nimToCStringConv(dir), ((mode_t) 511));
	nimln_(2489, "/usr/lib/nim/pure/os.nim");
	{
		if (!(res == ((NI32) 0))) goto LA3_;
		nimln_(2490, "/usr/lib/nim/pure/os.nim");
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(2491, "/usr/lib/nim/pure/os.nim");
		if (!(errno == EEXIST)) goto LA6_;
		nimln_(2492, "/usr/lib/nim/pure/os.nim");
		result = NIM_FALSE;
	}
	goto LA1_;
	LA6_: ;
	{
		NI32 T9_;
		nimln_(2495, "/usr/lib/nim/pure/os.nim");
		T9_ = (NI32)0;
		T9_ = osLastError__pureZos_453();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__pureZos_450(T9_, dir);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosdirExists)(NimStringV2 dir) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("dirExists", "/usr/lib/nim/pure/os.nim");
	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&res), sizeof(struct stat));
	nimln_(1194, "/usr/lib/nim/pure/os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(dir), (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISDIR(res.st_mode);
	LA3_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsOrCreateDir)(NimStringV2 dir) {
	NIM_BOOL result;
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("existsOrCreateDir", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(2522, "/usr/lib/nim/pure/os.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = rawCreateDir__pureZos_1716(dir);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = !(T1_);
	nimln_(2523, "/usr/lib/nim/pure/os.nim");
	{
		if (!result) goto LA4_;
		nimln_(2525, "/usr/lib/nim/pure/os.nim");
		{
			NIM_BOOL T8_;
			tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw* T11_;
			NimStringV2 T12_;
			T8_ = (NIM_BOOL)0;
			T8_ = nosdirExists(dir);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T8_)) goto LA9_;
			T11_ = NIM_NIL;
			T11_ = (tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw*) nimNewObj(sizeof(tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw), NIM_ALIGNOF(tyObject_IOError__iLZrPn9anoh9ad1MmO0RczFw));
			(*T11_).Sup.Sup.Sup.m_type = (&NTIv2__iLZrPn9anoh9ad1MmO0RczFw_);
			(*T11_).Sup.Sup.name = "IOError";
			nimln_(2526, "/usr/lib/nim/pure/os.nim");
			T12_.len = 0; T12_.p = NIM_NIL;
			T12_ = rawNewString(dir.len + 19);
appendString((&T12_), TM__yu6cxgKBBXbNsTkT9cyMd4g_25);
appendString((&T12_), dir);
appendString((&T12_), TM__yu6cxgKBBXbNsTkT9cyMd4g_27);
			(*T11_).Sup.Sup.message = T12_;
			(*T11_).Sup.Sup.parent = ((Exception*) NIM_NIL);
			raiseExceptionEx((Exception*)T11_, "IOError", "existsOrCreateDir", "/usr/lib/nim/pure/os.nim", 2526);
			goto BeforeRet_;
		}
		LA9_: ;
	}
	LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, noscreateDir)(NimStringV2 dir) {
	NIM_BOOL omitNext;
NIM_BOOL* nimErr_;
	nimfr_("createDir", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	nimln_(2544, "/usr/lib/nim/pure/os.nim");
	omitNext = NIM_FALSE;
	{
		NI i;
		NI colontmp_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_14;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(2547, "/usr/lib/nim/pure/os.nim");
		if (nimSubInt(dir.len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_14)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_14);
		nimln_(90, "/usr/lib/nim/system/iterators_1.nim");
		res = ((NI) 1);
		{
			nimln_(91, "/usr/lib/nim/system/iterators_1.nim");
			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_29;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2547, "/usr/lib/nim/pure/os.nim");
				i = res;
				{
					nimln_(2548, "/usr/lib/nim/pure/os.nim");
					if (i < 0 || i >= dir.len){ raiseIndexError2(i,dir.len-1); goto BeforeRet_;
}
					if (!(((NU8)(dir.p->data[i])) == ((NU8)(47)) || ((NU8)(dir.p->data[i])) == ((NU8)(47)))) goto LA6_;
					nimln_(2549, "/usr/lib/nim/pure/os.nim");
					{
						if (!omitNext) goto LA10_;
						nimln_(2550, "/usr/lib/nim/pure/os.nim");
						omitNext = NIM_FALSE;
					}
					goto LA8_;
					LA10_: ;
					{
						NimStringV2 colontmpD_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_28;
						NIM_BOOL T14_;
						colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
						nimln_(2552, "/usr/lib/nim/pure/os.nim");
						if (nimSubInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_28)) { raiseOverflow(); goto LA13_;
};
						colontmpD_ = substr__system_7460(dir, ((NI) 0), (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_28));
						T14_ = (NIM_BOOL)0;
						T14_ = nosexistsOrCreateDir(colontmpD_);
						if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
						(void)(T14_);
						{
							LA13_:;
						}
						{
							nimln_(54, "/usr/lib/nim/system/fatal.nim");
							eqdestroy___system_3263((&colontmpD_));
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
					LA8_: ;
				}
				LA6_: ;
				nimln_(93, "/usr/lib/nim/system/iterators_1.nim");
				if (nimAddInt(res, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_29)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_29);
			} LA3: ;
		}
	}
	nimln_(2555, "/usr/lib/nim/pure/os.nim");
	{
		NIM_BOOL T19_;
		NIM_BOOL T20_;
		NIM_CHAR T23_;
		NIM_BOOL T26_;
		T19_ = (NIM_BOOL)0;
		T20_ = (NIM_BOOL)0;
		T20_ = (((NI) 0) < dir.len);
		if (!(T20_)) goto LA21_;
		T20_ = !(omitNext);
		LA21_: ;
		T19_ = T20_;
		if (!(T19_)) goto LA22_;
		nimln_(2556, "/usr/lib/nim/pure/os.nim");
		T23_ = (NIM_CHAR)0;
		T23_ = X5BX5D___system_7016(dir, ((NI) 1));
		T19_ = !((((NU8)(T23_)) == ((NU8)(47)) || ((NU8)(T23_)) == ((NU8)(47))));
		LA22_: ;
		if (!T19_) goto LA24_;
		nimln_(2557, "/usr/lib/nim/pure/os.nim");
		T26_ = (NIM_BOOL)0;
		T26_ = nosexistsOrCreateDir(dir);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T26_);
	}
	LA24_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZos_338)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest, tyTuple__UV3llMMYFckfui8YMBuUZA src) {
	if ((*dest).Field0.p != src.Field0.p) {	eqdestroy___system_3263((&(*dest).Field0));
	}
(*dest).Field0.len = src.Field0.len; (*dest).Field0.p = src.Field0.p;
	if ((*dest).Field1.p != src.Field1.p) {	eqdestroy___system_3263((&(*dest).Field1));
	}
(*dest).Field1.len = src.Field1.len; (*dest).Field1.p = src.Field1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZos_335)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest, tyTuple__UV3llMMYFckfui8YMBuUZA src) {
	eqcopy___system_3266((&(*dest).Field0), src.Field0);
	eqcopy___system_3266((&(*dest).Field1), src.Field1);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_332)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest) {
	eqdestroy___system_3263((&(*dest).Field0));
	eqdestroy___system_3263((&(*dest).Field1));
}
static N_INLINE(NI, find__pureZos_815)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NI result;
	nimfr_("find", "/usr/lib/nim/system.nim");
{	result = (NI)0;
	nimln_(1837, "/usr/lib/nim/system.nim");
	result = ((NI) 0);
	{
		NIM_CHAR i;
		NI i_2;
		i = (NIM_CHAR)0;
		nimln_(18, "/usr/lib/nim/system/iterators.nim");
		i_2 = ((NI) 0);
		{
			nimln_(19, "/usr/lib/nim/system/iterators.nim");
			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_30;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_31;
				if (!(i_2 < aLen_0)) goto LA3;
				nimln_(1838, "/usr/lib/nim/system.nim");
				if (i_2 < 0 || i_2 >= aLen_0){ raiseIndexError2(i_2,aLen_0-1); goto BeforeRet_;
}
				i = a[i_2];
				{
					nimln_(1839, "/usr/lib/nim/system.nim");
					if (!((NU8)(i) == (NU8)(item))) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				nimln_(1838, "/usr/lib/nim/system.nim");
				if (nimAddInt(result, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_30)) { raiseOverflow(); goto BeforeRet_;
};
				result = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_30);
				nimln_(21, "/usr/lib/nim/system/iterators.nim");
				if (nimAddInt(i_2, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_31)) { raiseOverflow(); goto BeforeRet_;
};
				i_2 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_31);
			} LA3: ;
		}
	}
	nimln_(1841, "/usr/lib/nim/system.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__pureZos_810)(NIM_CHAR* a, NI aLen_0, NIM_CHAR item) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/usr/lib/nim/system.nim");
{	result = (NIM_BOOL)0;
	nimln_(1855, "/usr/lib/nim/system.nim");
	T1_ = (NI)0;
	T1_ = find__pureZos_815(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, searchExtPos__pureZos_286)(NimStringV2 path) {
	NI result;
	nimfr_("searchExtPos", "/usr/lib/nim/pure/os.nim");
{	result = (NI)0;
	nimln_(638, "/usr/lib/nim/pure/os.nim");
	result = ((NI) -1);
	{
		NI i;
		NI colontmp_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_32;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(639, "/usr/lib/nim/pure/os.nim");
		if (nimSubInt(path.len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_32)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_32);
		nimln_(33, "/usr/lib/nim/system/iterators_1.nim");
		res = colontmp_;
		{
			nimln_(34, "/usr/lib/nim/system/iterators_1.nim");
			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_33;
				if (!(((NI) 1) <= res)) goto LA3;
				nimln_(639, "/usr/lib/nim/pure/os.nim");
				i = res;
				{
					nimln_(640, "/usr/lib/nim/pure/os.nim");
					if (i < 0 || i >= path.len){ raiseIndexError2(i,path.len-1); goto BeforeRet_;
}
					if (!((NU8)(path.p->data[i]) == (NU8)(46))) goto LA6_;
					nimln_(641, "/usr/lib/nim/pure/os.nim");
					result = i;
					nimln_(642, "/usr/lib/nim/pure/os.nim");
					goto LA1;
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(643, "/usr/lib/nim/pure/os.nim");
					if (i < 0 || i >= path.len){ raiseIndexError2(i,path.len-1); goto BeforeRet_;
}
					if (!(((NU8)(path.p->data[i])) == ((NU8)(47)) || ((NU8)(path.p->data[i])) == ((NU8)(47)))) goto LA9_;
					nimln_(644, "/usr/lib/nim/pure/os.nim");
					goto LA1;
				}
				goto LA4_;
				LA9_: ;
				LA4_: ;
				nimln_(36, "/usr/lib/nim/system/iterators_1.nim");
				if (nimSubInt(res, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_33)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_33);
			} LA3: ;
		}
	} LA1: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, appendChar)(NimStringV2* dest, NIM_CHAR c) {
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_34;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_35;
{	(*(*dest).p).data[(*dest).len] = c;
	if (nimAddInt((*dest).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_34)) { raiseOverflow(); goto BeforeRet_;
};
	(*(*dest).p).data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_34)] = 0;
	if (nimAddInt((*dest).len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_35)) { raiseOverflow(); goto BeforeRet_;
};
	(*dest).len = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_35);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, normExt__pureZos_283)(NimStringV2 ext) {
	NimStringV2 result;
	nimfr_("normExt", "/usr/lib/nim/pure/os.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(618, "/usr/lib/nim/pure/os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (ext.len == 0);
		if (T3_) goto LA4_;
		if (((NI) 0) < 0 || ((NI) 0) >= ext.len){ raiseIndexError2(((NI) 0),ext.len-1); goto BeforeRet_;
}
		T3_ = ((NU8)(ext.p->data[((NI) 0)]) == (NU8)(46));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&result), ext);
	}
	goto LA1_;
	LA5_: ;
	{
		NimStringV2 T8_;
		nimln_(619, "/usr/lib/nim/pure/os.nim");
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(ext.len + 1);
appendChar((&T8_), 46);
appendString((&T8_), ext);
		result = T8_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosaddFileExt)(NimStringV2 filename, NimStringV2 ext) {
	NimStringV2 result;
	NI extPos;
NIM_BOOL* nimErr_;
	nimfr_("addFileExt", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(786, "/usr/lib/nim/pure/os.nim");
	extPos = searchExtPos__pureZos_286(filename);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(787, "/usr/lib/nim/pure/os.nim");
	{
		NimStringV2 colontmpD_;
		NimStringV2 T5_;
		if (!(extPos < ((NI) 0))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T5_.len = 0; T5_.p = NIM_NIL;
		colontmpD_ = normExt__pureZos_283(ext);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T5_ = rawNewString(filename.len + colontmpD_.len + 0);
appendString((&T5_), filename);
appendString((&T5_), colontmpD_);
		result = T5_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&colontmpD_));
	}
	goto LA1_;
	LA3_: ;
	{
		eqcopy___system_3266((&result), filename);
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("fileExists", "/usr/lib/nim/pure/os.nim");
{	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&res), sizeof(struct stat));
	nimln_(1175, "/usr/lib/nim/pure/os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(nimToCStringConv(filename), (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISREG(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_7440)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "/usr/lib/nim/system.nim");
	result = (NIM_BOOL)0;
	nimln_(2994, "/usr/lib/nim/system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2995, "/usr/lib/nim/system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(2996, "/usr/lib/nim/system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__pureZos_463)(NimStringV2 key, NimStringV2 default_0) {
	NimStringV2 result;
	NCSTRING env;
	nimfr_("getEnv", "/usr/lib/nim/pure/includes/osenv.nim");
{	result.len = 0; result.p = NIM_NIL;
	nimln_(70, "/usr/lib/nim/pure/includes/osenv.nim");
	env = getenv(nimToCStringConv(key));
	nimln_(71, "/usr/lib/nim/pure/includes/osenv.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = eqeq___system_7440(env, ((NCSTRING) NIM_NIL));
		if (!T3_) goto LA4_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&result), default_0);
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(72, "/usr/lib/nim/pure/includes/osenv.nim");
	result = cstrToNimstr(env);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NimStringV2, slash___pureZos_136)(NimStringV2 head, NimStringV2 tail) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(234, "/usr/lib/nim/pure/os.nim");
	result = nosjoinPath(head, tail);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T2_;
NIM_BOOL* nimErr_;
	nimfr_("getHomeDir", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimln_(893, "/usr/lib/nim/pure/os.nim");
	T2_.len = 0; T2_.p = NIM_NIL;
	colontmpD_ = getEnv__pureZos_463(TM__yu6cxgKBBXbNsTkT9cyMd4g_43, TM__yu6cxgKBBXbNsTkT9cyMd4g_44);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = rawNewString(colontmpD_.len + 1);
appendString((&T2_), colontmpD_);
appendString((&T2_), TM__yu6cxgKBBXbNsTkT9cyMd4g_45);
	result = T2_;
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	eqdestroy___system_3263((&colontmpD_));
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___system_3263((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandTilde__pureZos_732)(NimStringV2 path) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("expandTilde", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(1037, "/usr/lib/nim/pure/os.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (path.len == ((NI) 0));
		if (T3_) goto LA4_;
		if (((NI) 0) < 0 || ((NI) 0) >= path.len){ raiseIndexError2(((NI) 0),path.len-1); goto BeforeRet_;
}
		T3_ = !(((NU8)(path.p->data[((NI) 0)]) == (NU8)(126)));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&result), path);
	}
	goto LA1_;
	LA5_: ;
	{
		nimln_(1039, "/usr/lib/nim/pure/os.nim");
		if (!(path.len == ((NI) 1))) goto LA8_;
		nimln_(1040, "/usr/lib/nim/pure/os.nim");
		result = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		nimln_(1041, "/usr/lib/nim/pure/os.nim");
		if (((NI) 1) < 0 || ((NI) 1) >= path.len){ raiseIndexError2(((NI) 1),path.len-1); goto BeforeRet_;
}
		if (!(((NU8)(path.p->data[((NI) 1)])) == ((NU8)(47)) || ((NU8)(path.p->data[((NI) 1)])) == ((NU8)(47)))) goto LA11_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(1042, "/usr/lib/nim/pure/os.nim");
		colontmpD_ = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2 = substr__system_7472(path, ((NI) 2));
		result = slash___pureZos_136(colontmpD_, colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&colontmpD__2));
		eqdestroy___system_3263((&colontmpD_));
	}
	goto LA1_;
	LA11_: ;
	{
		eqcopy___system_3266((&result), path);
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
	nimfr_("symlinkExists", "/usr/lib/nim/pure/os.nim");
	result = (NIM_BOOL)0;
	nimZeroMem((void*)(&res), sizeof(struct stat));
	nimln_(1216, "/usr/lib/nim/pure/os.nim");
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = lstat(nimToCStringConv(link), (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISLNK(res.st_mode);
	LA3_: ;
	result = T1_;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path) {
	NIM_BOOL result;
	nimfr_("isAbsolute", "/usr/lib/nim/pure/os.nim");
{	result = (NIM_BOOL)0;
	nimln_(287, "/usr/lib/nim/pure/os.nim");
	{
		if (!(path.len == ((NI) 0))) goto LA3_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(301, "/usr/lib/nim/pure/os.nim");
	if (((NI) 0) < 0 || ((NI) 0) >= path.len){ raiseIndexError2(((NI) 0),path.len-1); goto BeforeRet_;
}
	result = ((NU8)(path.p->data[((NI) 0)]) == (NU8)(47));
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, parentDirPos__pureZos_210)(NimStringV2 path) {
	NI result;
	NI q;
	nimfr_("parentDirPos", "/usr/lib/nim/pure/os.nim");
{	result = (NI)0;
	nimln_(467, "/usr/lib/nim/pure/os.nim");
	q = ((NI) 1);
	nimln_(468, "/usr/lib/nim/pure/os.nim");
	{
		NIM_BOOL T3_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_47;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 1) <= path.len);
		if (!(T3_)) goto LA4_;
		if (nimSubInt(path.len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_47)) { raiseOverflow(); goto BeforeRet_;
};
		if ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_47) < 0 || (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_47) >= path.len){ raiseIndexError2((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_47),path.len-1); goto BeforeRet_;
}
		T3_ = (((NU8)(path.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_47)])) == ((NU8)(47)) || ((NU8)(path.p->data[(NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_47)])) == ((NU8)(47)));
		LA4_: ;
		if (!T3_) goto LA5_;
		q = ((NI) 2);
	}
	LA5_: ;
	{
		NI i;
		NI colontmp_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_48;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(469, "/usr/lib/nim/pure/os.nim");
		if (nimSubInt(path.len, q, &TM__yu6cxgKBBXbNsTkT9cyMd4g_48)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_48);
		nimln_(33, "/usr/lib/nim/system/iterators_1.nim");
		res = colontmp_;
		{
			nimln_(34, "/usr/lib/nim/system/iterators_1.nim");
			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_49;
				if (!(((NI) 0) <= res)) goto LA9;
				nimln_(469, "/usr/lib/nim/pure/os.nim");
				i = res;
				{
					nimln_(470, "/usr/lib/nim/pure/os.nim");
					if (i < 0 || i >= path.len){ raiseIndexError2(i,path.len-1); goto BeforeRet_;
}
					if (!(((NU8)(path.p->data[i])) == ((NU8)(47)) || ((NU8)(path.p->data[i])) == ((NU8)(47)))) goto LA12_;
					result = i;
					goto BeforeRet_;
				}
				LA12_: ;
				nimln_(36, "/usr/lib/nim/system/iterators_1.nim");
				if (nimSubInt(res, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_49)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_49);
			} LA9: ;
		}
	}
	nimln_(471, "/usr/lib/nim/pure/os.nim");
	result = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1717)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a, NimStringV2 b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
	nimfr_("eqStrings", "/usr/lib/nim/system/strmantle.nim");
{	result = (NIM_BOOL)0;
	nimln_(27, "/usr/lib/nim/system/strmantle.nim");
	alen = a.len;
	nimln_(28, "/usr/lib/nim/system/strmantle.nim");
	blen = b.len;
	nimln_(29, "/usr/lib/nim/system/strmantle.nim");
	{
		if (!(alen == blen)) goto LA3_;
		nimln_(30, "/usr/lib/nim/system/strmantle.nim");
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		nimln_(31, "/usr/lib/nim/system/strmantle.nim");
		result = equalMem__system_1717(((void*) ((&a.p->data[((NI) 0)]))), ((void*) ((&b.p->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path) {
	NimStringV2 result;
	NI sepPos;
NIM_BOOL* nimErr_;
	nimfr_("parentDir", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimln_(497, "/usr/lib/nim/pure/os.nim");
	result = normalizePath__pureZpathnorm_130(path, 47);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(498, "/usr/lib/nim/pure/os.nim");
	sepPos = parentDirPos__pureZos_210(result);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(499, "/usr/lib/nim/pure/os.nim");
	{
		NimStringV2 T5_;
		if (!(((NI) 0) <= sepPos)) goto LA3_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		nimln_(500, "/usr/lib/nim/pure/os.nim");
		T5_.len = 0; T5_.p = NIM_NIL;
		T5_ = substr__system_7460(result, ((NI) 0), sepPos);
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&result), T5_);
		nimln_(501, "/usr/lib/nim/pure/os.nim");
		normalizePathEnd__pureZos_66((&result), NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T7_;
		NIM_BOOL T8_;
		NIM_BOOL T9_;
		NIM_CHAR* T13_;
		nimln_(502, "/usr/lib/nim/pure/os.nim");
		T7_ = (NIM_BOOL)0;
		T8_ = (NIM_BOOL)0;
		T9_ = (NIM_BOOL)0;
		T9_ = eqStrings(result, TM__yu6cxgKBBXbNsTkT9cyMd4g_51);
		if (T9_) goto LA10_;
		T9_ = eqStrings(result, TM__yu6cxgKBBXbNsTkT9cyMd4g_53);
		LA10_: ;
		T8_ = T9_;
		if (T8_) goto LA11_;
		T8_ = (result.len == ((NI) 0));
		LA11_: ;
		T7_ = T8_;
		if (T7_) goto LA12_;
		T13_ = (NIM_CHAR*)0;
		T13_ = X5BX5D___system_7055((&result), ((NI) 1));
		T7_ = (((NU8)((*T13_))) == ((NU8)(47)) || ((NU8)((*T13_))) == ((NU8)(47)));
		LA12_: ;
		if (!T7_) goto LA14_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqsink___system_3269((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_54);
	}
	goto LA1_;
	LA14_: ;
	{
		eqsink___system_3269((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_55);
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, findExe__pureZos_803)(NimStringV2 exe, NIM_BOOL followSymlinks, NimStringV2* extensions, NI extensionsLen_0) {
	NimStringV2 result;
	NimStringV2 path;
NIM_BOOL* nimErr_;
	nimfr_("findExe", "/usr/lib/nim/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	path.len = 0; path.p = NIM_NIL;
	nimln_(1240, "/usr/lib/nim/pure/os.nim");
	{
		if (!(exe.len == ((NI) 0))) goto LA4_;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&path));
		goto BeforeRet_;
	}
	LA4_: ;
	nimln_(1246, "/usr/lib/nim/pure/os.nim");
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = contains__pureZos_810(((exe).p) ? (exe.p->data) : NIM_NIL, exe.len, 47);
		if (!T8_) goto LA9_;
		{
			NimStringV2* extX60gensym82_;
			NI i;
			extX60gensym82_ = (NimStringV2*)0;
			nimln_(8, "/usr/lib/nim/system/iterators.nim");
			i = ((NI) 0);
			{
				nimln_(9, "/usr/lib/nim/system/iterators.nim");
				while (1) {
					NimStringV2 T14_;
					NI TM__yu6cxgKBBXbNsTkT9cyMd4g_36;
					if (!(i < extensionsLen_0)) goto LA13;
					nimln_(1246, "/usr/lib/nim/pure/os.nim");
					if (i < 0 || i >= extensionsLen_0){ raiseIndexError2(i,extensionsLen_0-1); goto LA1_;
}
					extX60gensym82_ = (&extensions[i]);
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					nimln_(1243, "/usr/lib/nim/pure/os.nim");
					T14_.len = 0; T14_.p = NIM_NIL;
					T14_ = nosaddFileExt(exe, (*extX60gensym82_));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqsink___system_3269((&result), T14_);
					nimln_(1246, "/usr/lib/nim/pure/os.nim");
					{
						NIM_BOOL T17_;
						nimln_(1244, "/usr/lib/nim/pure/os.nim");
						T17_ = (NIM_BOOL)0;
						T17_ = nosfileExists(result);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						if (!T17_) goto LA18_;
						nimln_(54, "/usr/lib/nim/system/fatal.nim");
						eqdestroy___system_3263((&path));
						goto BeforeRet_;
					}
					LA18_: ;
					nimln_(11, "/usr/lib/nim/system/iterators.nim");
					if (nimAddInt(i, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_36)) { raiseOverflow(); goto LA1_;
};
					i = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_36);
				} LA13: ;
			}
		}
	}
	LA9_: ;
	nimln_(1249, "/usr/lib/nim/pure/os.nim");
	path = getEnv__pureZos_463(TM__yu6cxgKBBXbNsTkT9cyMd4g_38, TM__yu6cxgKBBXbNsTkT9cyMd4g_39);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 candidate;
		NI lastX60gensym34_;
		NI splitsX60gensym34_;
		candidate.len = 0; candidate.p = NIM_NIL;
		nimln_(365, "/usr/lib/nim/pure/strutils.nim");
		lastX60gensym34_ = ((NI) 0);
		nimln_(366, "/usr/lib/nim/pure/strutils.nim");
		splitsX60gensym34_ = ((NI) -1);
		{
			nimln_(426, "/usr/lib/nim/pure/strutils.nim");
			while (1) {
				NI firstX60gensym34_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_41;
				NimStringV2 T32_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_57;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_58;
				nimln_(368, "/usr/lib/nim/pure/strutils.nim");
				if (!(lastX60gensym34_ <= path.len)) goto LA23;
				nimln_(369, "/usr/lib/nim/pure/strutils.nim");
				firstX60gensym34_ = lastX60gensym34_;
				{
					nimln_(370, "/usr/lib/nim/pure/strutils.nim");
					while (1) {
						NIM_BOOL T26_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_40;
						T26_ = (NIM_BOOL)0;
						T26_ = (lastX60gensym34_ < path.len);
						if (!(T26_)) goto LA27_;
						if (lastX60gensym34_ < 0 || lastX60gensym34_ >= path.len){ raiseIndexError2(lastX60gensym34_,path.len-1); goto LA21_;
}
						T26_ = !(((NU8)(path.p->data[lastX60gensym34_]) == (NU8)(58)));
						LA27_: ;
						if (!T26_) goto LA25;
						nimln_(371, "/usr/lib/nim/pure/strutils.nim");
						if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_40)) { raiseOverflow(); goto LA21_;
};
						lastX60gensym34_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_40);
					} LA25: ;
				}
				nimln_(372, "/usr/lib/nim/pure/strutils.nim");
				{
					if (!(splitsX60gensym34_ == ((NI) 0))) goto LA30_;
					lastX60gensym34_ = path.len;
				}
				LA30_: ;
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				nimln_(1250, "/usr/lib/nim/pure/os.nim");
				nimln_(373, "/usr/lib/nim/pure/strutils.nim");
				if (nimSubInt(lastX60gensym34_, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_41)) { raiseOverflow(); goto LA21_;
};
				nimln_(1250, "/usr/lib/nim/pure/os.nim");
				T32_.len = 0; T32_.p = NIM_NIL;
				T32_ = substr__system_7460(path, firstX60gensym34_, (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_41));
				nimln_(54, "/usr/lib/nim/system/fatal.nim");
				eqsink___system_3269((&candidate), T32_);
				{
					NimStringV2 x;
					NimStringV2 colontmpD_;
					x.len = 0; x.p = NIM_NIL;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimln_(1251, "/usr/lib/nim/pure/os.nim");
					{
						if (!(candidate.len == ((NI) 0))) goto LA37_;
						nimln_(54, "/usr/lib/nim/system/fatal.nim");
						eqdestroy___system_3263((&colontmpD_));
						eqdestroy___system_3263((&x));
						nimln_(1251, "/usr/lib/nim/pure/os.nim");
						goto LA33;
					}
					LA37_: ;
					nimln_(1257, "/usr/lib/nim/pure/os.nim");
					colontmpD_ = expandTilde__pureZos_732(candidate);
					if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
					x = slash___pureZos_136(colontmpD_, exe);
					if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
					{
						NimStringV2* ext;
						NI i_2;
						ext = (NimStringV2*)0;
						nimln_(8, "/usr/lib/nim/system/iterators.nim");
						i_2 = ((NI) 0);
						{
							nimln_(9, "/usr/lib/nim/system/iterators.nim");
							while (1) {
								NimStringV2 x_2;
								NI TM__yu6cxgKBBXbNsTkT9cyMd4g_56;
								if (!(i_2 < extensionsLen_0)) goto LA41;
								x_2.len = 0; x_2.p = NIM_NIL;
								nimln_(1258, "/usr/lib/nim/pure/os.nim");
								if (i_2 < 0 || i_2 >= extensionsLen_0){ raiseIndexError2(i_2,extensionsLen_0-1); goto LA42_;
}
								ext = (&extensions[i_2]);
								nimln_(1259, "/usr/lib/nim/pure/os.nim");
								x_2 = nosaddFileExt(x, (*ext));
								if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
								nimln_(1258, "/usr/lib/nim/pure/os.nim");
								{
									NIM_BOOL T45_;
									nimln_(1260, "/usr/lib/nim/pure/os.nim");
									T45_ = (NIM_BOOL)0;
									T45_ = nosfileExists(x_2);
									if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
									if (!T45_) goto LA46_;
									{
										nimln_(1262, "/usr/lib/nim/pure/os.nim");
										while (1) {
											if (!followSymlinks) goto LA49;
											nimln_(1263, "/usr/lib/nim/pure/os.nim");
											{
												NIM_BOOL T52_;
												NimStringV2 r;
												NI len;
												T52_ = (NIM_BOOL)0;
												T52_ = nossymlinkExists(x_2);
												if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
												if (!T52_) goto LA53_;
												r.len = 0; r.p = NIM_NIL;
												nimln_(1264, "/usr/lib/nim/pure/os.nim");
												r = mnewString(((NI) 1024));
												nimln_(1265, "/usr/lib/nim/pure/os.nim");
												len = readlink(nimToCStringConv(x_2), nimToCStringConv(r), ((NI) 1024));
												nimln_(1266, "/usr/lib/nim/pure/os.nim");
												{
													NI32 T60_;
													if (!(len < ((NI) 0))) goto LA58_;
													nimln_(1267, "/usr/lib/nim/pure/os.nim");
													T60_ = (NI32)0;
													T60_ = osLastError__pureZos_453();
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													raiseOSError__pureZos_450(T60_, exe);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
												}
												LA58_: ;
												nimln_(1268, "/usr/lib/nim/pure/os.nim");
												{
													NI TM__yu6cxgKBBXbNsTkT9cyMd4g_46;
													NimStringV2 T65_;
													if (!(((NI) 1024) < len)) goto LA63_;
													nimln_(54, "/usr/lib/nim/system/fatal.nim");
													nimln_(1269, "/usr/lib/nim/pure/os.nim");
													if (nimAddInt(len, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_46)) { raiseOverflow(); goto LA55_;
};
													if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_46)) < ((NI) 0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_46)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_46), ((NI) 0), ((NI) 2147483647)); goto LA55_;
}
													T65_.len = 0; T65_.p = NIM_NIL;
													T65_ = mnewString(((NI) ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_46))));
													nimln_(54, "/usr/lib/nim/system/fatal.nim");
													eqsink___system_3269((&r), T65_);
													nimln_(1270, "/usr/lib/nim/pure/os.nim");
													len = readlink(nimToCStringConv(x_2), nimToCStringConv(r), len);
												}
												LA63_: ;
												nimln_(1271, "/usr/lib/nim/pure/os.nim");
												if ((len) < ((NI) 0) || (len) > ((NI) 2147483647)){ raiseRangeErrorI(len, ((NI) 0), ((NI) 2147483647)); goto LA55_;
}
												setLengthStrV2((&r), ((NI) (len)));
												nimln_(1272, "/usr/lib/nim/pure/os.nim");
												{
													NIM_BOOL T68_;
													T68_ = (NIM_BOOL)0;
													T68_ = nosisAbsolute(r);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													if (!T68_) goto LA69_;
													nimln_(54, "/usr/lib/nim/system/fatal.nim");
													eqsink___system_3269((&x_2), r);
													nimln_(1273, "/usr/lib/nim/pure/os.nim");
													r.len = 0; r.p = NIM_NIL;
												}
												goto LA66_;
												LA69_: ;
												{
													NimStringV2 colontmpD__2;
													NimStringV2 T72_;
													colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
													nimln_(54, "/usr/lib/nim/system/fatal.nim");
													nimln_(1275, "/usr/lib/nim/pure/os.nim");
													colontmpD__2 = nosparentDir(x_2);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													T72_.len = 0; T72_.p = NIM_NIL;
													T72_ = slash___pureZos_136(colontmpD__2, r);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													nimln_(54, "/usr/lib/nim/system/fatal.nim");
													eqsink___system_3269((&x_2), T72_);
													eqdestroy___system_3263((&colontmpD__2));
												}
												LA66_: ;
												{
													LA55_:;
												}
												{
													eqdestroy___system_3263((&r));
												}
												if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
											}
											goto LA50_;
											LA53_: ;
											{
												nimln_(1277, "/usr/lib/nim/pure/os.nim");
												goto LA48;
											}
											LA50_: ;
										} LA49: ;
									} LA48: ;
									nimln_(1278, "/usr/lib/nim/pure/os.nim");
									nimln_(54, "/usr/lib/nim/system/fatal.nim");
									eqsink___system_3269((&result), x_2);
									nimln_(1278, "/usr/lib/nim/pure/os.nim");
									x_2.len = 0; x_2.p = NIM_NIL;
									nimln_(54, "/usr/lib/nim/system/fatal.nim");
									eqdestroy___system_3263((&x_2));
									eqdestroy___system_3263((&colontmpD_));
									eqdestroy___system_3263((&x));
									eqdestroy___system_3263((&candidate));
									eqdestroy___system_3263((&path));
									goto BeforeRet_;
								}
								LA46_: ;
								nimln_(11, "/usr/lib/nim/system/iterators.nim");
								if (nimAddInt(i_2, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_56)) { raiseOverflow(); goto LA42_;
};
								i_2 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_56);
								{
									LA42_:;
								}
								{
									nimln_(54, "/usr/lib/nim/system/fatal.nim");
									eqdestroy___system_3263((&x_2));
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
							} LA41: ;
						}
					}
					{
						LA34_:;
					}
					{
						eqdestroy___system_3263((&colontmpD_));
						eqdestroy___system_3263((&x));
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
				} LA33: ;
				nimln_(374, "/usr/lib/nim/pure/strutils.nim");
				{
					if (!(splitsX60gensym34_ == ((NI) 0))) goto LA82_;
					goto LA22;
				}
				LA82_: ;
				nimln_(375, "/usr/lib/nim/pure/strutils.nim");
				if (nimSubInt(splitsX60gensym34_, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_57)) { raiseOverflow(); goto LA21_;
};
				splitsX60gensym34_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_57);
				nimln_(376, "/usr/lib/nim/pure/strutils.nim");
				if (nimAddInt(lastX60gensym34_, ((NI) 1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_58)) { raiseOverflow(); goto LA21_;
};
				lastX60gensym34_ = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_58);
			} LA23: ;
		} LA22: ;
		{
			LA21_:;
		}
		{
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqdestroy___system_3263((&candidate));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	eqsink___system_3269((&result), TM__yu6cxgKBBXbNsTkT9cyMd4g_59);
	{
		LA1_:;
	}
	{
		eqdestroy___system_3263((&path));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
