/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sosproc.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@spure@sosproc.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg;
typedef struct tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct RootObj RootObj;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ;
typedef struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ;
typedef struct tyTuple__0F3Kz25HWtRatQmCDVHWEA tyTuple__0F3Kz25HWtRatQmCDVHWEA;
typedef struct tyTuple__UV3llMMYFckfui8YMBuUZA tyTuple__UV3llMMYFckfui8YMBuUZA;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ tySequence__xv3aaFd3JCw8NbmALHiezQ;
typedef struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content tySequence__xv3aaFd3JCw8NbmALHiezQ_Content;
typedef struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA tyTuple__sPaDkVPSC0MkcoXCxPH9ccA;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU8 tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA;
typedef int tyArray__SKEqGXcReU4NvbQlH779b5Q[2];
struct tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA {
NimStringV2 sysCommand;
NCSTRING* sysArgs;
NCSTRING* sysEnv;
NCSTRING workingDir;
tyArray__SKEqGXcReU4NvbQlH779b5Q pStdin;
tyArray__SKEqGXcReU4NvbQlH779b5Q pStdout;
tyArray__SKEqGXcReU4NvbQlH779b5Q pStderr;
tyArray__SKEqGXcReU4NvbQlH779b5Q pErrorPipe;
tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg {
  RootObj Sup;
int inHandle;
int outHandle;
int errHandle;
pid_t id;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* inStream;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* outStream;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* errStream;
int exitStatus;
NIM_BOOL exitFlag;
tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options;
};
struct tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ {
NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ {
NI len;
NI cap;
tyTuple__0F3Kz25HWtRatQmCDVHWEA* d;
};
struct tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ {
tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ traceStack;
tyObject_CellSeq__z4KasHYddby49cXX2MD4LxQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
typedef NU8 tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA;
typedef NCSTRING tyUncheckedArray__nvS6J9clHMUMHfoZd8Ad2zg[1];
struct tyTuple__UV3llMMYFckfui8YMBuUZA {
NimStringV2 Field0;
NimStringV2 Field1;
};
struct tySequence__xv3aaFd3JCw8NbmALHiezQ {
  NI len; tySequence__xv3aaFd3JCw8NbmALHiezQ_Content* p;
};
typedef NU8 tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ;
struct tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg {
  RootObj Sup;
NI counter;
tySequence__xv3aaFd3JCw8NbmALHiezQ data;
tyEnum_StringTableMode__G9c4wVDFIzf0xHmQvxso9a9cQ mode;
};
struct tyTuple__sPaDkVPSC0MkcoXCxPH9ccA {
NimStringV2 Field0;
NimStringV2 Field1;
NIM_BOOL Field2;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NimStringV2 tyArray__Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringV2 tyArray__24KAM9afIUgUaqBaEBB6r9bg[3];


#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
#define tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content_PP
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
#define tySequence__xv3aaFd3JCw8NbmALHiezQ_Content_PP
struct tySequence__xv3aaFd3JCw8NbmALHiezQ_Content { NI cap; tyTuple__sPaDkVPSC0MkcoXCxPH9ccA data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_214)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3164)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_227)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_236)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest, void* env);
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env);
static N_INLINE(void, add__system_2723)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__system_1725)(NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__pureZos_450)(NI32 errorCode, NimStringV2 additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__pureZos_453)(void);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_3266)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__systemZassertions_66)(NimStringV2 msg);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZunicode_5812)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x, NimStringV2 value);
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, allocCStringArray__system_3789)(NimStringV2* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, envToCStringArray__pureZosproc_524)(void);
static N_INLINE(NIM_BOOL, eqeq___system_7440)(NCSTRING x, NCSTRING y);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s, NIM_CHAR sub, NI start, NI last);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZos_338)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest, tyTuple__UV3llMMYFckfui8YMBuUZA src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7460)(NimStringV2 s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_7472)(NimStringV2 s, NI first);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZos_335)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest, tyTuple__UV3llMMYFckfui8YMBuUZA src);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_3269)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3263)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZos_332)(tyTuple__UV3llMMYFckfui8YMBuUZA* dest);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_1727)(NI size);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, envToCStringArray__pureZosproc_513)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t);
N_LIB_PRIVATE N_NIMCALL(NI, nstlen)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(pid_t, startProcessAuxFork__pureZosproc_552)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZosproc_655)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* dest, tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* src);
N_LIB_PRIVATE N_CDECL(void, startProcessAfterFork__pureZosproc_554)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data);
N_LIB_PRIVATE N_NIMCALL(void, startProcessFail__pureZosproc_702)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, findExe__pureZos_803)(NimStringV2 exe, NIM_BOOL followSymlinks, NimStringV2* extensions, NI extensionsLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr, NimStringV2* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_652)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a, NI aLen_0, NimStringV2 sep);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, deallocCStringArray__system_3829)(NCSTRING* a);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3756)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* dest);
N_LIB_PRIVATE TNimTypeV2 NTIv2__2rGNQnv9bU4hanI2g3svReg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__HZdw8BhppcTQo8DIK46LSg_7 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_8 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_7};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__HZdw8BhppcTQo8DIK46LSg_9 = { 7 | NIM_STRLIT_FLAG, "/bin/sh" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_10 = {7, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_9};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_11 = {7, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_9};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__HZdw8BhppcTQo8DIK46LSg_12 = { 2 | NIM_STRLIT_FLAG, "-c" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_13 = {2, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_12};
static const struct {
  NI cap; NIM_CHAR data[102+1];
} TM__HZdw8BhppcTQo8DIK46LSg_14 = { 102 | NIM_STRLIT_FLAG, "/usr/lib/nim/pure/osproc.nim(988, 14) `args.len == 0` `args` has to be empty when using poEvalCommand." };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_15 = {102, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_14};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_28 = { 1 | NIM_STRLIT_FLAG, "=" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_29 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_28};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_35 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_28};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_40 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_7};
extern NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA ExeExts__pureZos_802;
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_41 = {0, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_7};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__HZdw8BhppcTQo8DIK46LSg_42 = { 42 | NIM_STRLIT_FLAG, "Could not find command: \'$1\'. OS error: $2" };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_43 = {42, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_42};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__HZdw8BhppcTQo8DIK46LSg_44 = { 1 | NIM_STRLIT_FLAG, " " };
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_45 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_44};
static const NimStringV2 TM__HZdw8BhppcTQo8DIK46LSg_46 = {1, (NimStrPayload*)&TM__HZdw8BhppcTQo8DIK46LSg_44};
extern NIM_BOOL nimInErrorMode__system_4240;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NCSTRING* environ;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/usr/lib/nim/system/arithmetics.nim");
	nimln_(418, "/usr/lib/nim/system/arithmetics.nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicDyn", "/usr/lib/nim/system/orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(475, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		nimln_(476, "/usr/lib/nim/system/orc.nim");
		nimln_(63, "/usr/lib/nim/system/arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		nimln_(477, "/usr/lib/nim/system/orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;
			nimln_(478, "/usr/lib/nim/system/orc.nim");
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__HZdw8BhppcTQo8DIK46LSg_2;
			nimln_(481, "/usr/lib/nim/system/orc.nim");
			if (nimSubInt((*cell).rc, ((NI) 16), &TM__HZdw8BhppcTQo8DIK46LSg_2)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_2);
		}
		LA6_: ;
		nimln_(483, "/usr/lib/nim/system/orc.nim");
		rememberCycle__system_3164(result, cell, (*((TNimTypeV2**) (p))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_214)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg** dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_227)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLastCyclicDyn((*dest).inStream);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).inStream);
	}
	LA4_: ;
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLastCyclicDyn((*dest).outStream);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).outStream);
	}
	LA9_: ;
	{
		NIM_BOOL T13_;
		T13_ = (NIM_BOOL)0;
		T13_ = nimDecRefIsLastCyclicDyn((*dest).errStream);
		if (!T13_) goto LA14_;
		nimDestroyAndDispose((*dest).errStream);
	}
	LA14_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, add__system_2723)(tyObject_CellSeq__sGle0igznE2T7vk4dBh5SQ* s, void** c, TNimTypeV2* t) {
	void** colontmp_;
	TNimTypeV2* colontmp__2;
	NI TM__HZdw8BhppcTQo8DIK46LSg_6;
	nimfr_("add", "/usr/lib/nim/system/cellseqs_v2.nim");
{	nimln_(20, "/usr/lib/nim/system/cellseqs_v2.nim");
	{
		NI TM__HZdw8BhppcTQo8DIK46LSg_3;
		tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
		NI TM__HZdw8BhppcTQo8DIK46LSg_4;
		void* T5_;
		NI TM__HZdw8BhppcTQo8DIK46LSg_5;
		if (!((*s).cap <= (*s).len)) goto LA3_;
		nimln_(21, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).cap, ((NI) 3), &TM__HZdw8BhppcTQo8DIK46LSg_3)) { raiseOverflow(); goto BeforeRet_;
};
		(*s).cap = (NI)((NI)(TM__HZdw8BhppcTQo8DIK46LSg_3) / ((NI) 2));
		nimln_(25, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).cap, ((NI) 8), &TM__HZdw8BhppcTQo8DIK46LSg_4)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_4)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_4)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_4), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T5_ = (void*)0;
		T5_ = allocImpl__system_1725(((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_4))));
		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
		nimln_(26, "/usr/lib/nim/system/cellseqs_v2.nim");
		if (nimMulInt((*s).len, ((NI) 8), &TM__HZdw8BhppcTQo8DIK46LSg_5)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_5)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_5)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_5), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) (d)), ((void*) ((*s).d)), ((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_5))));
		nimln_(30, "/usr/lib/nim/system/cellseqs_v2.nim");
		dealloc(((void*) ((*s).d)));
		nimln_(31, "/usr/lib/nim/system/cellseqs_v2.nim");
		(*s).d = d;
	}
	LA3_: ;
	nimln_(33, "/usr/lib/nim/system/cellseqs_v2.nim");
	colontmp_ = c;
	colontmp__2 = t;
	(*s).d[(*s).len].Field0 = colontmp_;
	(*s).d[(*s).len].Field1 = colontmp__2;
	nimln_(34, "/usr/lib/nim/system/cellseqs_v2.nim");
	if (nimAddInt((*s).len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_6)) { raiseOverflow(); goto BeforeRet_;
};
	(*s).len = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_6);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimTraceRefDyn)(void* q, void* env) {
	void** p;
	nimfr_("nimTraceRefDyn", "/usr/lib/nim/system/orc.nim");
	nimln_(130, "/usr/lib/nim/system/orc.nim");
	p = ((void**) (q));
	nimln_(131, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ* j;
		if (!!(((*p) == NIM_NIL))) goto LA3_;
		nimln_(132, "/usr/lib/nim/system/orc.nim");
		j = ((tyObject_GcEnv__g0b9ao2MXcYnUpu9b4I8eP9bQ*) (env));
		nimln_(133, "/usr/lib/nim/system/orc.nim");
		add__system_2723((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___pureZosproc_236)(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* dest, void* env) {
	nimTraceRefDyn(&(*dest).inStream, env);
	nimTraceRefDyn(&(*dest).outStream, env);
	nimTraceRefDyn(&(*dest).errStream, env);
}
static N_INLINE(NIM_BOOL, eqeq___system_7440)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "/usr/lib/nim/system.nim");
	result = (NIM_BOOL)0;
	nimln_(2994, "/usr/lib/nim/system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2995, "/usr/lib/nim/system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(2996, "/usr/lib/nim/system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		NI TM__HZdw8BhppcTQo8DIK46LSg_26;
		NI TM__HZdw8BhppcTQo8DIK46LSg_27;
		if (!(((NI) 0) < src.len)) goto LA3_;
		if (nimAddInt(src.len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_26)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_26)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_26)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_26), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_26))));
		if (nimAddInt((*dest).len, src.len, &TM__HZdw8BhppcTQo8DIK46LSg_27)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_27);
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, envToCStringArray__pureZosproc_524)(void) {
	NCSTRING* result;
	NI counter;
	NI TM__HZdw8BhppcTQo8DIK46LSg_21;
	NI TM__HZdw8BhppcTQo8DIK46LSg_22;
	void* T7_;
	NI i_2;
NIM_BOOL* nimErr_;
	nimfr_("envToCStringArray", "/usr/lib/nim/pure/osproc.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING*)0;
	nimln_(933, "/usr/lib/nim/pure/osproc.nim");
	counter = ((NI) 0);
	{
		NimStringV2 key;
		NimStringV2 val;
		key.len = 0; key.p = NIM_NIL;
		val.len = 0; val.p = NIM_NIL;
		{
			tyTuple__UV3llMMYFckfui8YMBuUZA ai;
			NI i;
			nimZeroMem((void*)(&ai), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
			nimln_(176, "/usr/lib/nim/pure/includes/osenv.nim");
			i = ((NI) 0);
			{
				nimln_(179, "/usr/lib/nim/pure/includes/osenv.nim");
				while (1) {
					NIM_BOOL T5_;
					NimStringV2 kv;
					tyTuple__UV3llMMYFckfui8YMBuUZA colontmp_;
					NI TM__HZdw8BhppcTQo8DIK46LSg_17;
					NI p;
					tyTuple__UV3llMMYFckfui8YMBuUZA T6_;
					NI TM__HZdw8BhppcTQo8DIK46LSg_18;
					NI TM__HZdw8BhppcTQo8DIK46LSg_19;
					NI TM__HZdw8BhppcTQo8DIK46LSg_20;
					T5_ = (NIM_BOOL)0;
					T5_ = eqeq___system_7440(environ[i], ((NCSTRING) NIM_NIL));
					if (!!(T5_)) goto LA4;
					kv.len = 0; kv.p = NIM_NIL;
					nimZeroMem((void*)(&colontmp_), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
					nimln_(180, "/usr/lib/nim/pure/includes/osenv.nim");
					kv = cstrToNimstr(environ[i]);
					nimln_(181, "/usr/lib/nim/pure/includes/osenv.nim");
					if (nimAddInt(i, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_17)) { raiseOverflow(); goto BeforeRet_;
};
					i = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_17);
					nimln_(182, "/usr/lib/nim/pure/includes/osenv.nim");
					p = nsuFindChar(kv, 61, ((NI) 0), ((NI) 0));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					nimln_(183, "/usr/lib/nim/pure/includes/osenv.nim");
					if (nimSubInt(p, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_18)) { raiseOverflow(); goto BeforeRet_;
};
					T6_.Field0 = substr__system_7460(kv, ((NI) 0), (NI)(TM__HZdw8BhppcTQo8DIK46LSg_18));
					if (nimAddInt(p, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_19)) { raiseOverflow(); goto BeforeRet_;
};
					T6_.Field1 = substr__system_7472(kv, (NI)(TM__HZdw8BhppcTQo8DIK46LSg_19));
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					eqsink___pureZos_338((&ai), T6_);
					nimln_(203, "/usr/lib/nim/pure/includes/osenv.nim");
					nimZeroMem((void*)(&colontmp_), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					eqcopy___pureZos_335((&colontmp_), ai);
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqsink___system_3269((&key), colontmp_.Field0);
					eqsink___system_3269((&val), colontmp_.Field1);
					nimln_(934, "/usr/lib/nim/pure/osproc.nim");
					if (nimAddInt(counter, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_20)) { raiseOverflow(); goto BeforeRet_;
};
					counter = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_20);
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqdestroy___system_3263((&kv));
				} LA4: ;
			}
			nimln_(720, "/usr/lib/nim/pure/os.nim");
			eqdestroy___pureZos_332((&ai));
		}
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&val));
		eqdestroy___system_3263((&key));
	}
	nimln_(935, "/usr/lib/nim/pure/osproc.nim");
	if (nimAddInt(counter, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_21)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimMulInt((NI)(TM__HZdw8BhppcTQo8DIK46LSg_21), ((NI) 4), &TM__HZdw8BhppcTQo8DIK46LSg_22)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_22)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_22)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_22), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	T7_ = (void*)0;
	T7_ = alloc0Impl__system_1727(((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_22))));
	result = ((NCSTRING*) (T7_));
	nimln_(936, "/usr/lib/nim/pure/osproc.nim");
	i_2 = ((NI) 0);
	{
		NimStringV2 key_2;
		NimStringV2 val_2;
		key_2.len = 0; key_2.p = NIM_NIL;
		val_2.len = 0; val_2.p = NIM_NIL;
		{
			tyTuple__UV3llMMYFckfui8YMBuUZA ai_2;
			NI i_3;
			nimZeroMem((void*)(&ai_2), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
			nimln_(176, "/usr/lib/nim/pure/includes/osenv.nim");
			i_3 = ((NI) 0);
			{
				nimln_(179, "/usr/lib/nim/pure/includes/osenv.nim");
				while (1) {
					NIM_BOOL T12_;
					NimStringV2 kv_2;
					tyTuple__UV3llMMYFckfui8YMBuUZA colontmp__2;
					NimStringV2 x;
					NI TM__HZdw8BhppcTQo8DIK46LSg_23;
					NI p_2;
					tyTuple__UV3llMMYFckfui8YMBuUZA T13_;
					NI TM__HZdw8BhppcTQo8DIK46LSg_24;
					NI TM__HZdw8BhppcTQo8DIK46LSg_25;
					NimStringV2 T14_;
					NI TM__HZdw8BhppcTQo8DIK46LSg_30;
					void* T15_;
					NI TM__HZdw8BhppcTQo8DIK46LSg_31;
					NI TM__HZdw8BhppcTQo8DIK46LSg_32;
					T12_ = (NIM_BOOL)0;
					T12_ = eqeq___system_7440(environ[i_3], ((NCSTRING) NIM_NIL));
					if (!!(T12_)) goto LA11;
					kv_2.len = 0; kv_2.p = NIM_NIL;
					nimZeroMem((void*)(&colontmp__2), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
					x.len = 0; x.p = NIM_NIL;
					nimln_(180, "/usr/lib/nim/pure/includes/osenv.nim");
					kv_2 = cstrToNimstr(environ[i_3]);
					nimln_(181, "/usr/lib/nim/pure/includes/osenv.nim");
					if (nimAddInt(i_3, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_23)) { raiseOverflow(); goto BeforeRet_;
};
					i_3 = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_23);
					nimln_(182, "/usr/lib/nim/pure/includes/osenv.nim");
					p_2 = nsuFindChar(kv_2, 61, ((NI) 0), ((NI) 0));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					nimln_(183, "/usr/lib/nim/pure/includes/osenv.nim");
					if (nimSubInt(p_2, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_24)) { raiseOverflow(); goto BeforeRet_;
};
					T13_.Field0 = substr__system_7460(kv_2, ((NI) 0), (NI)(TM__HZdw8BhppcTQo8DIK46LSg_24));
					if (nimAddInt(p_2, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_25)) { raiseOverflow(); goto BeforeRet_;
};
					T13_.Field1 = substr__system_7472(kv_2, (NI)(TM__HZdw8BhppcTQo8DIK46LSg_25));
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					eqsink___pureZos_338((&ai_2), T13_);
					nimln_(203, "/usr/lib/nim/pure/includes/osenv.nim");
					nimZeroMem((void*)(&colontmp__2), sizeof(tyTuple__UV3llMMYFckfui8YMBuUZA));
					nimln_(720, "/usr/lib/nim/pure/os.nim");
					eqcopy___pureZos_335((&colontmp__2), ai_2);
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqsink___system_3269((&key_2), colontmp__2.Field0);
					eqsink___system_3269((&val_2), colontmp__2.Field1);
					nimln_(938, "/usr/lib/nim/pure/osproc.nim");
					T14_.len = 0; T14_.p = NIM_NIL;
					T14_ = rawNewString(key_2.len + val_2.len + 1);
appendString((&T14_), key_2);
appendString((&T14_), TM__HZdw8BhppcTQo8DIK46LSg_29);
appendString((&T14_), val_2);
					x = T14_;
					nimln_(939, "/usr/lib/nim/pure/osproc.nim");
					if (nimAddInt(x.len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_30)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_30)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_30)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_30), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
					T15_ = (void*)0;
					T15_ = allocImpl__system_1725(((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_30))));
					result[i_2] = ((NCSTRING) (T15_));
					nimln_(937, "/usr/lib/nim/pure/osproc.nim");
					if (((NI) 0) < 0 || ((NI) 0) >= x.len){ raiseIndexError2(((NI) 0),x.len-1); goto BeforeRet_;
}
					nimln_(940, "/usr/lib/nim/pure/osproc.nim");
					if (nimAddInt(x.len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_31)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_31)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_31)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_31), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
					nimln_(937, "/usr/lib/nim/pure/osproc.nim");
					copyMem__system_1709(((void*) (result[i_2])), ((void*) ((&x.p->data[((NI) 0)]))), ((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_31))));
					if (nimAddInt(i_2, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_32)) { raiseOverflow(); goto BeforeRet_;
};
					i_2 = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_32);
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqdestroy___system_3263((&x));
					eqdestroy___system_3263((&kv_2));
				} LA11: ;
			}
			nimln_(720, "/usr/lib/nim/pure/os.nim");
			eqdestroy___pureZos_332((&ai_2));
		}
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&val_2));
		eqdestroy___system_3263((&key_2));
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, envToCStringArray__pureZosproc_513)(tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* t) {
	NCSTRING* result;
	NI T1_;
	NI TM__HZdw8BhppcTQo8DIK46LSg_33;
	NI TM__HZdw8BhppcTQo8DIK46LSg_34;
	void* T2_;
	NI i;
NIM_BOOL* nimErr_;
	nimfr_("envToCStringArray", "/usr/lib/nim/pure/osproc.nim");
{nimErr_ = nimErrorFlag();
	result = (NCSTRING*)0;
	nimln_(924, "/usr/lib/nim/pure/osproc.nim");
	T1_ = (NI)0;
	T1_ = nstlen(t);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (nimAddInt(T1_, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_33)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimMulInt((NI)(TM__HZdw8BhppcTQo8DIK46LSg_33), ((NI) 4), &TM__HZdw8BhppcTQo8DIK46LSg_34)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_34)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_34)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_34), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	T2_ = (void*)0;
	T2_ = alloc0Impl__system_1727(((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_34))));
	result = ((NCSTRING*) (T2_));
	nimln_(925, "/usr/lib/nim/pure/osproc.nim");
	i = ((NI) 0);
	{
		NimStringV2 key;
		NimStringV2 val;
		key.len = 0; key.p = NIM_NIL;
		val.len = 0; val.p = NIM_NIL;
		{
			NI h;
			NI colontmp_;
			NI T5_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(96, "/usr/lib/nim/pure/strtabs.nim");
			T5_ = ((*t).data.len-1);
			colontmp_ = T5_;
			nimln_(90, "/usr/lib/nim/system/iterators_1.nim");
			res = ((NI) 0);
			{
				nimln_(91, "/usr/lib/nim/system/iterators_1.nim");
				while (1) {
					NI TM__HZdw8BhppcTQo8DIK46LSg_39;
					if (!(res <= colontmp_)) goto LA7;
					nimln_(96, "/usr/lib/nim/pure/strtabs.nim");
					h = res;
					{
						NimStringV2 x;
						NimStringV2 T12_;
						NI TM__HZdw8BhppcTQo8DIK46LSg_36;
						void* T13_;
						NI TM__HZdw8BhppcTQo8DIK46LSg_37;
						NI TM__HZdw8BhppcTQo8DIK46LSg_38;
						if (h < 0 || h >= (*t).data.len){ raiseIndexError2(h,(*t).data.len-1); goto BeforeRet_;
}
						if (!(*t).data.p->data[h].Field2) goto LA10_;
						x.len = 0; x.p = NIM_NIL;
						nimln_(54, "/usr/lib/nim/system/fatal.nim");
						if (h < 0 || h >= (*t).data.len){ raiseIndexError2(h,(*t).data.len-1); goto BeforeRet_;
}
						eqcopy___system_3266((&key), (*t).data.p->data[h].Field0);
						if (h < 0 || h >= (*t).data.len){ raiseIndexError2(h,(*t).data.len-1); goto BeforeRet_;
}
						eqcopy___system_3266((&val), (*t).data.p->data[h].Field1);
						nimln_(927, "/usr/lib/nim/pure/osproc.nim");
						T12_.len = 0; T12_.p = NIM_NIL;
						T12_ = rawNewString(key.len + val.len + 1);
appendString((&T12_), key);
appendString((&T12_), TM__HZdw8BhppcTQo8DIK46LSg_35);
appendString((&T12_), val);
						x = T12_;
						nimln_(928, "/usr/lib/nim/pure/osproc.nim");
						if (nimAddInt(x.len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_36)) { raiseOverflow(); goto BeforeRet_;
};
						if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_36)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_36)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_36), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
						T13_ = (void*)0;
						T13_ = allocImpl__system_1725(((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_36))));
						result[i] = ((NCSTRING) (T13_));
						nimln_(926, "/usr/lib/nim/pure/osproc.nim");
						if (((NI) 0) < 0 || ((NI) 0) >= x.len){ raiseIndexError2(((NI) 0),x.len-1); goto BeforeRet_;
}
						nimln_(929, "/usr/lib/nim/pure/osproc.nim");
						if (nimAddInt(x.len, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_37)) { raiseOverflow(); goto BeforeRet_;
};
						if (((NI)(TM__HZdw8BhppcTQo8DIK46LSg_37)) < ((NI) 0) || ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_37)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__HZdw8BhppcTQo8DIK46LSg_37), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
						nimln_(926, "/usr/lib/nim/pure/osproc.nim");
						copyMem__system_1709(((void*) (result[i])), ((void*) ((&x.p->data[((NI) 0)]))), ((NI) ((NI)(TM__HZdw8BhppcTQo8DIK46LSg_37))));
						if (nimAddInt(i, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_38)) { raiseOverflow(); goto BeforeRet_;
};
						i = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_38);
						nimln_(54, "/usr/lib/nim/system/fatal.nim");
						eqdestroy___system_3263((&x));
					}
					LA10_: ;
					nimln_(93, "/usr/lib/nim/system/iterators_1.nim");
					if (nimAddInt(res, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_39)) { raiseOverflow(); goto BeforeRet_;
};
					res = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_39);
				} LA7: ;
			}
		}
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqdestroy___system_3263((&val));
		eqdestroy___system_3263((&key));
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZosproc_655)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* dest, tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* src) {
	eqcopy___system_3266((&(*dest).sysCommand), (*src).sysCommand);
	(*dest).sysArgs = (*src).sysArgs;
	(*dest).sysEnv = (*src).sysEnv;
	(*dest).workingDir = (*src).workingDir;
	nimCopyMem((void*)(*dest).pStdin, (NIM_CONST void*)(*src).pStdin, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimCopyMem((void*)(*dest).pStdout, (NIM_CONST void*)(*src).pStdout, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimCopyMem((void*)(*dest).pStderr, (NIM_CONST void*)(*src).pStderr, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimCopyMem((void*)(*dest).pErrorPipe, (NIM_CONST void*)(*src).pErrorPipe, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	(*dest).options = (*src).options;
}
N_LIB_PRIVATE N_NIMCALL(void, startProcessFail__pureZosproc_702)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data) {
	int error;
	NI T1_;
	error = errno;
	T1_ = (NI)0;
	T1_ = write((*data).pErrorPipe[(((NI) 1))- 0], ((void*) ((&error))), ((NI) 4));
	(void)(T1_);
	_exit(((NI) 1));
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_CDECL(void, startProcessAfterFork__pureZosproc_554)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data) {
	int T42_;
	int T43_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		int T5_;
		int T11_;
		int T17_;
		if (!!((((*data).options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 4))&7U)))!=0))) goto LA3_;
		T5_ = (int)0;
		T5_ = close((*data).pStdin[(((NI) 1))- 0]);
		(void)(T5_);
		{
			int T8_;
			T8_ = (int)0;
			T8_ = dup2((*data).pStdin[(((NI) 0))- 0], ((int) 0));
			if (!(T8_ < ((NI32) 0))) goto LA9_;
			startProcessFail__pureZosproc_702(data);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA9_: ;
		T11_ = (int)0;
		T11_ = close((*data).pStdout[(((NI) 0))- 0]);
		(void)(T11_);
		{
			int T14_;
			T14_ = (int)0;
			T14_ = dup2((*data).pStdout[(((NI) 1))- 0], ((int) 1));
			if (!(T14_ < ((NI32) 0))) goto LA15_;
			startProcessFail__pureZosproc_702(data);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA15_: ;
		T17_ = (int)0;
		T17_ = close((*data).pStderr[(((NI) 0))- 0]);
		(void)(T17_);
		{
			if (!(((*data).options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 3))&7U)))!=0)) goto LA20_;
			{
				int T24_;
				T24_ = (int)0;
				T24_ = dup2((*data).pStdout[(((NI) 1))- 0], ((int) 2));
				if (!(T24_ < ((NI32) 0))) goto LA25_;
				startProcessFail__pureZosproc_702(data);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			LA25_: ;
		}
		goto LA18_;
		LA20_: ;
		{
			{
				int T30_;
				T30_ = (int)0;
				T30_ = dup2((*data).pStderr[(((NI) 1))- 0], ((int) 2));
				if (!(T30_ < ((NI32) 0))) goto LA31_;
				startProcessFail__pureZosproc_702(data);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			}
			LA31_: ;
		}
		LA18_: ;
	}
	LA3_: ;
	{
		if (!(((NI) 0) < ((*data).workingDir ? nimCStrLen((*data).workingDir) : 0))) goto LA35_;
		{
			int T39_;
			T39_ = (int)0;
			T39_ = chdir((*data).workingDir);
			if (!(T39_ < ((NI32) 0))) goto LA40_;
			startProcessFail__pureZosproc_702(data);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA40_: ;
	}
	LA35_: ;
	T42_ = (int)0;
	T42_ = close((*data).pErrorPipe[(((NI) 0))- 0]);
	(void)(T42_);
	T43_ = (int)0;
	T43_ = fcntl((*data).pErrorPipe[(((NI) 1))- 0], F_SETFD, FD_CLOEXEC);
	(void)(T43_);
	{
		NimStringV2 exe;
		int T49_;
		if (!(((*data).options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 1))&7U)))!=0)) goto LA46_;
		exe.len = 0; exe.p = NIM_NIL;
		exe = findExe__pureZos_803((*data).sysCommand, NIM_TRUE, ExeExts__pureZos_802, 1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA48_;
		T49_ = (int)0;
		T49_ = execve(nimToCStringConv(exe), (*data).sysArgs, (*data).sysEnv);
		(void)(T49_);
		{
			LA48_:;
		}
		{
			eqdestroy___system_3263((&exe));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA44_;
	LA46_: ;
	{
		int T53_;
		T53_ = (int)0;
		T53_ = execve(nimToCStringConv((*data).sysCommand), (*data).sysArgs, (*data).sysEnv);
		(void)(T53_);
	}
	LA44_: ;
	startProcessFail__pureZosproc_702(data);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZosproc_652)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* dest) {
	eqdestroy___system_3263((&(*dest).sysCommand));
}
N_LIB_PRIVATE N_NIMCALL(pid_t, startProcessAuxFork__pureZosproc_552)(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA* data) {
	pid_t result;
	tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA dataCopy;
	pid_t pid;
	int T13_;
	int error;
	NI sizeRead;
	int T29_;
NIM_BOOL* nimErr_;
	nimfr_("startProcessAuxFork", "/usr/lib/nim/pure/osproc.nim");
{nimErr_ = nimErrorFlag();
	result = (pid_t)0;
	nimln_(1100, "/usr/lib/nim/pure/osproc.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = pipe((*data).pErrorPipe);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		nimln_(1101, "/usr/lib/nim/pure/osproc.nim");
		T6_ = (NI32)0;
		T6_ = osLastError__pureZos_453();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__pureZos_450(T6_, TM__HZdw8BhppcTQo8DIK46LSg_40);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	nimZeroMem((void*)(&dataCopy), sizeof(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA));
	pid = (pid_t)0;
	nimln_(980, "/usr/lib/nim/pure/osproc.nim");
	eqcopy___pureZosproc_655((&dataCopy), data);
	nimln_(1120, "/usr/lib/nim/pure/osproc.nim");
	pid = fork();
	nimln_(1121, "/usr/lib/nim/pure/osproc.nim");
	{
		if (!(pid == ((NI32) 0))) goto LA11_;
		nimln_(1122, "/usr/lib/nim/pure/osproc.nim");
		startProcessAfterFork__pureZosproc_554((&dataCopy));
		if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		nimln_(1123, "/usr/lib/nim/pure/osproc.nim");
		_exit(((NI) 1));
	}
	LA11_: ;
	nimln_(1125, "/usr/lib/nim/pure/osproc.nim");
	T13_ = (int)0;
	T13_ = close((*data).pErrorPipe[(((NI) 1))- 0]);
	(void)(T13_);
	nimln_(1126, "/usr/lib/nim/pure/osproc.nim");
	{
		NI32 T18_;
		if (!(pid < ((NI32) 0))) goto LA16_;
		T18_ = (NI32)0;
		T18_ = osLastError__pureZos_453();
		if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
		raiseOSError__pureZos_450(T18_, TM__HZdw8BhppcTQo8DIK46LSg_41);
		if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
	}
	LA16_: ;
	error = (int)0;
	nimln_(1129, "/usr/lib/nim/pure/osproc.nim");
	sizeRead = read((*data).pErrorPipe[(((NI) 0))- 0], ((void*) ((&error))), ((NI) 4));
	nimln_(1130, "/usr/lib/nim/pure/osproc.nim");
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NI32 T24_;
		tyArray__Re75IspeoxXy2oCZHwcRrA T25_;
		NCSTRING T26_;
		if (!(sizeRead == ((NI) 4))) goto LA21_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(1131, "/usr/lib/nim/pure/osproc.nim");
		T24_ = (NI32)0;
		T24_ = osLastError__pureZos_453();
		if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
		nimln_(1132, "/usr/lib/nim/pure/osproc.nim");
		T25_[0] = (*data).sysCommand;
		nimln_(1133, "/usr/lib/nim/pure/osproc.nim");
		T26_ = (NCSTRING)0;
		T26_ = strerror(error);
		colontmpD_ = cstrToNimstr(T26_);
		T25_[1] = colontmpD_;
		nimln_(1132, "/usr/lib/nim/pure/osproc.nim");
		colontmpD__2 = nsuFormatOpenArray(TM__HZdw8BhppcTQo8DIK46LSg_43, T25_, 2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
		nimln_(1131, "/usr/lib/nim/pure/osproc.nim");
		raiseOSError__pureZos_450(T24_, colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto LA23_;
		{
			LA23_:;
		}
		{
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqdestroy___system_3263((&colontmpD__2));
			eqdestroy___system_3263((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA8_;
	}
	LA21_: ;
	nimln_(1135, "/usr/lib/nim/pure/osproc.nim");
	result = pid;
	nimln_(980, "/usr/lib/nim/pure/osproc.nim");
	eqdestroy___pureZosproc_652((&dataCopy));
	nimln_(1104, "/usr/lib/nim/pure/osproc.nim");
	T29_ = (int)0;
	T29_ = close((*data).pErrorPipe[(((NI) 0))- 0]);
	(void)(T29_);
	goto BeforeRet_;
	{
		LA8_:;
	}
	{
		nimln_(980, "/usr/lib/nim/pure/osproc.nim");
		eqdestroy___pureZosproc_652((&dataCopy));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA7_;
	{
		LA7_:;
	}
	{
		int T34_;
		nimln_(1104, "/usr/lib/nim/pure/osproc.nim");
		T34_ = (int)0;
		T34_ = close((*data).pErrorPipe[(((NI) 0))- 0]);
		(void)(T34_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*, nospstartProcess)(NimStringV2 command, NimStringV2 workingDir, NimStringV2* args, NI argsLen_0, tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg* env, tySet_tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA options) {
	tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg* result;
	tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA data;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ sysArgsRaw;
	tyArray__SKEqGXcReU4NvbQlH779b5Q pStdin;
	tyArray__SKEqGXcReU4NvbQlH779b5Q pStdout;
	tyArray__SKEqGXcReU4NvbQlH779b5Q pStderr;
	pid_t pid;
	NCSTRING* sysArgs;
	NCSTRING* colontmpD__4;
	NCSTRING* colontmpD__5;
	NCSTRING* sysEnv;
NIM_BOOL* nimErr_;
	nimfr_("startProcess", "/usr/lib/nim/pure/osproc.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&data), sizeof(tyObject_StartProcessData__xgRnKnLIYRtnOkshMKhc9cA));
	sysArgsRaw.len = 0; sysArgsRaw.p = NIM_NIL;
	nimZeroMem((void*)pStdin, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimZeroMem((void*)pStdout, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimZeroMem((void*)pStderr, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimln_(1002, "/usr/lib/nim/system.nim");
	eqdestroy___pureZosproc_214(&result);
	nimln_(971, "/usr/lib/nim/pure/osproc.nim");
	result = (tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg*) nimNewObj(sizeof(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg), NIM_ALIGNOF(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg));
	(*result).Sup.m_type = (&NTIv2__2rGNQnv9bU4hanI2g3svReg_);
	nimln_(972, "/usr/lib/nim/pure/osproc.nim");
	(*result).options = options;
	nimln_(973, "/usr/lib/nim/pure/osproc.nim");
	(*result).exitFlag = NIM_TRUE;
	nimln_(975, "/usr/lib/nim/pure/osproc.nim");
	{
		if (!!(((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 4))&7U)))!=0))) goto LA4_;
		nimln_(976, "/usr/lib/nim/pure/osproc.nim");
		{
			NIM_BOOL T8_;
			NIM_BOOL T9_;
			int T10_;
			int T12_;
			int T14_;
			NI32 T17_;
			T8_ = (NIM_BOOL)0;
			T9_ = (NIM_BOOL)0;
			T10_ = (int)0;
			T10_ = pipe(pStdin);
			T9_ = !((T10_ == ((NI32) 0)));
			if (T9_) goto LA11_;
			T12_ = (int)0;
			T12_ = pipe(pStdout);
			T9_ = !((T12_ == ((NI32) 0)));
			LA11_: ;
			T8_ = T9_;
			if (T8_) goto LA13_;
			nimln_(977, "/usr/lib/nim/pure/osproc.nim");
			T14_ = (int)0;
			T14_ = pipe(pStderr);
			T8_ = !((T14_ == ((NI32) 0)));
			LA13_: ;
			if (!T8_) goto LA15_;
			nimln_(978, "/usr/lib/nim/pure/osproc.nim");
			T17_ = (NI32)0;
			T17_ = osLastError__pureZos_453();
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			raiseOSError__pureZos_450(T17_, TM__HZdw8BhppcTQo8DIK46LSg_8);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA15_: ;
	}
	LA4_: ;
	nimln_(982, "/usr/lib/nim/pure/osproc.nim");
	{
		NimStringV2 colontmpD_;
		if (!((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 2))&7U)))!=0)) goto LA20_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(984, "/usr/lib/nim/pure/osproc.nim");
		data.sysCommand = TM__HZdw8BhppcTQo8DIK46LSg_10;
		nimln_(987, "/usr/lib/nim/pure/osproc.nim");
		sysArgsRaw.len = 3; sysArgsRaw.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(3, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
		sysArgsRaw.p->data[0] = TM__HZdw8BhppcTQo8DIK46LSg_11;
		sysArgsRaw.p->data[1] = TM__HZdw8BhppcTQo8DIK46LSg_13;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&colontmpD_), command);
		sysArgsRaw.p->data[2] = colontmpD_;
		nimln_(988, "/usr/lib/nim/pure/osproc.nim");
		{
			if (!!((argsLen_0 == ((NI) 0)))) goto LA24_;
			failedAssertImpl__systemZassertions_66(TM__HZdw8BhppcTQo8DIK46LSg_15);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		}
		LA24_: ;
	}
	goto LA18_;
	LA20_: ;
	{
		NimStringV2 colontmpD__2;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&data.sysCommand), command);
		nimln_(991, "/usr/lib/nim/pure/osproc.nim");
		sysArgsRaw.len = 1; sysArgsRaw.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(1, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(54, "/usr/lib/nim/system/fatal.nim");
		eqcopy___system_3266((&colontmpD__2), command);
		sysArgsRaw.p->data[0] = colontmpD__2;
		{
			NimStringV2* arg;
			NI i;
			arg = (NimStringV2*)0;
			nimln_(8, "/usr/lib/nim/system/iterators.nim");
			i = ((NI) 0);
			{
				nimln_(9, "/usr/lib/nim/system/iterators.nim");
				while (1) {
					NimStringV2 colontmpD__3;
					NI TM__HZdw8BhppcTQo8DIK46LSg_16;
					if (!(i < argsLen_0)) goto LA29;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					nimln_(992, "/usr/lib/nim/pure/osproc.nim");
					if (i < 0 || i >= argsLen_0){ raiseIndexError2(i,argsLen_0-1); goto LA1_;
}
					arg = (&args[i]);
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					nimln_(54, "/usr/lib/nim/system/fatal.nim");
					eqcopy___system_3266((&colontmpD__3), (*arg));
					nimln_(992, "/usr/lib/nim/pure/osproc.nim");
					add__pureZunicode_5812((&sysArgsRaw), colontmpD__3);
					nimln_(11, "/usr/lib/nim/system/iterators.nim");
					if (nimAddInt(i, ((NI) 1), &TM__HZdw8BhppcTQo8DIK46LSg_16)) { raiseOverflow(); goto LA1_;
};
					i = (NI)(TM__HZdw8BhppcTQo8DIK46LSg_16);
				} LA29: ;
			}
		}
	}
	LA18_: ;
	pid = (pid_t)0;
	nimln_(997, "/usr/lib/nim/pure/osproc.nim");
	sysArgs = allocCStringArray__system_3789(((sysArgsRaw).p) ? (sysArgsRaw.p->data) : NIM_NIL, sysArgsRaw.len);
	colontmpD__4 = (NCSTRING*)0;
	colontmpD__5 = (NCSTRING*)0;
	nimln_(1000, "/usr/lib/nim/pure/osproc.nim");
	{
		if (!(env == ((tyObject_StringTableObj__V5PVrt9bIxZEeV7lfvqqtNg*) NIM_NIL))) goto LA33_;
		nimln_(1001, "/usr/lib/nim/pure/osproc.nim");
		colontmpD__4 = envToCStringArray__pureZosproc_524();
		if (NIM_UNLIKELY(*nimErr_)) goto LA30_;
		sysEnv = colontmpD__4;
	}
	goto LA31_;
	LA33_: ;
	{
		nimln_(1003, "/usr/lib/nim/pure/osproc.nim");
		colontmpD__5 = envToCStringArray__pureZosproc_513(env);
		if (NIM_UNLIKELY(*nimErr_)) goto LA30_;
		sysEnv = colontmpD__5;
	}
	LA31_: ;
	nimln_(1007, "/usr/lib/nim/pure/osproc.nim");
	data.sysArgs = sysArgs;
	nimln_(1008, "/usr/lib/nim/pure/osproc.nim");
	data.sysEnv = sysEnv;
	nimln_(1009, "/usr/lib/nim/pure/osproc.nim");
	nimCopyMem((void*)data.pStdin, (NIM_CONST void*)pStdin, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimln_(1010, "/usr/lib/nim/pure/osproc.nim");
	nimCopyMem((void*)data.pStdout, (NIM_CONST void*)pStdout, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimln_(1011, "/usr/lib/nim/pure/osproc.nim");
	nimCopyMem((void*)data.pStderr, (NIM_CONST void*)pStderr, sizeof(tyArray__SKEqGXcReU4NvbQlH779b5Q));
	nimln_(1012, "/usr/lib/nim/pure/osproc.nim");
	data.workingDir = nimToCStringConv(workingDir);
	nimln_(1013, "/usr/lib/nim/pure/osproc.nim");
	data.options = options;
	nimln_(1021, "/usr/lib/nim/pure/osproc.nim");
	pid = startProcessAuxFork__pureZosproc_552((&data));
	if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
	nimln_(1024, "/usr/lib/nim/pure/osproc.nim");
	{
		NimStringV2 colontmpD__6;
		tyArray__24KAM9afIUgUaqBaEBB6r9bg T42_;
		if (!((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 0))&7U)))!=0)) goto LA39_;
		colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
		nimln_(1025, "/usr/lib/nim/pure/osproc.nim");
		T42_[0] = command;
		T42_[1] = TM__HZdw8BhppcTQo8DIK46LSg_45;
		colontmpD__6 = nsuJoinSep(args, argsLen_0, TM__HZdw8BhppcTQo8DIK46LSg_46);
		if (NIM_UNLIKELY(*nimErr_)) goto LA41_;
		T42_[2] = colontmpD__6;
		echoBinSafe(T42_, 3);
		{
			LA41_:;
		}
		{
			nimln_(54, "/usr/lib/nim/system/fatal.nim");
			eqdestroy___system_3263((&colontmpD__6));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA36_;
	}
	LA39_: ;
	nimln_(1026, "/usr/lib/nim/pure/osproc.nim");
	(*result).id = pid;
	nimln_(1027, "/usr/lib/nim/pure/osproc.nim");
	(*result).exitFlag = NIM_FALSE;
	nimln_(1029, "/usr/lib/nim/pure/osproc.nim");
	{
		if (!((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 4))&7U)))!=0)) goto LA47_;
		nimln_(1031, "/usr/lib/nim/pure/osproc.nim");
		(*result).inHandle = ((int) 0);
		nimln_(1032, "/usr/lib/nim/pure/osproc.nim");
		(*result).outHandle = ((int) 1);
		nimln_(1033, "/usr/lib/nim/pure/osproc.nim");
		{
			if (!((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 3))&7U)))!=0)) goto LA51_;
			nimln_(1034, "/usr/lib/nim/pure/osproc.nim");
			(*result).errHandle = (*result).outHandle;
		}
		goto LA49_;
		LA51_: ;
		{
			nimln_(1036, "/usr/lib/nim/pure/osproc.nim");
			(*result).errHandle = ((int) 2);
		}
		LA49_: ;
	}
	goto LA45_;
	LA47_: ;
	{
		int T61_;
		int T62_;
		int T63_;
		nimln_(1038, "/usr/lib/nim/pure/osproc.nim");
		(*result).inHandle = pStdin[(((NI) 1))- 0];
		nimln_(1039, "/usr/lib/nim/pure/osproc.nim");
		(*result).outHandle = pStdout[(((NI) 0))- 0];
		nimln_(1040, "/usr/lib/nim/pure/osproc.nim");
		{
			int T59_;
			if (!((options &((NU8)1<<((NU)(((tyEnum_ProcessOption__bnU6W8LhTMnT4JaSWtGlSA) 3))&7U)))!=0)) goto LA57_;
			nimln_(1041, "/usr/lib/nim/pure/osproc.nim");
			(*result).errHandle = (*result).outHandle;
			nimln_(1042, "/usr/lib/nim/pure/osproc.nim");
			T59_ = (int)0;
			T59_ = close(pStderr[(((NI) 0))- 0]);
			(void)(T59_);
		}
		goto LA55_;
		LA57_: ;
		{
			nimln_(1044, "/usr/lib/nim/pure/osproc.nim");
			(*result).errHandle = pStderr[(((NI) 0))- 0];
		}
		LA55_: ;
		nimln_(1045, "/usr/lib/nim/pure/osproc.nim");
		T61_ = (int)0;
		T61_ = close(pStderr[(((NI) 1))- 0]);
		(void)(T61_);
		nimln_(1046, "/usr/lib/nim/pure/osproc.nim");
		T62_ = (int)0;
		T62_ = close(pStdin[(((NI) 0))- 0]);
		(void)(T62_);
		nimln_(1047, "/usr/lib/nim/pure/osproc.nim");
		T63_ = (int)0;
		T63_ = close(pStdout[(((NI) 1))- 0]);
		(void)(T63_);
	}
	LA45_: ;
	{
		LA36_:;
	}
	{
		nimln_(1005, "/usr/lib/nim/pure/osproc.nim");
		deallocCStringArray__system_3829(sysEnv);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA30_;
	{
		LA30_:;
	}
	{
		nimln_(998, "/usr/lib/nim/pure/osproc.nim");
		deallocCStringArray__system_3829(sysArgs);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimln_(2264, "/usr/lib/nim/system.nim");
		eqdestroy___system_3756((&sysArgsRaw));
		nimln_(980, "/usr/lib/nim/pure/osproc.nim");
		eqdestroy___pureZosproc_652((&data));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsosprocdotnim_DatInit000)(void) {
NTIv2__2rGNQnv9bU4hanI2g3svReg_.destructor = (void*)eqdestroy___pureZosproc_227; NTIv2__2rGNQnv9bU4hanI2g3svReg_.size = sizeof(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg); NTIv2__2rGNQnv9bU4hanI2g3svReg_.align = NIM_ALIGNOF(tyObject_ProcessObj__2rGNQnv9bU4hanI2g3svReg); NTIv2__2rGNQnv9bU4hanI2g3svReg_.name = "|stdlib.osproc.ProcessObj|RootObj|";
; NTIv2__2rGNQnv9bU4hanI2g3svReg_.traceImpl = (void*)eqtrace___pureZosproc_236; NTIv2__2rGNQnv9bU4hanI2g3svReg_.flags = 0;}

