/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@sstd@sprivate@sdigitsutils.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s..@s..@susr@slib@snim@sstd@sprivate@sdigitsutils.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__PbS9a6gkxCuxWEnFq4lOU9aw[24];
typedef NIM_CHAR tyArray__38Z69amCaoywES5tRmClBSw[200];
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_2330)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_171)(NimStringV2* result, NU64 x);
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_71)(NimStringV2* result, NU64 x);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, addChars__stdZprivateZdigitsutils_112)(NimStringV2* result, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x, NI start, NI n);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE NIM_CONST tyArray__38Z69amCaoywES5tRmClBSw digits100__stdZprivateZdigitsutils_2 = {48,
48,
48,
49,
48,
50,
48,
51,
48,
52,
48,
53,
48,
54,
48,
55,
48,
56,
48,
57,
49,
48,
49,
49,
49,
50,
49,
51,
49,
52,
49,
53,
49,
54,
49,
55,
49,
56,
49,
57,
50,
48,
50,
49,
50,
50,
50,
51,
50,
52,
50,
53,
50,
54,
50,
55,
50,
56,
50,
57,
51,
48,
51,
49,
51,
50,
51,
51,
51,
52,
51,
53,
51,
54,
51,
55,
51,
56,
51,
57,
52,
48,
52,
49,
52,
50,
52,
51,
52,
52,
52,
53,
52,
54,
52,
55,
52,
56,
52,
57,
53,
48,
53,
49,
53,
50,
53,
51,
53,
52,
53,
53,
53,
54,
53,
55,
53,
56,
53,
57,
54,
48,
54,
49,
54,
50,
54,
51,
54,
52,
54,
53,
54,
54,
54,
55,
54,
56,
54,
57,
55,
48,
55,
49,
55,
50,
55,
51,
55,
52,
55,
53,
55,
54,
55,
55,
55,
56,
55,
57,
56,
48,
56,
49,
56,
50,
56,
51,
56,
52,
56,
53,
56,
54,
56,
55,
56,
56,
56,
57,
57,
48,
57,
49,
57,
50,
57,
51,
57,
52,
57,
53,
57,
54,
57,
55,
57,
56,
57,
57}
;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NIM_BOOL nimInErrorMode__system_4240;
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_2330(s);
	}
	LA5_: ;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
static N_INLINE(void, addChars__stdZprivateZdigitsutils_112)(NimStringV2* result, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x, NI start, NI n) {
	NI old;
	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_7;
	nimfr_("addChars", "/usr/lib/nim/std/private/digitsutils.nim");
{	nimln_(43, "/usr/lib/nim/std/private/digitsutils.nim");
	old = (*result).len;
	nimln_(44, "/usr/lib/nim/std/private/digitsutils.nim");
	if (nimAddInt(old, n, &TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) < ((NI) 0) || ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	setLengthStrV2((&(*result)), ((NI) ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7))));
	nimln_(52, "/usr/lib/nim/std/private/digitsutils.nim");
	if (old < 0 || old >= (*result).len){ raiseIndexError2(old,(*result).len-1); goto BeforeRet_;
}
	if ((NU)(start) > (NU)(23)){ raiseIndexError2(start, 23); goto BeforeRet_;
}
	if ((n) < ((NI) 0) || (n) > ((NI) 2147483647)){ raiseRangeErrorI(n, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	copyMem__system_1709(((void*) ((&(*result).p->data[old]))), ((void*) ((&x[(start)- 0]))), ((NI) (n)));
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_71)(NimStringV2* result, NU64 x) {
	tyArray__PbS9a6gkxCuxWEnFq4lOU9aw tmp;
	NU64 num;
	NI next;
	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_8;
NIM_BOOL* nimErr_;
	nimfr_("addIntImpl", "/usr/lib/nim/std/private/digitsutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(59, "/usr/lib/nim/std/private/digitsutils.nim");
	num = x;
	nimln_(60, "/usr/lib/nim/std/private/digitsutils.nim");
	next = ((NI) 23);
	{
		nimln_(63, "/usr/lib/nim/std/private/digitsutils.nim");
		while (1) {
			NU64 originNum;
			NU64 index;
			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_3;
			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_4;
			if (!((NU64)(100ULL) <= (NU64)(num))) goto LA2;
			nimln_(64, "/usr/lib/nim/std/private/digitsutils.nim");
			originNum = num;
			nimln_(65, "/usr/lib/nim/std/private/digitsutils.nim");
			num = (NU64)((NU64)(num) / (NU64)(100ULL));
			nimln_(66, "/usr/lib/nim/std/private/digitsutils.nim");
			index = (NU64)((NU64)((NU64)((NU64)(originNum) - (NU64)((NU64)((NU64)(num) * (NU64)(100ULL))))) << (NU64)(((NI) 1)));
			if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); goto BeforeRet_;
}
			nimln_(67, "/usr/lib/nim/std/private/digitsutils.nim");
			if ((NU)((NU64)((NU64)(index) + (NU64)(1ULL))) > (NU)(199)){ raiseIndexError2((NU64)((NU64)(index) + (NU64)(1ULL)), 199); goto BeforeRet_;
}
			tmp[(next)- 0] = digits100__stdZprivateZdigitsutils_2[((NU64)((NU64)(index) + (NU64)(1ULL)))- 0];
			nimln_(68, "/usr/lib/nim/std/private/digitsutils.nim");
			if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_3)) { raiseOverflow(); goto BeforeRet_;
};
			if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3), 23); goto BeforeRet_;
}
			if ((NU)(index) > (NU)(199)){ raiseIndexError2(index, 199); goto BeforeRet_;
}
			tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3))- 0] = digits100__stdZprivateZdigitsutils_2[(index)- 0];
			nimln_(69, "/usr/lib/nim/std/private/digitsutils.nim");
			if (nimSubInt(next, ((NI) 2), &TM__J7BLF9cgvwzEso7aEL9cCOKw_4)) { raiseOverflow(); goto BeforeRet_;
};
			next = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_4);
		} LA2: ;
	}
	nimln_(72, "/usr/lib/nim/std/private/digitsutils.nim");
	{
		if (!((NU64)(num) < (NU64)(10ULL))) goto LA5_;
		if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); goto BeforeRet_;
}
		nimln_(73, "/usr/lib/nim/std/private/digitsutils.nim");
		if ((NU64)((NU64)(48ULL) + (NU64)(num)) > (NU64)(((NI) 255))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
}
		tmp[(next)- 0] = ((NIM_CHAR) (((NI) ((NU64)((NU64)(48ULL) + (NU64)(num))))));
	}
	goto LA3_;
	LA5_: ;
	{
		NU64 index_2;
		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_5;
		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_6;
		nimln_(75, "/usr/lib/nim/std/private/digitsutils.nim");
		index_2 = (NU64)((NU64)(num) * (NU64)(2ULL));
		if ((NU)(next) > (NU)(23)){ raiseIndexError2(next, 23); goto BeforeRet_;
}
		nimln_(76, "/usr/lib/nim/std/private/digitsutils.nim");
		if ((NU)((NU64)((NU64)(index_2) + (NU64)(1ULL))) > (NU)(199)){ raiseIndexError2((NU64)((NU64)(index_2) + (NU64)(1ULL)), 199); goto BeforeRet_;
}
		tmp[(next)- 0] = digits100__stdZprivateZdigitsutils_2[((NU64)((NU64)(index_2) + (NU64)(1ULL)))- 0];
		nimln_(77, "/usr/lib/nim/std/private/digitsutils.nim");
		if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) { raiseOverflow(); goto BeforeRet_;
};
		if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5), 23); goto BeforeRet_;
}
		if ((NU)(index_2) > (NU)(199)){ raiseIndexError2(index_2, 199); goto BeforeRet_;
}
		tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5))- 0] = digits100__stdZprivateZdigitsutils_2[(index_2)- 0];
		nimln_(78, "/usr/lib/nim/std/private/digitsutils.nim");
		if (nimSubInt(next, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_6)) { raiseOverflow(); goto BeforeRet_;
};
		next = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_6);
	}
	LA3_: ;
	nimln_(79, "/usr/lib/nim/std/private/digitsutils.nim");
	if (nimSubInt(((NI) 24), next, &TM__J7BLF9cgvwzEso7aEL9cCOKw_8)) { raiseOverflow(); goto BeforeRet_;
};
	addChars__stdZprivateZdigitsutils_112(result, tmp, next, (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_8));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_171)(NimStringV2* result, NU64 x) {
NIM_BOOL* nimErr_;
	nimfr_("addInt", "/usr/lib/nim/std/private/digitsutils.nim");
{nimErr_ = nimErrorFlag();
	nimln_(87, "/usr/lib/nim/std/private/digitsutils.nim");
	addIntImpl__stdZprivateZdigitsutils_71(result, x);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_174)(NimStringV2* result, NI64 x) {
	NU64 numX60gensym3_;
	nimfr_("addInt", "/usr/lib/nim/std/private/digitsutils.nim");
{	numX60gensym3_ = (NU64)0;
	nimln_(99, "/usr/lib/nim/std/private/digitsutils.nim");
	{
		NI baseX60gensym3_;
		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_2;
		if (!(x < IL64(0))) goto LA3_;
		nimln_(100, "/usr/lib/nim/std/private/digitsutils.nim");
		{
			if (!(x == (IL64(-9223372036854775807) - IL64(1)))) goto LA7_;
			nimln_(101, "/usr/lib/nim/std/private/digitsutils.nim");
			numX60gensym3_ = ((NU64) (x));
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(103, "/usr/lib/nim/std/private/digitsutils.nim");
			if (x == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;
}
			numX60gensym3_ = ((NU64) (-(x)));
		}
		LA5_: ;
		nimln_(104, "/usr/lib/nim/std/private/digitsutils.nim");
		baseX60gensym3_ = (*result).len;
		nimln_(105, "/usr/lib/nim/std/private/digitsutils.nim");
		if (nimAddInt(baseX60gensym3_, ((NI) 1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) < ((NI) 0) || ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		setLengthStrV2((&(*result)), ((NI) ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2))));
		if (baseX60gensym3_ < 0 || baseX60gensym3_ >= (*result).len){ raiseIndexError2(baseX60gensym3_,(*result).len-1); goto BeforeRet_;
}
		nimPrepareStrMutationV2((&(*result)));
		nimln_(106, "/usr/lib/nim/std/private/digitsutils.nim");
		(*result).p->data[baseX60gensym3_] = 45;
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(108, "/usr/lib/nim/std/private/digitsutils.nim");
		numX60gensym3_ = ((NU64) (x));
	}
	LA1_: ;
	nimln_(114, "/usr/lib/nim/std/private/digitsutils.nim");
	addInt__stdZprivateZdigitsutils_171(result, numX60gensym3_);
	}BeforeRet_: ;
	popFrame();
}
