/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s.nimble@spkgs@snico-0.4.9@snico@sringbuffer.nim.c.o /home/manea/Documents/Connect4x4/tmp/@m..@s..@s..@s.nimble@spkgs@snico-0.4.9@snico@sringbuffer.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw;
typedef struct tySequence__JVUCJoIAFxiGphM572dT1g tySequence__JVUCJoIAFxiGphM572dT1g;
typedef struct tySequence__JVUCJoIAFxiGphM572dT1g_Content tySequence__JVUCJoIAFxiGphM572dT1g_Content;
typedef struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ;
typedef struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg;
typedef struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg tySequence__BPX0nQ9a18neVv9cyL9bIVAbg;
typedef struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q;
struct tySequence__JVUCJoIAFxiGphM572dT1g {
  NI len; tySequence__JVUCJoIAFxiGphM572dT1g_Content* p;
};
struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw {
tySequence__JVUCJoIAFxiGphM572dT1g data;
NI head;
NI tail;
NI size;
NI length;
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA {
tySequence__4Xyxy0Om14N6K1l5e9bUPSQ data;
NI head;
NI tail;
NI size;
NI length;
};
struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg {
  NI len; tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content* p;
};
struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg {
tySequence__BPX0nQ9a18neVv9cyL9bIVAbg data;
NI head;
NI tail;
NI size;
NI length;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
NI rootIdx;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw {
NimStringV2 name;
tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q start;
NI64 time;
NI count;
tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw* parent;
tySequence__JVUCJoIAFxiGphM572dT1g children;
};


#ifndef tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
#define tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
struct tySequence__JVUCJoIAFxiGphM572dT1g_Content { NI cap; tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
#define tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
#define tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content_PP
#define tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content_PP
struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content { NI cap; tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
#define tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
struct tySequence__JVUCJoIAFxiGphM572dT1g_Content { NI cap; tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw data[SEQ_DECL_SIZE];};
#endif

      static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__JVUCJoIAFxiGphM572dT1g, newSeq__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2902)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_168)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest);
N_LIB_PRIVATE N_NIMCALL(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ, newSeq__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6497)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1395)(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ** dest, tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* src, NIM_BOOL cyclic);
N_LIB_PRIVATE N_NIMCALL(NI, idx__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1119)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i);
N_LIB_PRIVATE N_NIMCALL(NI, floorMod__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1124)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_300)(tySequence__BPX0nQ9a18neVv9cyL9bIVAbg* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p, TNimTypeV2* desc);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3164)(NIM_BOOL isDestroyAction, tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* s, TNimTypeV2* desc);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1405)(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3014)(tySequence__JVUCJoIAFxiGphM572dT1g* dest);
extern TNimTypeV2 NTIv2__s5bbV5gDnl2gfvzhWCmDXQ_;
extern NIM_BOOL nimInErrorMode__system_4240;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw, initRingBuffer__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2893)(NI length) {
	tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw result;
	tySequence__JVUCJoIAFxiGphM572dT1g s;
	NI colontmpD_;
	tySequence__JVUCJoIAFxiGphM572dT1g blitTmp;
	nimfr_("initRingBuffer", "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw));
	s.len = 0; s.p = NIM_NIL;
	colontmpD_ = (NI)0;
	nimln_(10, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	if ((length) < ((NI) 0) || (length) > ((NI) 2147483647)){ raiseRangeErrorI(length, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	s = newSeq__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2902(((NI) (length)));
	nimln_(11, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw));
	blitTmp = s;
	result.data = blitTmp;
	result.head = ((NI) 0);
	result.tail = ((NI) -1);
	result.size = ((NI) 0);
	colontmpD_ = length;
	result.length = colontmpD_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6590)(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA* dest, tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA src) {
	if ((*dest).data.p != src.data.p) {	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_168((&(*dest).data));
	}
(*dest).data.len = src.data.len; (*dest).data.p = src.data.p;
	(*dest).head = src.head;
	(*dest).tail = src.tail;
	(*dest).size = src.size;
	(*dest).length = src.length;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA, initRingBuffer__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6575)(NI length) {
	tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA result;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ s;
	NI colontmpD_;
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ blitTmp;
	nimfr_("initRingBuffer", "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
{	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA));
	s.len = 0; s.p = NIM_NIL;
	colontmpD_ = (NI)0;
	nimln_(10, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	if ((length) < ((NI) 0) || (length) > ((NI) 2147483647)){ raiseRangeErrorI(length, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	s = newSeq__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6497(((NI) (length)));
	nimln_(11, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA));
	blitTmp = s;
	result.data = blitTmp;
	result.head = ((NI) 0);
	result.tail = ((NI) -1);
	result.size = ((NI) 0);
	colontmpD_ = length;
	result.length = colontmpD_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_6454)(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA* b, NF32 data) {
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_2;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_3;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_4;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_5;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_6;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_7;
	NI TM__LhSvWNjLDmsc0z4j9bkjpPA_8;
	nimfr_("add", "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
{	nimln_(17, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	if (nimAddInt((*b).tail, ((NI) 1), &TM__LhSvWNjLDmsc0z4j9bkjpPA_2)) { raiseOverflow(); goto BeforeRet_;
};
	if ((*b).length == 0){ raiseDivByZero(); goto BeforeRet_;
}
	if (nimModInt((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_2), (*b).length, &TM__LhSvWNjLDmsc0z4j9bkjpPA_3)) { raiseOverflow(); goto BeforeRet_;
};
	(*b).tail = (NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_3);
	if ((*b).tail < 0 || (*b).tail >= (*b).data.len){ raiseIndexError2((*b).tail,(*b).data.len-1); goto BeforeRet_;
}
	nimln_(28, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	(*b).data.p->data[(*b).tail] = data;
	nimln_(29, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	if (nimAddInt((*b).size, ((NI) 1), &TM__LhSvWNjLDmsc0z4j9bkjpPA_4)) { raiseOverflow(); goto BeforeRet_;
};
	(*b).size = (((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_4) <= (*b).length) ? (NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_4) : (*b).length);
	nimln_(14, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	if (nimAddInt((*b).length, (*b).tail, &TM__LhSvWNjLDmsc0z4j9bkjpPA_5)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimSubInt((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_5), (*b).size, &TM__LhSvWNjLDmsc0z4j9bkjpPA_6)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimAddInt((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_6), ((NI) 1), &TM__LhSvWNjLDmsc0z4j9bkjpPA_7)) { raiseOverflow(); goto BeforeRet_;
};
	if ((*b).length == 0){ raiseDivByZero(); goto BeforeRet_;
}
	if (nimModInt((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_7), (*b).length, &TM__LhSvWNjLDmsc0z4j9bkjpPA_8)) { raiseOverflow(); goto BeforeRet_;
};
	(*b).head = (NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_8);
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI, idx__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1119)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
NIM_BOOL* nimErr_;
	nimfr_("idx", "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(33, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	{
		NI TM__LhSvWNjLDmsc0z4j9bkjpPA_9;
		NI TM__LhSvWNjLDmsc0z4j9bkjpPA_10;
		if (!(i < ((NI) 0))) goto LA3_;
		nimln_(36, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
		if (nimAddInt(i, ((NI) 1), &TM__LhSvWNjLDmsc0z4j9bkjpPA_9)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt(b.tail, (NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_9), &TM__LhSvWNjLDmsc0z4j9bkjpPA_10)) { raiseOverflow(); goto BeforeRet_;
};
		colontmpD_ = floorMod__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1124((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_10), b.length);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__LhSvWNjLDmsc0z4j9bkjpPA_11;
		nimln_(38, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
		if (nimAddInt(i, b.head, &TM__LhSvWNjLDmsc0z4j9bkjpPA_11)) { raiseOverflow(); goto BeforeRet_;
};
		colontmpD__2 = floorMod__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1124((NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_11), b.length);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ*, X5BX5D___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1109)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i) {
	tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* result;
	NI T1_;
NIM_BOOL* nimErr_;
	nimfr_("[]", "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimln_(328, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	nimln_(41, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	T1_ = (NI)0;
	T1_ = idx__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1119(b, i);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (T1_ < 0 || T1_ >= b.data.len){ raiseIndexError2(T1_,b.data.len-1); goto BeforeRet_;
}
	nimln_(328, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqcopy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1395(&result, b.data.p->data[T1_], NIM_FALSE);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	nimfr_("-%", "/usr/lib/nim/system/arithmetics.nim");
	result = (NI)0;
	nimln_(414, "/usr/lib/nim/system/arithmetics.nim");
	nimln_(418, "/usr/lib/nim/system/arithmetics.nim");
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p, TNimTypeV2* desc) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("nimDecRefIsLastCyclicStatic", "/usr/lib/nim/system/orc.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimln_(486, "/usr/lib/nim/system/orc.nim");
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		nimln_(487, "/usr/lib/nim/system/orc.nim");
		nimln_(63, "/usr/lib/nim/system/arc.nim");
		T5_ = (NI)0;
		T5_ = minuspercent___system_716(((NI) (ptrdiff_t) (p)), ((NI) 8));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		nimln_(488, "/usr/lib/nim/system/orc.nim");
		{
			if (!((NI)((*cell).rc & ((NI) -16)) == ((NI) 0))) goto LA8_;
			nimln_(489, "/usr/lib/nim/system/orc.nim");
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__LhSvWNjLDmsc0z4j9bkjpPA_12;
			nimln_(492, "/usr/lib/nim/system/orc.nim");
			if (nimSubInt((*cell).rc, ((NI) 16), &TM__LhSvWNjLDmsc0z4j9bkjpPA_12)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__LhSvWNjLDmsc0z4j9bkjpPA_12);
		}
		LA6_: ;
		nimln_(494, "/usr/lib/nim/system/orc.nim");
		rememberCycle__system_3164(result, cell, desc);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_300)(tySequence__BPX0nQ9a18neVv9cyL9bIVAbg* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLastCyclicStatic((*dest).p->data[colontmp_], (&NTIv2__s5bbV5gDnl2gfvzhWCmDXQ_));
				if (!T6_) goto LA7_;
				eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1405((*dest).p->data[colontmp_]);
				nimRawDispose((*dest).p->data[colontmp_], ((NI) 4));
			}
			LA7_: ;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_288)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg* dest) {
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_300((&(*dest).data));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3051)(tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw* dest) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3014((&(*dest).data));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
