/* Generated by Nim Compiler v1.6.10 */
/* Compiled for: Linux, wasm32, clang */
/* Command for C compiler:
   emcc -c -w -ferror-limit=3   -I/usr/lib/nim -I/home/manea/Documents/Connect4x4/src -o /home/manea/Documents/Connect4x4/tmp/@mmain.nim.c.o /home/manea/Documents/Connect4x4/tmp/@mmain.nim.c */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ;
typedef struct tyObject_Channel__lbLEAhZwVPtEttYh9bI9aHHA tyObject_Channel__lbLEAhZwVPtEttYh9bI9aHHA;
typedef struct tyObject_SfxBuffercolonObjectType___HlVeWpaTGrNpJeGP1t2tJQ tyObject_SfxBuffercolonObjectType___HlVeWpaTGrNpJeGP1t2tJQ;
typedef struct tyObject_VorbisObj__sF9aEMy2YfGZ8T5yoAoJBNg tyObject_VorbisObj__sF9aEMy2YfGZ8T5yoAoJBNg;
typedef struct tyTuple__hlJGhatkI8LFyY55THZx0Q tyTuple__hlJGhatkI8LFyY55THZx0Q;
typedef struct tyTuple__c9coqeWOmFSekVKFlKv7pXg tyTuple__c9coqeWOmFSekVKFlKv7pXg;
typedef struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content;
typedef struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg;
typedef struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg tySequence__BPX0nQ9a18neVv9cyL9bIVAbg;
typedef struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content;
typedef struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA;
typedef struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw;
typedef struct tySequence__JVUCJoIAFxiGphM572dT1g tySequence__JVUCJoIAFxiGphM572dT1g;
typedef struct tySequence__JVUCJoIAFxiGphM572dT1g_Content tySequence__JVUCJoIAFxiGphM572dT1g_Content;
typedef struct tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g tySequence__pcXSChh0J6OCdCDPpBK9b1g;
typedef struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content;
typedef struct tyObject_Tilemap__Cb7kErRc9a4SI23raoiNXvg tyObject_Tilemap__Cb7kErRc9a4SI23raoiNXvg;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content tySequence__qwqHTkRvwhrRyENtudHQ7g_Content;
typedef struct tySequence__QMZmXMN9bwY3vA8Sx4L2V3g tySequence__QMZmXMN9bwY3vA8Sx4L2V3g;
typedef struct tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content;
typedef struct tyObject_NicoControllercolonObjectType___KhzrHn1wfPdYSFPNFSFvIQ tyObject_NicoControllercolonObjectType___KhzrHn1wfPdYSFPNFSFvIQ;
typedef struct tySequence__MS9aJfh6Fd7IofAvchdiznA tySequence__MS9aJfh6Fd7IofAvchdiznA;
typedef struct tySequence__MS9aJfh6Fd7IofAvchdiznA_Content tySequence__MS9aJfh6Fd7IofAvchdiznA_Content;
typedef struct tySequence__mEQvKVWOkDYIN3NI9ayITqg tySequence__mEQvKVWOkDYIN3NI9ayITqg;
typedef struct tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg tySequence__EtvC1a2T849cB0SNWHj6Fbg;
typedef struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content;
typedef struct tySequence__pQdESQwIdfY7p9bK9cdq2lzQ tySequence__pQdESQwIdfY7p9bK9cdq2lzQ;
typedef struct tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content;
typedef struct tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA;
typedef struct tySequence__P9cgLJz9cK9czFckaAibTALJQ tySequence__P9cgLJz9cK9czFckaAibTALJQ;
typedef struct tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content;
typedef struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw;
typedef struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q;
typedef struct tyObject_Event__fw14ob1dmkh8dqzKWW9b4Kg tyObject_Event__fw14ob1dmkh8dqzKWW9b4Kg;
typedef struct tyObject_Touch__UdJIioDvIawxRuaaz9c4i1w tyObject_Touch__UdJIioDvIawxRuaaz9c4i1w;
typedef struct tyTuple__3gBPj2HWazk1I9akTDe3bAg tyTuple__3gBPj2HWazk1I9akTDe3bAg;
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NF32 dt, void* ClE_0);
void* ClE_0;
} tyProc__y9aUXu4JGz72YDIZVWUrK5w;
typedef N_CLOSURE_PTR(void, TM__fG1ut6j0ImqM9bibVlGRHfA_9) (void* ClE_0);
typedef NU8 tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg;
typedef N_CLOSURE_PTR(void, TM__fG1ut6j0ImqM9bibVlGRHfA_10) (NF32 dt, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__fG1ut6j0ImqM9bibVlGRHfA_13) (void* ClE_0);
typedef NU8 tyEnum_ChannelKind__7k9cdR0vQKg8iCy1452Ot6A;
typedef struct {
N_NIMCALL_PTR(NF32, ClP_0) (NF32 input, void* ClE_0);
void* ClE_0;
} tyProc__Gpfb5rC9cmDwspzoCJcvT9cg;
typedef NF32 tyArray__AH8zxXMFV9aJOtXCzmguz0Q[4096];
typedef tyArray__AH8zxXMFV9aJOtXCzmguz0Q tyArray__MLIYHgc9b3aVhhy7Dt9bea6g[2];
typedef NU8 tyEnum_SynthShape__qgoPiEcl9ae3PKHp1XZJIdg;
struct tyTuple__c9coqeWOmFSekVKFlKv7pXg {
NU8 Field0;
NU8 Field1;
tyEnum_SynthShape__qgoPiEcl9ae3PKHp1XZJIdg Field2;
};
typedef tyTuple__c9coqeWOmFSekVKFlKv7pXg tyArray__HPRyIsjQTV9aRpPxmTkQCZA[32];
struct tyTuple__hlJGhatkI8LFyY55THZx0Q {
NU8 Field0;
tyArray__HPRyIsjQTV9aRpPxmTkQCZA Field1;
NU8 Field2;
NU8 Field3;
};
typedef NU8 tyArray__vEOa9c5qaE9ajWxR5R4zwfQg[32];
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  NI len; tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content* p;
};
struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA {
tySequence__4Xyxy0Om14N6K1l5e9bUPSQ data;
NI head;
NI tail;
NI size;
NI length;
};
struct tyObject_Channel__lbLEAhZwVPtEttYh9bI9aHHA {
tyEnum_ChannelKind__7k9cdR0vQKg8iCy1452Ot6A kind;
tyObject_SfxBuffercolonObjectType___HlVeWpaTGrNpJeGP1t2tJQ* buffer;
tyProc__Gpfb5rC9cmDwspzoCJcvT9cg callback;
NIM_BOOL callbackStereo;
tyObject_VorbisObj__sF9aEMy2YfGZ8T5yoAoJBNg* musicFile;
NI musicIndex;
NI musicBuffer;
NIM_BOOL musicStereo;
NF32 musicSampleRate;
tyArray__MLIYHgc9b3aVhhy7Dt9bea6g musicBuffers;
NI loop;
NF32 phase;
NF32 freq;
NF32 basefreq;
NF32 targetFreq;
NF32 width;
NF32 pan;
tyEnum_SynthShape__qgoPiEcl9ae3PKHp1XZJIdg shape;
NF32 gain;
tyTuple__hlJGhatkI8LFyY55THZx0Q synthData;
NI synthDataIndex;
NI init;
NI env;
NF32 envValue;
NI envPhase;
NI length;
NI vibspeed;
NI vibamount;
NI glide;
NI pchange;
NIM_BOOL trigger;
NU32 lfsr;
NU32 lfsr2;
NI nextClick;
NF32 outvalue;
NF32 priority;
tyArray__vEOa9c5qaE9ajWxR5R4zwfQg wavData;
tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA outputBuffer;
};
typedef tyObject_Channel__lbLEAhZwVPtEttYh9bI9aHHA tyArray__cKa1HEw74ddZZVmp1eKlNw[16];
typedef NimStringV2 tyArray__TLUjAhnMfzBtYkb49czB0KA[64];
typedef tyObject_SfxBuffercolonObjectType___HlVeWpaTGrNpJeGP1t2tJQ* tyArray__GzR9br8iqIdyqWIH0oXqxWw[64];
struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg {
  NI len; tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content* p;
};
struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg {
tySequence__BPX0nQ9a18neVv9cyL9bIVAbg data;
NI head;
NI tail;
NI size;
NI length;
};
struct tySequence__JVUCJoIAFxiGphM572dT1g {
  NI len; tySequence__JVUCJoIAFxiGphM572dT1g_Content* p;
};
struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw {
tySequence__JVUCJoIAFxiGphM572dT1g data;
NI head;
NI tail;
NI size;
NI length;
};
typedef tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ* tyArray__rwmHpsjkpPrR1BjtQ5RhXA[16];
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g {
  NI len; tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content* p;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NimStringV2 text, void* ClE_0);
void* ClE_0;
} tyProc__Hx0b1P9bD01T9bF9aUnykFuyA;
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  NI len; tySequence__qwqHTkRvwhrRyENtudHQ7g_Content* p;
};
struct tyObject_Tilemap__Cb7kErRc9a4SI23raoiNXvg {
tySequence__qwqHTkRvwhrRyENtudHQ7g data;
NI w;
NI h;
NIM_BOOL hex;
NI hexOffset;
NI tw;
NI th;
};
typedef tyObject_Tilemap__Cb7kErRc9a4SI23raoiNXvg tyArray__JC9bUAldadIzKs0FGdE3WRw[16];
typedef tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* tyArray__bpxTuYCyERko8Fktv7LjkA[16];
struct tySequence__QMZmXMN9bwY3vA8Sx4L2V3g {
  NI len; tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_NicoControllercolonObjectType___KhzrHn1wfPdYSFPNFSFvIQ* controller, void* ClE_0);
void* ClE_0;
} tyProc__deO4ZRZZip4KrxVc7H3fgw;
struct tySequence__MS9aJfh6Fd7IofAvchdiznA {
  NI len; tySequence__MS9aJfh6Fd7IofAvchdiznA_Content* p;
};
typedef tySequence__MS9aJfh6Fd7IofAvchdiznA tyArray__qmqi35rnFQ5DnGnp9cFW1qQ[16];
struct tySequence__mEQvKVWOkDYIN3NI9ayITqg {
  NI len; tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content* p;
};
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg {
  NI len; tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content* p;
};
struct tySequence__pQdESQwIdfY7p9bK9cdq2lzQ {
  NI len; tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content* p;
};
struct tySequence__P9cgLJz9cK9czFckaAibTALJQ {
  NI len; tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content* p;
};
struct tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA {
tySequence__P9cgLJz9cK9czFckaAibTALJQ data;
NI counter;
};


#ifndef tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
#define tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content_PP
#define tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content_PP
struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg_Content { NI cap; tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
#define tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content_PP
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ_Content { NI cap; NF32 data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw {
NimStringV2 name;
tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q start;
NI64 time;
NI count;
tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw* parent;
tySequence__JVUCJoIAFxiGphM572dT1g children;
};


#ifndef tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
#define tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
struct tySequence__JVUCJoIAFxiGphM572dT1g_Content { NI cap; tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw data[SEQ_DECL_SIZE];};
#endif

      typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NI x, NI y, void* ClE_0);
void* ClE_0;
} tyProc__yZbvgbtLeGIhzIA9bifjdPw;


#ifndef tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content_PP
#define tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content_PP
struct tySequence__pcXSChh0J6OCdCDPpBK9b1g_Content { NI cap; tyProc__yZbvgbtLeGIhzIA9bifjdPw data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
#define tySequence__qwqHTkRvwhrRyENtudHQ7g_Content_PP
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content_PP
#define tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content_PP
struct tySequence__QMZmXMN9bwY3vA8Sx4L2V3g_Content { NI cap; tyObject_NicoControllercolonObjectType___KhzrHn1wfPdYSFPNFSFvIQ* data[SEQ_DECL_SIZE];};
#endif

      typedef NI32 tyEnum_Scancode__uJPSzpLR9c8rQv9cq8H9bgOVg;


#ifndef tySequence__MS9aJfh6Fd7IofAvchdiznA_Content_PP
#define tySequence__MS9aJfh6Fd7IofAvchdiznA_Content_PP
struct tySequence__MS9aJfh6Fd7IofAvchdiznA_Content { NI cap; tyEnum_Scancode__uJPSzpLR9c8rQv9cq8H9bgOVg data[SEQ_DECL_SIZE];};
#endif

      typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (tyObject_Event__fw14ob1dmkh8dqzKWW9b4Kg* e, void* ClE_0);
void* ClE_0;
} tyProc__Jp8pG9cSgHrgSQB2tshrEyg;


#ifndef tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content_PP
#define tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content_PP
struct tySequence__mEQvKVWOkDYIN3NI9ayITqg_Content { NI cap; tyProc__Jp8pG9cSgHrgSQB2tshrEyg data[SEQ_DECL_SIZE];};
#endif

      typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (NI sym, NU16 mods, NI scancode, NIM_BOOL down, void* ClE_0);
void* ClE_0;
} tyProc__SR0j0ClEYDvwlJHrgLh3cQ;


#ifndef tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content_PP
#define tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content_PP
struct tySequence__EtvC1a2T849cB0SNWHj6Fbg_Content { NI cap; tyProc__SR0j0ClEYDvwlJHrgLh3cQ data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_TouchState__P6WNaIEkSOmee5vWR6wWgA;
struct tyObject_Touch__UdJIioDvIawxRuaaz9c4i1w {
NI id;
NI x;
NI y;
NF32 sx;
NF32 sy;
NF32 xrel;
NF32 yrel;
NF32 xrelraw;
NF32 yrelraw;
tyEnum_TouchState__P6WNaIEkSOmee5vWR6wWgA state;
};


#ifndef tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content_PP
#define tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content_PP
struct tySequence__pQdESQwIdfY7p9bK9cdq2lzQ_Content { NI cap; tyObject_Touch__UdJIioDvIawxRuaaz9c4i1w data[SEQ_DECL_SIZE];};
#endif

      typedef NI32 tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ;
struct tyTuple__3gBPj2HWazk1I9akTDe3bAg {
NI Field0;
tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ Field1;
NU32 Field2;
};


#ifndef tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content_PP
#define tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content_PP
struct tySequence__P9cgLJz9cK9czFckaAibTALJQ_Content { NI cap; tyTuple__3gBPj2HWazk1I9akTDe3bAg data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
#define tySequence__JVUCJoIAFxiGphM572dT1g_Content_PP
struct tySequence__JVUCJoIAFxiGphM572dT1g_Content { NI cap; tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw data[SEQ_DECL_SIZE];};
#endif

      typedef NU8 tyEnum_EventKind__pqgoSZIiVa02aB0FKUaUPw;
struct tyObject_Event__fw14ob1dmkh8dqzKWW9b4Kg {
tyEnum_EventKind__pqgoSZIiVa02aB0FKUaUPw kind;
NU8 button;
NI x;
NI y;
NF32 xrel;
NF32 yrel;
tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ keycode;
tyEnum_Scancode__uJPSzpLR9c8rQv9cq8H9bgOVg scancode;
NU16 mods;
NU8 clicks;
NI repeat;
NI ywheel;
NimStringV2 text;
NU8 which;
};
N_LIB_PRIVATE N_NIMCALL(void, init__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_444)(NimStringV2 org, NimStringV2 app);
N_LIB_PRIVATE N_NIMCALL(void, createWindow__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_6806)(NimStringV2 title, NI w, NI h, NI scale, NIM_BOOL fullscreen);
N_LIB_PRIVATE N_NIMCALL(void, run__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_6899)(tyProc__HzVCwACFYM9cx9aV62PdjtuA init, tyProc__y9aUXu4JGz72YDIZVWUrK5w update, tyProc__HzVCwACFYM9cx9aV62PdjtuA draw);
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_5)(void);
N_LIB_PRIVATE N_NIMCALL(void, loadFont__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_4982)(NI index, NimStringV2 filename);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4411)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_6)(NF32 dt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, btn__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_190)(tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg b);
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_8)(void);
N_LIB_PRIVATE N_NIMCALL(void, cls__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_1502)(NI c);
N_LIB_PRIVATE N_NIMCALL(void, setColor__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_59)(NI colId);
N_LIB_PRIVATE N_NIMCALL(void, printc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_40)(NimStringV2 text, NI32 x, NI32 y, NI32 scale);
N_LIB_PRIVATE N_NIMCALL(int, toCint__OOZOOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1392)(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_498)(tyObject_Channel__lbLEAhZwVPtEttYh9bI9aHHA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_474)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_426)(tyObject_SfxBuffercolonObjectType___HlVeWpaTGrNpJeGP1t2tJQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_288)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsecfg_740)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_168)(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3051)(tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2387)(tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2240)(tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2098)(tySequence__pcXSChh0J6OCdCDPpBK9b1g* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2078)(tyProc__Hx0b1P9bD01T9bF9aUnykFuyA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1088)(tyProc__HzVCwACFYM9cx9aV62PdjtuA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2058)(tyProc__y9aUXu4JGz72YDIZVWUrK5w* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1926)(tyObject_Tilemap__Cb7kErRc9a4SI23raoiNXvg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1891)(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3263)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1754)(tySequence__QMZmXMN9bwY3vA8Sx4L2V3g* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1734)(tyProc__deO4ZRZZip4KrxVc7H3fgw* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1710)(tySequence__MS9aJfh6Fd7IofAvchdiznA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1250)(tySequence__mEQvKVWOkDYIN3NI9ayITqg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1108)(tySequence__EtvC1a2T849cB0SNWHj6Fbg* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_990)(tySequence__pQdESQwIdfY7p9bK9cdq2lzQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_270)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* dest);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatstimesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatscontrollerdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsstreamsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsrandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsosprocdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsparsecfgdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot2atsnimPNGatsnimzdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot2atsnimPNGdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsfontdatadotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__fG1ut6j0ImqM9bibVlGRHfA_2 = { 10 | NIM_STRLIT_FLAG, "tubbygames" };
static const NimStringV2 TM__fG1ut6j0ImqM9bibVlGRHfA_3 = {10, (NimStrPayload*)&TM__fG1ut6j0ImqM9bibVlGRHfA_2};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__fG1ut6j0ImqM9bibVlGRHfA_4 = { 10 | NIM_STRLIT_FLAG, "connect4x4" };
static const NimStringV2 TM__fG1ut6j0ImqM9bibVlGRHfA_5 = {10, (NimStrPayload*)&TM__fG1ut6j0ImqM9bibVlGRHfA_4};
static const NimStringV2 TM__fG1ut6j0ImqM9bibVlGRHfA_6 = {10, (NimStrPayload*)&TM__fG1ut6j0ImqM9bibVlGRHfA_4};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__fG1ut6j0ImqM9bibVlGRHfA_7 = { 8 | NIM_STRLIT_FLAG, "font.png" };
static const NimStringV2 TM__fG1ut6j0ImqM9bibVlGRHfA_8 = {8, (NimStrPayload*)&TM__fG1ut6j0ImqM9bibVlGRHfA_7};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__fG1ut6j0ImqM9bibVlGRHfA_11 = { 21 | NIM_STRLIT_FLAG, "welcome to connect4x4" };
static const NimStringV2 TM__fG1ut6j0ImqM9bibVlGRHfA_12 = {21, (NimStrPayload*)&TM__fG1ut6j0ImqM9bibVlGRHfA_11};
N_LIB_PRIVATE NIM_BOOL buttonDown__main_4 = NIM_FALSE;
extern NIM_BOOL nimInErrorMode__system_4240;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern TFrame* framePtr__system_3889;
extern NI screenWidth__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_822;
extern NI screenHeight__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_823;
extern tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* defaultFontSurface__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZfontdata_6;
extern tyArray__cKa1HEw74ddZZVmp1eKlNw audioChannels__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_167;
extern tyArray__TLUjAhnMfzBtYkb49czB0KA musicFileLibrary__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_165;
extern tyArray__GzR9br8iqIdyqWIH0oXqxWw sfxBufferLibrary__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_164;
extern tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg recordFrames__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_163;
extern tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* config__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_156;
extern tySequence__4Xyxy0Om14N6K1l5e9bUPSQ outputSamples__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_143;
extern tySequence__4Xyxy0Om14N6K1l5e9bUPSQ inputSamples__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_142;
extern tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw profileHistory__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3064;
extern tyObject_FontcolonObjectType___9cwRb4wyfcTtg2ayEpv8DDQ* currentFont__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_942;
extern tyArray__rwmHpsjkpPrR1BjtQ5RhXA fonts__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_941;
extern tySequence__pcXSChh0J6OCdCDPpBK9b1g resizeFuncs__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_940;
extern tyProc__Hx0b1P9bD01T9bF9aUnykFuyA textFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_939;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA drawFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_936;
extern tyProc__y9aUXu4JGz72YDIZVWUrK5w updateFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_934;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA initFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_930;
extern tyArray__JC9bUAldadIzKs0FGdE3WRw tilemaps__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_927;
extern tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* spritesheet__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_926;
extern tyArray__bpxTuYCyERko8Fktv7LjkA spritesheets__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_925;
extern NimStringV2 writePath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_923;
extern NimStringV2 assetPath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_922;
extern NimStringV2 basePath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_921;
extern tySequence__QMZmXMN9bwY3vA8Sx4L2V3g controllers__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_897;
extern tyProc__deO4ZRZZip4KrxVc7H3fgw controllerRemovedFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_896;
extern tyProc__deO4ZRZZip4KrxVc7H3fgw controllerAddedFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_893;
extern tyArray__qmqi35rnFQ5DnGnp9cFW1qQ keymap__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_890;
extern tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* stencilBuffer__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_790;
extern tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* swCanvas__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_789;
extern tySequence__mEQvKVWOkDYIN3NI9ayITqg eventListeners__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_785;
extern tySequence__EtvC1a2T849cB0SNWHj6Fbg keyListeners__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_780;
extern tyProc__HzVCwACFYM9cx9aV62PdjtuA audioTickCallback__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_771;
extern tySequence__pQdESQwIdfY7p9bK9cdq2lzQ touches__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_763;
extern tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA keysDown__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_191;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__system_4240);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__system_3889 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__system_3889).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__system_3889;
	framePtr__system_3889 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__system_4411();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_3889 = (*framePtr__system_3889).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_5)(void) {
NIM_BOOL* nimErr_;
	nimfr_("gameInit", "/home/manea/Documents/Connect4x4/src/main.nim");
{nimErr_ = nimErrorFlag();
	nimln_(9, "/home/manea/Documents/Connect4x4/src/main.nim");
	loadFont__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_4982(((NI) 0), TM__fG1ut6j0ImqM9bibVlGRHfA_8);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_6)(NF32 dt) {
	NIM_BOOL T1_;
NIM_BOOL* nimErr_;
	nimfr_("gameUpdate", "/home/manea/Documents/Connect4x4/src/main.nim");
{nimErr_ = nimErrorFlag();
	nimln_(12, "/home/manea/Documents/Connect4x4/src/main.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = btn__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_190(((tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg) 4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	buttonDown__main_4 = T1_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_8)(void) {
	NI colontmpD_;
	NI colontmpD__2;
	NI T1_;
	int T7_;
	int T8_;
NIM_BOOL* nimErr_;
	nimfr_("gameDraw", "/home/manea/Documents/Connect4x4/src/main.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimln_(15, "/home/manea/Documents/Connect4x4/src/main.nim");
	cls__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_1502(((NI) 0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(16, "/home/manea/Documents/Connect4x4/src/main.nim");
	T1_ = (NI)0;
	{
		if (!buttonDown__main_4) goto LA4_;
		colontmpD_ = ((NI) 7);
		T1_ = colontmpD_;
	}
	goto LA2_;
	LA4_: ;
	{
		colontmpD__2 = ((NI) 3);
		T1_ = colontmpD__2;
	}
	LA2_: ;
	setColor__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_59(T1_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(17, "/home/manea/Documents/Connect4x4/src/main.nim");
	T7_ = (int)0;
	T7_ = toCint__OOZOOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((NI)(screenWidth__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_822 / ((NI) 2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T8_ = (int)0;
	T8_ = toCint__OOZOOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((NI)(screenHeight__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_823 / ((NI) 2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	printc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_40(TM__fG1ut6j0ImqM9bibVlGRHfA_12, T7_, T8_, ((NI32) 1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsrandomdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsfontdatadotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_Init000();
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatssystemdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatstimesdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatscontrollerdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsstreamsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsosprocdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsusratslibatsnimatspureatsparsecfgdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot2atsnimPNGatsnimzdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot2atsnimPNGdotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_DatInit000();
	atmdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_DatInit000();
	PreMainInner();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	PreMain();
	NimMainInner();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T1_;
	tyProc__y9aUXu4JGz72YDIZVWUrK5w T2_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T3_;
NIM_BOOL* nimErr_;
	nimfr_("main", "/home/manea/Documents/Connect4x4/src/main.nim");
nimErr_ = nimErrorFlag();
	nimln_(19, "/home/manea/Documents/Connect4x4/src/main.nim");
	init__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_444(TM__fG1ut6j0ImqM9bibVlGRHfA_3, TM__fG1ut6j0ImqM9bibVlGRHfA_5);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(20, "/home/manea/Documents/Connect4x4/src/main.nim");
	createWindow__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_6806(TM__fG1ut6j0ImqM9bibVlGRHfA_6, ((NI) 128), ((NI) 128), ((NI) 4), NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(21, "/home/manea/Documents/Connect4x4/src/main.nim");
	nimZeroMem((void*)(&T1_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T1_.ClP_0 = ((TM__fG1ut6j0ImqM9bibVlGRHfA_9) (gameInit__main_5)); T1_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__y9aUXu4JGz72YDIZVWUrK5w));
	T2_.ClP_0 = ((TM__fG1ut6j0ImqM9bibVlGRHfA_10) (gameUpdate__main_6)); T2_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T3_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T3_.ClP_0 = ((TM__fG1ut6j0ImqM9bibVlGRHfA_13) (gameDraw__main_8)); T3_.ClE_0 = NIM_NIL;
	run__OOZOOZOOZOnimbleZpkgsZnico4548O52O57Znico_6899(T1_, T2_, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(328, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1392(&defaultFontSurface__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZfontdata_6);
	nimln_(194, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/sdl2.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_498(audioChannels__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_167);
	nimln_(191, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/sdl2.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_474(musicFileLibrary__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_165);
	nimln_(190, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/sdl2.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_426(sfxBufferLibrary__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_164);
	nimln_(188, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/sdl2.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_288((&recordFrames__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_163));
	nimln_(1824, "/usr/lib/nim/pure/collections/tables.nim");
	eqdestroy___pureZparsecfg_740(&config__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_156);
	nimln_(157, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/sdl2.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_168((&outputSamples__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_143));
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_168((&inputSamples__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_142));
	nimln_(11, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/ringbuffer.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3051((&profileHistory__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_3064));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(438, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2387(&currentFont__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_942);
	nimln_(437, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2240(fonts__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_941);
	nimln_(435, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2098((&resizeFuncs__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_940));
	nimln_(434, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2078((&textFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_939));
	nimln_(312, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1088((&drawFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_936));
	nimln_(432, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_2058((&updateFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_934));
	nimln_(312, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1088((&initFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_930));
	nimln_(427, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1926(tilemaps__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_927);
	nimln_(328, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1392(&spritesheet__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_926);
	nimln_(424, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1891(spritesheets__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_925);
	nimln_(54, "/usr/lib/nim/system/fatal.nim");
	eqdestroy___system_3263((&writePath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_923));
	eqdestroy___system_3263((&assetPath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_922));
	eqdestroy___system_3263((&basePath__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_921));
	nimln_(392, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1754((&controllers__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_897));
	nimln_(389, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1734((&controllerRemovedFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_896));
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1734((&controllerAddedFunc__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_893));
	nimln_(366, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1710(keymap__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_890);
	nimln_(328, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1392(&stencilBuffer__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_790);
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1392(&swCanvas__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_789);
	nimln_(321, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1250((&eventListeners__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_785));
	nimln_(320, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1108((&keyListeners__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_780));
	nimln_(312, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1088((&audioTickCallback__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_771));
	nimln_(302, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_990((&touches__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_763));
	nimln_(53, "/home/manea/.nimble/pkgs/nico-0.4.9/nico/backends/common.nim");
	eqdestroy___OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_270((&keysDown__OOZOOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_191));
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

